#!/usr/bin/env python3
"""Generate /tmp/r39_label_moves.json: every \\newlabel that moved since c9718cf.

Check 35g pins all `\\newlabel` entries of the document against their page at
c9718cf (round 34's commit) and lists the exceptions explicitly. Round 36 wrote
its four exceptions as a literal dict; round 37's list ran to 103 and became
DATA, generated by gen_r37_label_moves.py; round 38 regenerated it after adding
~7.1k characters of appendix text. Round 39 adds 6,939 characters for EXP-BF
(the benign false-positive rate of the parameter-free rule, plus its reference in
bucket 3 of the appendix roadmap), so the appendix tail repaginates again and the
exception list moves with it.

ROUND-39 DIFFERENCE: `ADDED` grows by EXP-BF's two labels. Round 37 added two
with EXP-XP, round 38 added none, and round 39 adds `app:benign_fpr` (the
subsection) and `tab:benign_fpr` (its one table). That is the whole of the
round's label cost, and it is the reason 38f's total moves 225 -> 227 and 28p's
two late appendix float pins each gain one NUMBER. Anything else appearing here
is an unbudgeted float or cross-reference, so the set is asserted rather than
tolerated.

The file records, per moved label, its (float number, page) at c9718cf and now. It
is a record of the round's PRICE, not a licence: the verifier asserts the moved set
is exactly this one, that each move is exactly this delta, that no label with a
c9718cf page inside the 9-page main text appears in it at all, and that the delta
histogram matches -- so a main-text pin sliding, or one more label moving, still
fires.
"""
import io
import json
import re
import subprocess

REPO = "/Users/mediratta/code/paper_writing/AI-Researcher-align"
PAPER = REPO + "/output/adaptive_lie_detector_paper"
DATA = PAPER + "/verification/data/"
PIN = re.compile(r"newlabel\{([^}]*)\}\{\{([^}]*)\}\{(\d+)\}")
# round 37's two EXP-XP labels, plus round 39's two EXP-BF labels. Round 38 added
# nothing to this set.
ADDED = {"app:pacchiardi_census", "tab:pacchiardi_census",
         "app:benign_fpr", "tab:benign_fpr"}


def pins(aux):
    return {m.group(1): (m.group(2), m.group(3)) for m in PIN.finditer(aux)}


def main():
    was = subprocess.run(["git", "show", "c9718cf:output/adaptive_lie_detector_paper/"
                          "main.aux"], cwd=REPO, capture_output=True, text=True)
    was.check_returncode()
    a = pins(was.stdout)
    b = pins(io.open(PAPER + "/main.aux", encoding="utf-8").read())
    print("c9718cf: %d labels    now: %d labels" % (len(a), len(b)))

    added, removed = set(b) - set(a), set(a) - set(b)
    print("added: %s    removed: %s" % (sorted(added), sorted(removed)))
    if added != ADDED or removed:
        raise SystemExit("the label set changed by something other than EXP-XP's "
                         "two round-37 labels and EXP-BF's two round-39 labels; "
                         "re-read the round-39 plan before proceeding")

    moved = {k: [list(a[k]), list(b[k])] for k in sorted(set(a) & set(b))
             if a[k] != b[k]}
    unmoved = len(set(a) & set(b)) - len(moved)

    hist = {}
    for k, (x, y) in moved.items():
        hist[int(y[1]) - int(x[1])] = hist.get(int(y[1]) - int(x[1]), 0) + 1
    print("moved: %d    unmoved: %d    page-delta histogram: %s"
          % (len(moved), unmoved, dict(sorted(hist.items()))))

    # the property the round is costed on: nothing inside the 9-page main text moved
    inside = sorted(k for k in moved if int(moved[k][0][1]) <= 9)
    print("moved labels whose c9718cf page was in the main text: %s" % inside)
    if inside:
        raise SystemExit("a main-text page pin moved; round 39 is costed at zero "
                         "main-text rulers and this contradicts it")

    # and the five main-text float pins 37a names, by label, must be byte-identical
    # to c9718cf -- the same statement 35g makes globally, restated here so this
    # generator fails before writing a record that would license a main-text slide.
    # This is also the machine-checkable form of round 39's one deliberate
    # omission: the benign-FPR clause drafted for sec:hedging_baseline was costed
    # against the ruler budget and dropped, so EXP-BF touches no main-text page.
    for k in ["fig:dag", "tab:claim_ledger", "fig:ladder", "fig:r1c_collapse",
              "tab:external_audit"]:
        if k not in a or k not in b:
            raise SystemExit("main-text float pin %s is missing from one side" % k)
        if a[k] != b[k]:
            raise SystemExit("main-text float pin %s moved %s -> %s" % (k, a[k], b[k]))
    print("the five main-text float pins are unmoved since c9718cf")

    for path in ("/tmp/r39_label_moves.json", DATA + "r39_label_moves.json"):
        json.dump(moved, io.open(path, "w", encoding="utf-8"), indent=1,
                  sort_keys=True)
    print("\nwrote /tmp/r39_label_moves.json and data/r39_label_moves.json "
          "(%d entries)" % len(moved))


if __name__ == "__main__":
    main()
