#!/usr/bin/env python3
"""Build /tmp/verify_r34.py from /tmp/verify_r33.py.

Retains all 1820 round-33 checks. The ones round 34 deliberately changes are
UPDATED IN PLACE with the round-34 reason in a comment, never deleted, per the
standing Part C rule. Then appends GROUP 34.

Round 34 answers a 7/10 Weak Accept (confidence High) whose complaint is
explicitly presentation, not science: "there is an excellent ~8-page paper
buried inside a 90-page research audit" and "I would not add another 10
experiments". So it is a LENGTH round: the appendix is 6,748 characters and two
PDF pages shorter, four main-text edits landed inside a 9-page limit at slack 0,
and three planned edits were WITHDRAWN BY MEASUREMENT rather than forced.
"""
import io

SRC = "/tmp/verify_r33.py"
DST = "/tmp/verify_r34.py"
s = io.open(SRC, encoding="utf-8").read()
n = 0


def sub(old, new, label):
    global s, n
    assert s.count(old) == 1, (label, s.count(old))
    s = s.replace(old, new, 1)
    n += 1
    print(f"  patched: {label}")


# ---- P1. the round-34 edit ledger --------------------------------------------
sub('''R33_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r33_edits.json",
                                                 encoding="utf-8"))]
''',
    '''R33_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r33_edits.json",
                                                 encoding="utf-8"))]
# ROUND-34 EXTENSION: the 44 paragraph-level blocks round 34 applied on top of
# the round-33 commit (225f069). This was the LENGTH round, answering a 7/10
# Weak Accept whose only remaining complaint was presentation -- "an excellent
# ~8-page paper buried inside a 90-page research audit" -- and whose own
# instruction was "I would not add another 10 experiments". So: no experiment,
# no pre-registration, no number changed. 42 of the 44 entries are in
# appendix.tex (A1's deletions of illustrative transcripts and config dumps,
# three batches of A2 condensations that keep every number and drop the
# walk-through prose, A4's four-appendix signpost, and the ADAGE paragraph
# becoming the canonical site for B4's cut); the other two are B1's "What is
# new." label on the already-pinned novelty sentence (introduction-1) and §3.4's
# self-funding swap of the ADAGE clause for the Corollary tie (experiments-1).
# Generated by /tmp/gen_r34_edits.py, the same coalescing opcode walk that
# produced r29..r33_edits.json.
R34_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r34_edits.json",
                                                 encoding="utf-8"))]
''', "P1 R34_EDITS load")

# ---- P2. replay the round-34 blocks before the word-multiset comparison ------
sub('''    predicted = words(rebuilt)
    actual = words(cur_cat)''',
    '''    # ROUND-34 EXTENSION: replay the round-34 blocks on top of the rebuilt
    # round-33 baseline. Unlike round 33 (BOLDED-only) this round is dominated
    # by appendix.tex, so it needs the R31/R32 side-bag pattern: the main-text
    # word bag is BOLDED-only by design, so an appendix entry can never apply to
    # `rebuilt` and gets the stronger two-sided pin instead -- the post-image
    # present exactly once AND the pre-image gone, which is what makes a
    # 6,748-character deletion round auditable rather than asserted.
    r34_side = {"appendix": read("appendix.tex")}
    for name, tag, old, new in R34_EDITS:
        if name not in BOLDED:
            ck(name in r34_side,
               f"round-34 ledger entry {tag} names an unknown non-main file: "
               f"{name}")
            if name not in r34_side:
                continue
            side = r34_side[name]
            ck(side.count(new) >= 1,
               f"round-34 {name} edit {tag} is absent from {name}.tex: "
               f"{new[:80]!r}")
            if len(new) >= 40:
                ck(side.count(new) == 1,
                   f"round-34 {name} edit {tag} appears {side.count(new)}x in "
                   f"{name}.tex, not once -- a double-applied edit: "
                   f"{new[:80]!r}")
            residue = side.replace(new, "") if old in new else side
            ck(residue.count(old) == 0,
               f"round-34 {name} edit {tag} left its pre-image behind in "
               f"{name}.tex: {old[:80]!r}")
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-34 edit does not apply once to the rebuilt "
           f"round-33 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    predicted = words(rebuilt)
    actual = words(cur_cat)''', "P2 R34 replay stage")

sub('''    ck(not lost, f"WORDS LOST that no enumerated round-23..33 edit accounts for: "
                 f"{dict(list(lost.items())[:12])}")
    ck(not gained, f"WORDS GAINED that no enumerated round-23..33 edit accounts "
                   f"for: {dict(list(gained.items())[:12])}")''',
    '''    ck(not lost, f"WORDS LOST that no enumerated round-23..34 edit accounts for: "
                 f"{dict(list(lost.items())[:12])}")
    ck(not gained, f"WORDS GAINED that no enumerated round-23..34 edit accounts "
                   f"for: {dict(list(gained.items())[:12])}")''',
    "P2b ledger message range")

# ---- P3. the page count: 91 -> 89, which IS this round's deliverable ---------
sub('''    ck("Output written on main.pdf (91 pages" in log,
       "page count is not 91 (90 + the round-32 inferential-unit ladder page)")''',
    '''    # ROUND-34 SUBSTITUTION: 91 -> 89, and this is the one check that records
    # the round's actual deliverable. The reviewer's complaint was the document's
    # SIZE ("a 90-page research audit"), so A1/A2 cut 6,748 characters of
    # illustrative transcripts, config dumps and walk-through prose out of the
    # appendix. Pinned as an EQUALITY, in both directions: 90+ means the cuts
    # regressed, 88 or fewer means a later round deleted something this one
    # deliberately kept (the pre-registered material named in 34g).
    ck("Output written on main.pdf (89 pages" in log,
       "page count is not 89 (91 - the two pages round 34's appendix "
       "condensation bought)")''', "P3 page count 91 -> 89")

# ---- P4. tab:prior_work_criteria repages 21 -> 22 ----------------------------
sub('''                           ("tab:prior_work_criteria", "8", "21")]:''',
    '''                           # ROUND-34 SUBSTITUTION: p21 -> p22. Its NUMBER
                           # is unchanged at 8, which is the control: A1 and A2
                           # deleted appendix PROSE, not floats, so nothing
                           # upstream renumbered and only the page packing
                           # moved. A number change here would mean a float was
                           # dropped, which this round did not authorize.
                           ("tab:prior_work_criteria", "8", "22")]:''',
    "P4 tab:prior_work_criteria page")

# ---- P5/P6. the prose-bold ledger gains B1's label --------------------------
sub('''PROSE_BOLD = {"abstract": (18, 17), "introduction": (24, 51),
              "methodology": (29, 58), "experiments": (39, 51),
              "discussion": (6, 5), "conclusion": (10, 15)}''',
    '''# ROUND-34 SUBSTITUTION: introduction 51 -> 52, the single span B1 adds --
# "What is new." in front of the (byte-unchanged) novelty sentence, which is
# their §25.1 and the biggest 7->8 lever they name. experiments is UNCHANGED at
# 51 because §3.4's swap is span-neutral: B4 removes "ADAGE is an apparatus, not
# a contribution" and B2 adds "scale moves the numbers, not the verdict" in the
# same sentence, which is what made B2 self-funding. Every other file unchanged.
PROSE_BOLD = {"abstract": (18, 17), "introduction": (24, 52),
              "methodology": (29, 58), "experiments": (39, 51),
              "discussion": (6, 5), "conclusion": (10, 15)}''',
    "P5 PROSE_BOLD introduction")

sub('''    ck(tot_was == 126 and tot_now == 197,
       f"the prose-bold ledger changed: {tot_was} -> {tot_now}, expected 126 -> 197")''',
    '''    # ROUND-34 SUBSTITUTION: 197 -> 198, the one span B1 adds (see PROSE_BOLD).
    # Net +1 on a round that CUT two pages, because the cutting was all in the
    # appendix, which this ledger does not cover.
    ck(tot_was == 126 and tot_now == 198,
       f"the prose-bold ledger changed: {tot_was} -> {tot_now}, expected 126 -> 198")''',
    "P6 tot_now 197 -> 198")

# ---- P7. round 22's P4 ADAGE pin follows the fact to the appendix ------------
sub('''        ("R8 ADAGE carries nothing (P4)",
         "\\\\textbf{ADAGE is an apparatus, not a contribution}", expt),''',
    '''        # ROUND-34 SUBSTITUTION (B4, the funding cut): round 22's P4 asked that
        # ADAGE be de-emphasized, and the main text carried the span for eleven
        # rounds. Round 34 spent it to fund B1 and B2 -- the reviewer's own §25.4
        # authorizes moving secondary detector analyses out of the main text, and
        # §3.4 is inside the spilling region where a cut is the only thing that
        # pays. The de-emphasis is NOT dropped: app:adage_details now BOLDS it
        # and says so in its own words ("this paragraph is where the paper says
        # so"), so the check follows the fact instead of the file.
        ("R8 ADAGE carries nothing (P4)",
         "\\\\textbf{ADAGE is an apparatus, not a contribution}", app),''',
    "P7 round-22 P4 ADAGE pin -> appendix")

# ---- P8. item E: the same swap, pinned in BOTH directions -------------------
sub('''    ck("ADAGE is an apparatus, not a contribution" in read("experiments.tex"),
       "item E: the ADAGE de-emphasis is gone")''',
    '''    # ROUND-34 SUBSTITUTION (B4): see the note at the round-22 P4 entry above.
    # Updated in BOTH directions, so the round is pinned rather than merely
    # permitted: the main text must NOT carry the span (it is B1/B2's funding),
    # and app:adage_details MUST.
    ck("ADAGE is an apparatus, not a contribution" not in read("experiments.tex"),
       "item E: the ADAGE de-emphasis clause is back in §3.4; round 34 spent it "
       "to fund B1 and B2, on the reviewer's own §25.4")
    ck("\\\\textbf{ADAGE is an apparatus, not a contribution}, and this paragraph "
       "is where the paper says so." in read("appendix.tex"),
       "item E: app:adage_details is not the canonical site for the ADAGE "
       "de-emphasis, so the paper no longer states it anywhere")''',
    "P8 item E ADAGE both directions")

# ---- P9. the 28p appendix pins repack by one page each -----------------------
sub('''    for lab, num, page in [("tab:eccp_decidability", "7", "19"),
                           ("tab:frontier_panel", "9", "23"),
                           ("tab:experiment_summary", "10", "25"),
                           # ROUND-32 SUBSTITUTION: A4's tab:inference_ladder
                           # is a new appendix float at p41, so both of these
                           # shift by exactly one number and one page. Updated
                           # rather than relaxed: a second shift still fires.
                           ("tab:dimension_transfer", "51", "68"),
                           ("tab:covariate_audit", "52", "70")]:''',
    '''    # ROUND-34 SUBSTITUTION: A1/A2 deleted appendix PROSE, never a float, so
    # every NUMBER below is unchanged and only pages move -- the signature of a
    # pure repagination, and the control that proves no table was dropped to buy
    # length. p19 -> p20 for tab:eccp_decidability (its Appendix-A neighbours
    # tab:roadmap 4/p15, tab:criteria 5/p16 and tab:appendix_roadmap 3/p14 are
    # unchanged because A4 ADDED the signpost paragraph upstream of them, which
    # offsets the cuts exactly there); tab:frontier_panel 9/p23 and
    # tab:experiment_summary 10/p25 unchanged; and the two late floats move
    # BACKWARD by one page (p68 -> p67, p70 -> p69), which is the deletion
    # showing up where the deletions are.
    for lab, num, page in [("tab:eccp_decidability", "7", "20"),
                           ("tab:frontier_panel", "9", "23"),
                           ("tab:experiment_summary", "10", "25"),
                           # ROUND-32 SUBSTITUTION: A4's tab:inference_ladder
                           # is a new appendix float at p41, so both of these
                           # shift by exactly one number and one page. Updated
                           # rather than relaxed: a second shift still fires.
                           ("tab:dimension_transfer", "51", "67"),
                           ("tab:covariate_audit", "52", "69")]:''',
    "P9 28p appendix pins")

# ---- P10. 32d: tab:inference_ladder repages 41 -> 40 ------------------------
sub('''        ck(_m32.group(1) == "30" and _m32.group(2) == "41",
           f"32d: tab:inference_ladder moved: now {_m32.group(1)} on "
           f"p{_m32.group(2)}, expected 30 on p41")''',
    '''        # ROUND-34 SUBSTITUTION: p41 -> p40, number unchanged at 30. Same
        # reason as 28p above: A1/A2 removed prose upstream of it, so it packs
        # one page earlier while its float number holds.
        ck(_m32.group(1) == "30" and _m32.group(2) == "40",
           f"32d: tab:inference_ladder moved: now {_m32.group(1)} on "
           f"p{_m32.group(2)}, expected 30 on p40")''',
    "P10 32d inference_ladder page")

# ---- P11. GROUP 34 ----------------------------------------------------------
GROUP34 = r'''
    # ==== GROUP 34 -- the LENGTH round: cut the appendix, not the argument ===
    # Round 34 answers a 7/10 Weak Accept (confidence High, up from 6/10) whose
    # remaining objection is explicitly presentation: "My biggest remaining
    # concern is presentation rather than science: there is an excellent ~8-page
    # paper buried inside a 90-page research audit", plus "I would not add
    # another 10 experiments". So the round runs NO experiment and changes NO
    # number; it makes the document smaller and labels the novelty claim.
    # Three of its seven planned edits were WITHDRAWN BY MEASUREMENT, and this
    # group pins what landed AND what was deliberately not bought.
    intro34, meth34, expt34, concl34, app34 = intro, meth, expt, concl, app

    # ---- 34a. the reduction, asserted as a measured quantity rather than
    # described. 386,189 chars at 225f069 -> 379,441 now: -6,748, which bought
    # exactly two PDF pages (91 -> 89, pinned as an equality at check 1 above).
    # Bounded on BOTH sides: the ceiling catches a regression that puts the
    # narration back, the floor catches a later round gutting the appendix past
    # what this one authorized.
    ck(len(app34) < 382_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441 and a value this high means the cuts were "
       f"reverted")
    ck(len(app34) > 372_000,
       f"34a: appendix.tex is {len(app34)} chars, below what round 34 cut it to "
       f"(379,441) -- something was deleted that this round deliberately kept; "
       f"see 34g")
    # and the cuts cost no cross-reference: every \ref target still has a label
    # somewhere in the document. LaTeX's own "0 undefined" is checked above; this
    # is the source-level twin, which fires on the EDIT rather than on the build.
    _srcs34 = [read(f) for f in MAIN if _exists(f)] + [app34,
               io.open("main.tex", encoding="utf-8").read()]
    _all34 = "\n".join(_srcs34)
    _labels34 = set(re.findall(r"\\label\{([^}]*)\}", _all34))
    _refs34 = set()
    for _m34 in re.finditer(r"\\(?:ref|autoref|cref|pageref|nameref)\{([^}]*)\}",
                            _all34):
        _refs34.add(_m34.group(1))
    ck(not (_refs34 - _labels34),
       f"34a: A1/A2 left dangling cross-references: "
       f"{sorted(_refs34 - _labels34)[:8]}")

    # ---- 34b. A1: what was DELETED, and the fact it carried, at its surviving
    # site. The rule for the round was that nothing load-bearing leaves with the
    # narration, so every deletion is pinned as a (heading gone, fact kept) pair.
    for _gone34 in ["Real LLM Interrogation Transcripts",
                    "Example Interrogation Transcripts",
                    "\\subsection{Lie Mode}", "\\subsection{Truth Mode}",
                    "\\subsection{API Configuration}"]:
        ck(_gone34 not in app34,
           f"34b: A1's deleted block is back in the appendix: {_gone34!r}")
    # the two transcript subsections collapse into one, and BOTH labels survive
    # on it so no \ref breaks -- that is why 34a's dangling-ref scan passes.
    ck("\\subsection{Interrogation Transcripts}" in app34,
       "34b: the surviving transcript section lost its heading")
    ck("\\label{app:real_transcripts}" in app34
       and "\\label{app:transcripts}" in app34,
       "34b: one of the two transcript labels went with the deleted subsections, "
       "which would strand the roadmap's bucket-5 pointer")
    # the ONE transcript kept is the one carrying an analytic point, not an
    # illustration, and it is named as such.
    ck("the one that carries an analytic point rather than an illustration"
       in app34,
       "34b: the transcript section no longer says why exactly one transcript "
       "survived, which is the difference between a cut and an omission")
    ck("Transcript C: RLHF Refusal Cascade" in app34,
       "34b: Transcript C went with the illustrative ones; it is the one the "
       "dual-refusal paragraph and sec:haiku_defensiveness both depend on")
    for _fact34, _why34 in [
            ("50/50 (100\\%) contain target refusal language",
             "the dual-refusal prevalence"),
            ("RLHF safety compliance detection",
             "the characterization of the 97.8% instructed accuracy"),
            ("us.anthropic.claude-haiku-4-5-20251001-v1:0",
             "the Bedrock model ID, i.e. reproducibility of the frontier target"),
            ("greedy decoding", "the decoding setting every number depends on"),
            ("must pretend it is true", "the lie-mode system prompt, verbatim"),
            ("Defend this claim honestly",
             "the truth-mode system prompt, verbatim")]:
        ck(_fact34 in app34,
           f"34b: A1's deletions also removed {_why34}: {_fact34!r}")
    # the two verbatim prompts ARE the intervention E, so they are labelled as
    # such rather than left as configuration trivia.
    ck("\\textbf{The two system prompts below are the intervention $E$ itself}"
       in app34,
       "34b: the surviving config section no longer says the two prompts are the "
       "intervention, which is the only reason they are printed verbatim")
    # the mock-transcript block was a DELETION CANDIDATE and was KEPT, because
    # tab:appendix_roadmap's bucket 4 and tab:experiment_summary both \ref it.
    # Pinned so the letter's account of what was kept is auditable.
    ck("Algorithmic Sanity Checks (Mock Transcripts; Not Predictive of "
       "Real-Model Performance)" in app34,
       "34b: the mock-transcript block was deleted; it is \\ref'd from the "
       "roadmap's bucket 4 and from the experiment summary, and its own title "
       "already warns the reader it predicts nothing")

    # ---- 34c. A2: condensed to results-only, and EVERY NUMBER SURVIVED. The
    # rule was: keep the table or its headline figures, delete the walk-through
    # prose. These are sampled from the condensed blocks -- per-model instructed
    # and equalized detail, leave-one-model-out, zero-shot, hedging, multi-turn,
    # the four self-labelled exploratory blocks, the human baseline and the
    # machine-rater ICC proxy.
    for _n34 in ["83.9", "76.3", "91.4", "82.8", "74.7", "89.9", "75.0",
                 "10.2", "68.5", "0.83", "35.0", "26.0", "54.0", "0.327",
                 "57.6", "0.0045", "93.9", "1.61"]:
        ck(_n34 in app34,
           f"34c: A2's condensation dropped the number {_n34!r}; the rule was "
           f"results-only, not results-lite")
    # the exploratory blocks keep their own self-labelling, which is what lets
    # the roadmap's bucket 4 claim be checked by a reader
    for _ex34 in ["Exploratory: Not Load-Bearing",
                  "\\textbf{This subsection is exploratory and post-hoc.}"]:
        ck(_ex34 in app34,
           f"34c: a condensed exploratory block lost its own warning label: "
           f"{_ex34!r}")

    # ---- 34d. A4, their §10 ("why am I still reading 50 pages of increasingly
    # specialized diagnostics?"): the appendix now names the four sections that
    # carry the argument, one per link of §2.2's load-bearing chain, so a
    # reviewer who reads nothing else knows which four to open.
    ck("\\textbf{If you read four appendices, read these}, one per link of "
       "§\\ref{sec:eval_controls}'s chain:" in app34,
       "34d: the four-appendix signpost is gone, which was the whole answer to "
       "their §10")
    _sign34 = app34[app34.index("If you read four appendices"):]
    _sign34 = _sign34[:_sign34.index("\\begin{table}")]
    for _lab34 in ["app:criteria_taxonomy", "app:r1b", "app:external_audit",
                   "app:crit4_ours"]:
        ck("\\ref{" + _lab34 + "}" in _sign34,
           f"34d: the signpost no longer names {_lab34}, so it points at fewer "
           f"than the four links of the chain")
    ck("\\textbf{Those four carry the argument}" in _sign34,
       "34d: the signpost lost the sentence that makes it a ranking rather than "
       "a list")
    # and tab:appendix_roadmap's caption carries the same four, so the table and
    # the paragraph cannot drift apart
    ck("\\textbf{Four sections in\nbucket~2 carry the argument by themselves}"
       in app34 or "Four sections in bucket~2 carry the argument by themselves"
       in re.sub(r"\s+", " ", app34),
       "34d: tab:appendix_roadmap's caption no longer names the four, so the "
       "signpost and the roadmap can disagree")
    # bucket 5's cell was rewritten to say what the config section now IS
    ck("the two verbatim system prompts that are the intervention $E$, and one "
       "transcript" in app34,
       "34d: the roadmap's bucket-5 cell still advertises the deleted "
       "transcript sections")

    # ---- 34e. B1, their §25.1 and the biggest 7->8 lever they name: the
    # novelty claim already existed, unlabelled and mid-paragraph inside
    # Contribution 2; their complaint was that they had to find it. The sentence
    # is BYTE-UNCHANGED and the label sits immediately in front of it.
    ck("\\textbf{What is new.} \\textbf{The novelty is not the observation that "
       "confounding exists; it is turning a previously implicit causal-validity "
       "requirement into an auditor-executable protocol and showing that "
       "existing behavioral deception benchmarks fail it in empirically "
       "distinct ways.}" in intro34,
       "34e: B1's 'What is new.' label is not immediately in front of the "
       "novelty sentence, or the sentence itself was reworded -- it is pinned "
       "verbatim by round 31 and only the label was authorized")
    ck(intro34.count("\\textbf{What is new.}") == 1,
       f"34e: the introduction carries "
       f"{intro34.count(chr(92) + 'textbf{What is new.}')} 'What is new.' "
       f"labels, expected exactly 1 -- a second one makes the first not a "
       f"novelty statement")
    ck("\\noindent\\textbf{Contribution~2" in intro34,
       "34e: the label was bought by dissolving Contribution 2's own heading; "
       "B1 was a ~20-character insertion, not a restructure")

    # ---- 34f. B2, their §12: they call "scaling does not rescue construct
    # validity" a powerful message without noticing it is already PROVEN at
    # methodology.tex's Corollary. §3.4's frontier numbers now name the Corollary
    # they instantiate. Self-funding: it sits in the same sentence as B4's cut.
    ck("Frontier scale: rule 80--90\\%, pipeline 40--56\\% (EXP-FS; "
       "Appendix~\\ref{app:frontier_panel})---\\textbf{scale moves the numbers, "
       "not the verdict}, which is the Corollary of §\\ref{sec:identification}."
       in expt34,
       "34f: §3.4's frontier sentence no longer ties its numbers to the "
       "Corollary, which is their §12's ask and the reason B2 was free")
    ck("\\paragraph{Corollary (scale does not help).}" in meth34,
       "34f: the Corollary B2 points at is gone, so the pointer dangles")
    ck("No increase in accuracy, model scale, or detector sophistication "
       "resolves this" in meth34,
       "34f: the Corollary lost the clause that makes it about scale")
    # B4's cut left EXP-A/EXP-G and fig:feature_collapse still reachable: the
    # figure had exactly ONE \ref in the whole main text, inside the cut clause,
    # so a pointer had to be kept or the figure would float uncited.
    ck(expt34.count("\\ref{fig:feature_collapse}") >= 1,
       "34f: B4's cut took fig:feature_collapse's only main-text reference with "
       "it, leaving the figure uncited")
    ck("Under neutral prompts and cross-family re-extraction the collapse "
       "reproduces (EXP-A/EXP-G;" in expt34,
       "34f: the EXP-A/EXP-G reproduction clause is gone; B4 cut the ADAGE "
       "framing, not the result")
    # and it obeys check 29n's style rule, which the first draft of this
    # sentence violated: an experiment ID may not open a sentence as its subject
    ck("EXP-A/EXP-G reproduce" not in expt34,
       "34f: the reproduction clause opens with an experiment ID as its "
       "subject, which 29n forbids")

    # ---- 34g. WHAT THIS ROUND REFUSED TO CUT, pinned so the length pressure of
    # a later round cannot quietly take it. The plan's own char target was
    # priced off a set that turned out to be dominated by PRE-REGISTERED
    # material; deleting that would be an integrity problem, not a length win,
    # so the measured reduction (-6,748) is smaller than the planned one and the
    # letter reports the measured number.
    for _keep34, _why34 in [
            ("EXP-XL", "a pre-registered rollout-release audit"),
            ("EXP-XJ", "load-bearing for requirement (iv) in "
                       "tab:external_audit's rows"),
            ("EXP-IT2", "load-bearing for requirement (v)"),
            ("EXP-R1d", "a pre-registered recency check reported INCONCLUSIVE, "
                        "which a prior reviewer asked for"),
            ("Pre-Registered 4th Scenario", "pre-registered"),
            ("Pre-Registered 5th Scenario", "pre-registered")]:
        ck(_keep34 in app34,
           f"34g: round 34's length cuts removed {_keep34}, which was excluded "
           f"from the candidate set: {_why34}")
    # EXP-R1d's inconclusive verdict is stated as a verdict, not buried
    ck("\\textbf{Stated exactly: this run did not establish recency, and the "
       "reason is an instrument failure on three of its four targets, not a "
       "result about the collapse.}" in app34,
       "34g: EXP-R1d's inconclusive verdict lost its own statement; reporting a "
       "paid-for pre-registered null is a strength the letter defends")
    ck("\\textbf{One target is not a panel}" in app34,
       "34g: EXP-R1d lost the pre-registration's own fewer-than-two rule, which "
       "is why no recency claim enters the paper")
    ck("\\textbf{What we got wrong when writing this item}" in app34,
       "34g: the Future Directions item (7) self-correction went with the "
       "condensation; it is the paper correcting its own text and is pinned")
    # Future Directions was CONDENSED, not deleted, and its NUMBERING is
    # preserved because appendix.tex refers to "(7)" by number from two sites.
    ck("\\section{Future Directions}\\label{app:future_directions}" in app34,
       "34g: Future Directions was deleted; it is \\ref'd from the roadmap's "
       "bucket 4 and from EXP-R1d's two correction paragraphs")
    for _i34 in range(1, 13):
        ck("\\textbf{(%d)" % _i34 in app34,
           f"34g: Future Directions item ({_i34}) is gone -- the condensation "
           f"had to preserve the NUMBERING, because two paragraphs cite item "
           f"(7) by number")
    # the criterion-5 transfer block was condensed with its one pinned string
    # left byte-identical
    ck("supplies the cross-model half of criterion~5 and only a thin slice of "
       "the cross-claim half" in app34,
       "34g: the criterion-5 transfer block's pinned scope sentence was "
       "paraphrased by the condensation")
    # and the frozen pre-registration set is untouched ON DISK
    # NB: `CODE` is rebound to a single analysis script inside main() further
    # up, so the repo root is spelled out here rather than reused.
    _pre34 = glob.glob("/Users/mediratta/code/paper_writing/AI-Researcher-align/"
                       "code/adaptive_lie_detector/docs/PREREG_EXP_*.md")
    ck(len(_pre34) >= 16,
       f"34g: {len(_pre34)} PREREG_EXP_*.md files on disk, expected >= 16 -- the "
       f"pre-registrations are frozen and a length round may not touch them")

    # ---- 34h. WITHDRAWN BY MEASUREMENT, pinned so a later round does not
    # assume they landed. All three were priced, not guessed.
    # B3 (their §11, promote the appendix's vintage-independence into the
    # Corollary paragraph): measured at +224, then +162, then +67 characters --
    # ALL THREE SPILLED the document to p10. The §2.1 Corollary sits on a line
    # boundary. methodology.tex is byte-identical to its round-33 state.
    ck("vintage-independent" not in meth34,
       "34h: B3's vintage clause is in methodology.tex, but it was measured at "
       "+67 chars = one spilled page three times over and declined; if it now "
       "fits, the budget changed and the fit test must be re-measured")
    ck("\\textbf{Identification is vintage-independent.}" in app34,
       "34h: B3 was declined on budget on the understanding that the canonical "
       "statement stays in the appendix -- and now it is in neither place")
    # B5 (their §25.3, a consistent strength vocabulary in tab:claim_ledger's
    # Final interpretation column): +6 characters in one cell reflowed a row and
    # spilled the document. The plan's own rule was "if it reflows, skip it".
    ck("\\textbf{Instructed accuracy is regime-dependent}" in meth34
       and "\\textbf{No learned features needed}" in meth34,
       "34h: tab:claim_ledger's claim-2/claim-3 verdict leads were edited; B5 "
       "was declined because +6 chars in that column reflows a row")
    ck("Replicated: accuracy is regime-dependent" not in meth34
       and "Diagnostic: no learned features" not in meth34,
       "34h: B5's rewritten cells are in the table, but they were measured at a "
       "spilled page and reverted")
    # B6 (their §26, the abstract's transition): the 403-word ratchet at 29z
    # forbids any non-word-neutral edit, and 10 of the abstract's 13 sentences
    # are pinned verbatim by earlier rounds' must-fixes -- one of them promoted
    # INTO the abstract at a prior reviewer's request (27g).
    ck("no public release we audited supplies all five" in absr,
       "34h: the abstract's transition sentence was edited; B6 was declined on "
       "the 403-word ratchet, not deferred")

    # ---- 34i. the guards: a length round must change nothing else. Each of
    # these is already pinned above or in group 33; they are restated here
    # because "we cut two pages" is only credible if the spine is provably
    # untouched.
    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "34i: the three structured caution boxes must survive a LENGTH round "
       "unchanged; every reviewer who has commented on them named them a "
       "strength, and they are the first thing a length cut would reach for")
    ck(len([h for h in re.findall(r"\\subsection\{([^}]*)\}", expt34)
            if "Rung" in h]) == 4,
       "34i: round 33's four rung tags did not survive round 34")
    ck("(4)--(5) as a weaker, target-dependent secondary finding" in concl34,
       "34i: round 31's down-weighting of claims (4)-(5) is gone -- it is their "
       "§25.5 ask and it was already satisfied before this round")
    ck("\\textbf{Criteria 1--5 and requirements~(i)--(v) are different lists}"
       in meth34,
       "34i: round 33's numbering disambiguation went with the length cuts")
    ck("this paper reaches rung 4, not rung 5" in meth34,
       "34i: the rung-4-not-5 callout is gone")
    # no experiment ran: the experiment roster is unchanged in COUNT
    ck("\\label{tab:experiment_summary}" in app34,
       "34i: the experiment summary table is gone, so the claim that no "
       "experiment was added or removed cannot be checked")
'''

sub("""
    # ---- report -----------------------------------------------------------
    if fails:""", GROUP34 + """
    # ---- report -----------------------------------------------------------
    if fails:""", "P11 GROUP 34")

io.open(DST, "w", encoding="utf-8").write(s)
print(f"wrote {DST} ({n} patches, {len(s)} chars)")
