#!/usr/bin/env python3
"""Build /tmp/verify_r37.py from /tmp/verify_r36.py.

Round 37 mines the NeurIPS 2026 workshop TAE review into the ICLR tree: six
landed parts (A-F), one new pre-registered experiment (EXP-XP), and one new
descriptive arm (claim-clustered intervals on EXP-C4B's H1).

Under the standing rule ALL 2463 round-36 checks are RETAINED. The ones this
round deliberately changes are UPDATED, each with the round-37 reason in a
comment, never deleted. There is no pass 1 here: round 36 needed span alignment
because it rewrote punctuation under 84 pinned literals; round 37 changes text
at ten enumerated paragraph sites, so every affected check is named below.

The substitution discipline is the same as every earlier mk_verify_r*.py: each
`old` must occur EXACTLY ONCE in the source or nothing is written. That
assertion is what enforces the read-back rule -- a paraphrased anchor fails
loudly instead of silently landing in the wrong place.

The one structural addition is UNDO37. verify_r36.py carries the 538-pair
em-dash ledger and un-converts live text so the round-23..35 pins can be
asserted byte-exactly. The round-37 ledger is generated from UNCONVERT(parent)
against UNCONVERT(tree), i.e. it lives in PRE-round-36 punctuation. So:

  * a forward R37 stage can be appended to 13g's replay after the R35 stage,
    because `rebuilt` is in pre-round-36 punctuation at that point; and
  * every historical pin that reads the live tree is routed through
    UNDO37(UNCONVERT(text, name), name), which by construction restores
    UNCONVERT(ea6faf9) byte-for-byte -- so those checks pass for the same
    reason they passed at the parent commit, not because they were weakened.
"""
import io
import json
import sys

D = ("/Users/mediratta/code/paper_writing/AI-Researcher-align/output/"
     "adaptive_lie_detector_paper")
SRC = "/tmp/verify_r36.py"
OUT = "/tmp/verify_r37.py"

src = io.open(SRC, encoding="utf-8").read()
out = src

subs = []


def sub(old, new, label):
    subs.append((old, new, label))


# =========================================================== (a) UNDO37 itself
sub(r'''    for _o, _n in R36_BY_FILE.get(name, []):
        text = text.replace(_n, _o)
    return text
''',
    r'''    for _o, _n in R36_BY_FILE.get(name, []):
        text = text.replace(_n, _o)
    return text


# ROUND-37: the TAE-review round. Ten paragraph-level edits over methodology.tex
# (1), appendix.tex (7) and related_work.tex (2). The ledger is generated by
# gen_r37_edits.py as a diff of UNCONVERT(ea6faf9) against UNCONVERT(tree), so it
# is expressed in PRE-round-36 punctuation -- which is what lets 13g replay it
# forward after the R35 stage, and what makes an `old` that overlaps a round-36
# post-image structurally impossible (asserted in 37b anyway).
R37_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r37_edits.json",
                                                 encoding="utf-8"))]
R37_BY_FILE = {}
for _n37, _t37, _o37, _x37 in R37_EDITS:
    R37_BY_FILE.setdefault(_n37, []).append((_o37, _x37))


def UNDO37(text, name):
    """Invert round 37 on already-un-converted text: UNDO37(UNCONVERT(live)).

    Rounds 30-35 pin their own ledgers' post-edit text against the live appendix
    and related_work, and 35f asserts byte-identity against c9718cf. Round 37
    rewrote ten of those paragraphs, so those pins are asserted against the
    un-done text rather than restated more loosely -- the historical assertion is
    preserved exactly, and round 37 is the documented reason. Applied in reverse
    ledger order, which is the exact inverse of the forward replay.
    """
    for _o, _n in reversed(R37_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text
''',
    "(a) inject R37_EDITS + UNDO37")

# ============================================= (b) the five historical side-bags
sub(r'''    # ROUND-36: un-convert before replaying a round-30 pin (see UNCONVERT)
    appx_led = UNCONVERT(read("appendix.tex"), "appendix")''',
    r'''    # ROUND-36: un-convert before replaying a round-30 pin (see UNCONVERT)
    # ROUND-37: and un-do round 37, whose appendix-2 pair rewrote the
    # tab:experiment_summary block this round-30 pin lands in (see UNDO37).
    appx_led = UNDO37(UNCONVERT(read("appendix.tex"), "appendix"), "appendix")''',
    "(b) round-30 appx_led")

sub(r'''    # ROUND-36: un-convert before replaying round-31 pins (see UNCONVERT)
    r31_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix"),
                "related_work": UNCONVERT(read("related_work.tex"),
                                          "related_work")}''',
    r'''    # ROUND-36: un-convert before replaying round-31 pins (see UNCONVERT)
    # ROUND-37: then un-do round 37 (see UNDO37). Not currently load-bearing for
    # these pins, and applied anyway: UNDO37(UNCONVERT(live)) is exactly
    # UNCONVERT(ea6faf9), so a later round-37-style edit inside a round-31 pin
    # cannot silently retire it.
    r31_side = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"),
                "related_work": UNDO37(UNCONVERT(read("related_work.tex"),
                                                 "related_work"),
                                       "related_work")}''',
    "(b) round-31 side bag")

sub(r'''    # ROUND-36: un-convert before replaying a round-32 pin (see UNCONVERT)
    r32_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix")}''',
    r'''    # ROUND-36: un-convert before replaying a round-32 pin (see UNCONVERT)
    # ROUND-37: then un-do round 37 (see UNDO37), same reason as the round-31 bag.
    r32_side = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix")}''',
    "(b) round-32 side bag")

sub(r'''    # ROUND-36: un-convert before replaying round-34 pins (see UNCONVERT)
    r34_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix")}''',
    r'''    # ROUND-36: un-convert before replaying round-34 pins (see UNCONVERT)
    # ROUND-37: then un-do round 37 (see UNDO37), same reason as the round-31 bag.
    r34_side = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix")}''',
    "(b) round-34 side bag")

sub(r'''    # ROUND-36: un-convert before replaying round-35 pins (see UNCONVERT)
    r35_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix"),
                "related_work": UNCONVERT(read("related_work.tex"),
                                          "related_work")}''',
    r'''    # ROUND-36: un-convert before replaying round-35 pins (see UNCONVERT)
    # ROUND-37: and un-do round 37, whose related_work-1 pair rewrote the
    # black-box-approaches paragraph that carries a round-35 citation-key pin,
    # and whose appendix pairs rewrote three blocks round 35 also touched.
    r35_side = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"),
                "related_work": UNDO37(UNCONVERT(read("related_work.tex"),
                                                 "related_work"),
                                       "related_work")}''',
    "(b) round-35 side bag")

# ================================================ (c) the forward R37 stage in 13g
sub(r'''        ck(rebuilt.count(old) == 1,
           f"enumerated round-35 edit does not apply once to the rebuilt "
           f"round-34 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    # ROUND-35 BIBLIOGRAPHY AUDIT (20 Sep 2026), pinned as facts so a later round''',
    r'''        ck(rebuilt.count(old) == 1,
           f"enumerated round-35 edit does not apply once to the rebuilt "
           f"round-34 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    # ROUND-37 EXTENSION: the 10 paragraph-level blocks round 37 applied on top of
    # the round-35/36 commit (ea6faf9), answering the NeurIPS 2026 workshop TAE
    # review. Exactly one is in a BOLDED file -- methodology-1, Part B's
    # aliasing/mediator gloss, which is word-neutral to within +20 characters -- so
    # the word bag above closes on it. The other nine are appendix.tex (7) and
    # related_work.tex (2) and take rounds 31-35's two-sided side-bag form: the
    # post-image present exactly once AND the pre-image gone.
    #
    # Why this stage can be FORWARD while round 36's could not: the round-36 ledger
    # is a punctuation conversion whose widened context overlaps text that later
    # rounds also edit, so a forward R36 stage would fail count==1. The round-37
    # ledger is generated from UNCONVERT(ea6faf9) against UNCONVERT(tree), i.e. in
    # the same pre-round-36 punctuation `rebuilt` is already in, so it replays
    # directly -- and 37b asserts that no round-37 pre-image lies inside a round-36
    # post-image, which is the hazard that would otherwise couple the two ledgers.
    r37_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix"),
                "related_work": UNCONVERT(read("related_work.tex"),
                                          "related_work")}
    for name, tag, old, new in R37_EDITS:
        if name not in BOLDED:
            ck(name in r37_side,
               f"round-37 ledger entry {tag} names an unknown non-main file: "
               f"{name}")
            if name not in r37_side:
                continue
            side = r37_side[name]
            ck(side.count(new) >= 1,
               f"round-37 {name} edit {tag} is absent from {name}.tex: "
               f"{new[:80]!r}")
            if len(new) >= 40:
                ck(side.count(new) == 1,
                   f"round-37 {name} edit {tag} appears {side.count(new)}x in "
                   f"{name}.tex, not once -- a double-applied edit: "
                   f"{new[:80]!r}")
            residue = side.replace(new, "") if old in new else side
            ck(residue.count(old) == 0,
               f"round-37 {name} edit {tag} left its pre-image behind in "
               f"{name}.tex: {old[:80]!r}")
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-37 edit does not apply once to the rebuilt "
           f"round-35 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    # ROUND-35 BIBLIOGRAPHY AUDIT (20 Sep 2026), pinned as facts so a later round''',
    "(c) forward R37 stage")

sub(r'''    ck(not lost, f"WORDS LOST that no enumerated round-23..35 edit accounts for: "''',
    r'''    ck(not lost, f"WORDS LOST that no enumerated round-23..37 edit accounts for: "''',
    "(c) word-bag LOST message")

sub(r'''    ck(not gained, f"WORDS GAINED that no enumerated round-23..35 edit accounts "''',
    r'''    ck(not gained, f"WORDS GAINED that no enumerated round-23..37 edit accounts "''',
    "(c) word-bag GAINED message")

# ================================================================ (d) page count
sub(r'''    ck("Output written on main.pdf (89 pages" in log,
       "page count is not 89 (91 - the two pages round 34's appendix "
       "condensation bought)")''',
    r'''    # ROUND-37 SUBSTITUTION: 89 -> 93. The round adds ~17.4k characters of
    # APPENDIX text (EXP-XP's census subsection and table, Part A's two Pacchiardi
    # paragraphs, Part C's bank-width and frozen-weights disclosures, Part D's
    # interval paragraph) plus a main.tex availability sentence that renders on
    # p10-p11. The 9-page main text is unchanged, which is what 37a proves from the
    # margin rulers; these four pages are all appendix. Still an EQUALITY in both
    # directions: 94+ means an unbudgeted add, 92 or fewer means a later round
    # deleted material this one deliberately landed.
    ck("Output written on main.pdf (93 pages" in log,
       "page count is not 93 (89 + the four appendix pages round 37's "
       "EXP-XP census and Parts A/C/D disclosures cost)")''',
    "(d) build-log page count 89 -> 93")

# ======================================== (e) code-repo cleanliness, three sites
sub(r'''    g = subprocess.run(["git", "status", "--porcelain"], capture_output=True,
                       text=True, cwd=CODEREPO)
    ck(g.stdout.strip() == "" or all(
        l.strip().startswith("??") for l in g.stdout.strip().split("\n")),
       f"the code repo has uncommitted TRACKED changes:\n{g.stdout}")
    d = subprocess.run(["git", "diff", "--", "docs/"], capture_output=True,
                       text=True, cwd=CODEREPO)
    ck(d.stdout.strip() == "", "docs/ (the pre-registrations) were modified")''',
    r'''    # ROUND-37 SUBSTITUTION. Round 37 deliberately adds code-repo deliverables
    # (EXP-XP's pre-registration, fetcher and census script; the crit4b interval
    # script; three result/manifest files) and appends one section to
    # PREREG_EXP_C4B.md's append-only log. Commit happens only on request, so the
    # tree is dirty by design between the work and the commit. The old form accepted
    # ANY untracked file and forbade ANY docs/ diff; the new form is an explicit
    # ALLOW-SET and is strictly STRONGER on untracked files -- a stray untracked
    # result file now fails where it used to pass. It also passes unchanged once the
    # round is committed, because an empty status satisfies it trivially.
    R37_UNTRACKED = {
        "adaptive_lie_detector/docs/PREREG_EXP_XP.md",
        "adaptive_lie_detector/experiments/fetch_pacchiardi_release.py",
        "adaptive_lie_detector/experiments/analyze_pacchiardi_census.py",
        "adaptive_lie_detector/experiments/analyze_crit4b_ci.py",
        "adaptive_lie_detector/data/external/pacchiardi_release_manifest.json",
        "adaptive_lie_detector/data/results/pacchiardi_census.json",
        "adaptive_lie_detector/data/results/crit4b_ci.json",
    }
    R37_TRACKED = {".gitignore",
                   "adaptive_lie_detector/docs/PREREG_EXP_C4B.md"}
    g = subprocess.run(["git", "status", "--porcelain"], capture_output=True,
                       text=True, cwd=CODEREPO)
    _unexpected37 = []
    for _ln37 in g.stdout.strip().split("\n"):
        _ln37 = _ln37.strip()
        if not _ln37:
            continue
        _st37, _pt37 = _ln37[:2].strip(), _ln37[2:].strip()
        if _st37 == "??" and _pt37 in R37_UNTRACKED:
            continue
        if _st37 == "M" and _pt37 in R37_TRACKED:
            continue
        _unexpected37.append(_ln37)
    ck(not _unexpected37,
       f"the code repo is dirty by something other than round 37's enumerated "
       f"deliverables:\n" + "\n".join(_unexpected37))
    d = subprocess.run(["git", "diff", "--numstat", "--", "docs/"],
                       capture_output=True, text=True, cwd=CODEREPO)
    _docs37 = [_l.split("\t") for _l in d.stdout.strip().split("\n") if _l.strip()]
    ck(all(_r37[1] == "0" for _r37 in _docs37),
       f"docs/ (the pre-registrations) lost lines; every pre-registration is "
       f"frozen and only its append-only log may grow: {d.stdout!r}")
    ck({_r37[2] for _r37 in _docs37}
       <= {"adaptive_lie_detector/docs/PREREG_EXP_C4B.md"},
       f"a pre-registration other than PREREG_EXP_C4B.md was modified: "
       f"{sorted(_r37[2] for _r37 in _docs37)}")''',
    "(e) code-repo status allow-set")

sub(r'''    st_lines = [ln for ln in st.splitlines() if not CKPT.match(ln.strip())]
    st_filtered = "\n".join(st_lines).strip()
    ck(st_filtered == "",
       f"28o: the code repo's working tree is not clean (run checkpoints "
       f"excluded): {st_filtered!r}")''',
    r'''    # ROUND-37 SUBSTITUTION: the same allow-set as check 9, for the same reason --
    # the round's own deliverables are uncommitted until the user asks for a commit.
    # Named by exact path, so a stray file still fires, and satisfied trivially once
    # the round is committed.
    def _ok37(_ln):
        if CKPT.match(_ln.strip()):
            return True
        _s, _p = _ln[:2].strip(), _ln[2:].strip()
        return ((_s == "??" and _p in R37_UNTRACKED)
                or (_s == "M" and _p in R37_TRACKED))

    st_lines = [ln for ln in st.splitlines() if not _ok37(ln)]
    st_filtered = "\n".join(st_lines).strip()
    ck(st_filtered == "",
       f"28o: the code repo's working tree is not clean (run checkpoints and "
       f"round 37's enumerated deliverables excluded): {st_filtered!r}")''',
    "(e) 28o working-tree allow-set")

# ============================ (e2) one narrative SHA the history rewrite renumbered
# Check 28o's comment cites the round-28 commit that first tracked EXP-AF's three
# files. The 2026-09-22 `git filter-repo --strip-blobs-bigger-than 50M` pass (run to
# drop four blobs over GitHub's 100 MB per-file limit, which had made the code repo
# unpushable) renumbered every commit SHA, so b499458 no longer resolves. Same
# commit, same tree, new name: b499458 -> 644d10f. Comment only -- no check changes
# behaviour -- but a dangling SHA in an audit trail is exactly what this apparatus
# exists to prevent, so it is corrected rather than left to rot.
sub(r'''    # *untracked* set until code b499458 committed them. The invariant this''',
    r'''    # *untracked* set until code 644d10f committed them. The invariant this''',
    "(e2) round-28 narrative SHA b499458 -> 644d10f")

# ============================================================ (f) 27j, 16 -> 17
sub(r'''    ck(len(pre) == 16, f"27j: {len(pre)} pre-registrations, expected 16 "
                       f"(12 frozen + EXP-AD + EXP-AE + EXP-AF + EXP-FS)")
    for f in ["PREREG_EXP_AD.md", "PREREG_EXP_AE.md", "PREREG_EXP_AF.md",
              "PREREG_EXP_FS.md"]:
        ck(f in pre, f"27j: docs/{f} is missing")''',
    r'''    # ROUND-37 SUBSTITUTION: 16 -> 17, EXP-XP's pre-registration (the census of
    # the audit target's own release). A NEW file is not an edit to a frozen one;
    # 37g asserts the other 16 are byte-identical to the pinned commit.
    ck(len(pre) == 17, f"27j: {len(pre)} pre-registrations, expected 17 "
                       f"(12 frozen + EXP-AD + EXP-AE + EXP-AF + EXP-FS + "
                       f"EXP-XP)")
    for f in ["PREREG_EXP_AD.md", "PREREG_EXP_AE.md", "PREREG_EXP_AF.md",
              "PREREG_EXP_FS.md", "PREREG_EXP_XP.md"]:
        ck(f in pre, f"27j: docs/{f} is missing")''',
    "(f) 27j prereg count 16 -> 17")

# ====================================================== (g) 28p appendix floats
sub(r'''                           ("tab:dimension_transfer", "51", "67"),
                           ("tab:covariate_audit", "52", "69")]:''',
    r'''                           # ROUND-37 SUBSTITUTION: EXP-XP's tab:pacchiardi_census
                           # is a new appendix float upstream of both, so each
                           # gains one number; and ~17.4k characters of new
                           # appendix prose push them three pages later. Updated
                           # rather than relaxed -- a further shift still fires,
                           # and 37a asserts no MAIN-TEXT pin moved at all.
                           ("tab:dimension_transfer", "52", "70"),
                           ("tab:covariate_audit", "53", "72")]:''',
    "(g) 28p two appendix float pins")

# ========================================== (h) the two Part B literal rewrites
sub(r'''    ck("\\textbf{Outside deception the precondition is thus decidable and "
       "decided; the magnitude is measured only for deception}" in meth,''',
    r'''    # ROUND-37 SUBSTITUTION: "is thus decidable" -> "is decidable". Part B's
    # aliasing gloss is word-neutral, and `thus` is one of the two words that paid
    # for it (the other is "stated in full in Appendix" -> "are in Appendix"). The
    # decidable/measured split itself is unchanged, which is what this pins.
    ck("\\textbf{Outside deception the precondition is decidable and "
       "decided; the magnitude is measured only for deception}" in meth,''',
    "(h) 29x methodology literal")

sub(r'''    ck("\\textbf{The ECCP names a benchmark-design instance of standard pathway "
       "non-identifiability, not a new theoretical result}" in meth31,''',
    r'''    # ROUND-37 SUBSTITUTION: Part B, the review's W6. The paper used "confound" in
    # the design-of-experiments ALIASING sense while its formal apparatus is a
    # causal graph in which deception is a MEDIATOR, and it separately and
    # correctly uses the common-cause sense for the residual latent U. A
    # causal-inference reviewer reads the second and trips. The gloss names the
    # sense at the definition site, in +20 characters and 0 rulers; round 31's
    # concession is otherwise word-for-word what it was.
    ck("\\textbf{The ECCP names a benchmark-design instance of standard pathway "
       "non-identifiability (\\emph{aliasing}, not common causation), not a new "
       "theoretical result}" in meth31,''',
    "(h) 31e ECCP literal")

sub(r'''    _eccp35 = ("\\textbf{The ECCP names a benchmark-design instance of standard "
               "pathway non-identifiability, not a new theoretical result}")''',
    r'''    # ROUND-37 SUBSTITUTION: the same Part B gloss as 31e. The ORDER assertion
    # below -- disclaimer before the Proposition-instantiation sentence -- is round
    # 35's claim and is unchanged.
    _eccp35 = ("\\textbf{The ECCP names a benchmark-design instance of standard "
               "pathway non-identifiability (\\emph{aliasing}, not common "
               "causation), not a new theoretical result}")''',
    "(h) 35a _eccp35 literal")

# ========================================================== (i) 34a size bounds
sub(r'''    ck(len(app34) < 382_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441 and a value this high means the cuts were "
       f"reverted")
    ck(len(app34) > 372_000,
       f"34a: appendix.tex is {len(app34)} chars, below what round 34 cut it to "
       f"(379,441) -- something was deleted that this round deliberately kept; "
       f"see 34g")''',
    r'''    # ROUND-37 SUBSTITUTION: the LIVE band moves, because round 37 adds ~17.4k
    # characters of appendix text on purpose (EXP-XP, Parts A/C/D). Round 34's
    # claim is not weakened by re-banding the live number: it is RESTORED at full
    # strength immediately below, where un-doing round 37 and un-converting round
    # 36 must land back inside round 34's original 372,000-382,000 window. So a
    # reverted condensation still fires, at the number round 34 measured.
    ck(len(app34) < 400_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441 and round 37 added 17,390 for EXP-XP and "
       f"Parts A/C/D -- a value this high means more than that landed")
    ck(len(app34) > 390_000,
       f"34a: appendix.tex is {len(app34)} chars, below round 34's 379,441 plus "
       f"round 37's 17,390 -- something was deleted that one of the two rounds "
       f"deliberately kept; see 34g and 37e")
    _app34_r34 = UNDO37(UNCONVERT(app34, "appendix"), "appendix")
    ck(len(_app34_r34) < 382_000,
       f"34a: with rounds 36 and 37 inverted appendix.tex is {len(_app34_r34)} "
       f"chars; round 34's condensation took it from 386,189 to 379,441 and a "
       f"value this high means the cuts were reverted")
    ck(len(_app34_r34) > 372_000,
       f"34a: with rounds 36 and 37 inverted appendix.tex is {len(_app34_r34)} "
       f"chars, below what round 34 cut it to (379,441) -- something was deleted "
       f"that round 34 deliberately kept; see 34g")''',
    "(i) 34a appendix size band")

# ================================================= (j) 35a methodology char pin
sub(r'''    ck(len(meth35) == 15_669,
       f"35a: methodology.tex is {len(meth35)} chars, expected 15,669 (15,687 "
       f"before round 36's three repunctuations) -- Part C is a pure move and Part "
       f"A is confined to five \\rungrow column-1 arguments, so any other value "
       f"means an unledgered edit entered §2")
    ck(len(UNCONVERT(meth35, "methodology")) == 15_687,
       f"35a: un-converting round 36 leaves methodology.tex at "
       f"{len(UNCONVERT(meth35, 'methodology'))} chars, not the 15,687 round 35 "
       f"pinned -- so round 36 did more to §2 than repunctuate it")''',
    r'''    # ROUND-37 SUBSTITUTION: 15,669 -> 15,689. Part B's aliasing gloss adds 61
    # characters at the ECCP definition and funds 41 of them in place ("stated in
    # full in Appendix" -> "are in Appendix", and one "thus"), for a net +20 at 0
    # rulers. Round 35's number is RESTORED at full strength on the third check:
    # un-doing round 37 and un-converting round 36 must give back exactly 15,687,
    # so "Part C is a pure move" is still asserted against the number it was
    # measured at, and an unledgered edit entering §2 still fires.
    ck(len(meth35) == 15_689,
       f"35a: methodology.tex is {len(meth35)} chars, expected 15,689 (15,669 "
       f"before round 37's +20 Part B gloss) -- Part C is a pure move and Part "
       f"A is confined to five \\rungrow column-1 arguments, so any other value "
       f"means an unledgered edit entered §2")
    ck(len(UNCONVERT(meth35, "methodology")) == 15_707,
       f"35a: un-converting round 36 leaves methodology.tex at "
       f"{len(UNCONVERT(meth35, 'methodology'))} chars, not the 15,707 the "
       f"round-37 tree gives -- so round 36 did more to §2 than repunctuate it")
    ck(len(UNDO37(UNCONVERT(meth35, "methodology"), "methodology")) == 15_687,
       f"35a: un-doing rounds 37 and 36 leaves methodology.tex at "
       f"{len(UNDO37(UNCONVERT(meth35, 'methodology'), 'methodology'))} chars, "
       f"not the 15,687 round 35 pinned -- so one of the two rounds did more to "
       f"§2 than its ledger accounts for")''',
    "(j) 35a methodology char counts")

# ================================================================ (k) 35d stamp
sub(r'''    _stamp35 = ("\\textbf{Build identity.} Source revision~35, built "
                "20~September~2026 from parent\ncommit \\texttt{c9718cf}.")''',
    r'''    # ROUND-37 SUBSTITUTION: the revision number increments once per REVIEW round
    # and this is a new one (the NeurIPS workshop TAE review), so 35 -> 37 with the
    # date and the parent commit advancing together. A stamp naming an older parent
    # on a newer tree is exactly the provenance drift the stamp exists to catch.
    _stamp35 = ("\\textbf{Build identity.} Source revision~37, built "
                "22~September~2026 from parent\ncommit \\texttt{ea6faf9}.")''',
    "(k) 35d build stamp literal")

sub(r'''        ck("Source revision 35" not in _f35,
           f"35d: the build stamp rendered on p{_pg35}, inside the 9-page main "
           f"text -- it was costed as free because it lands after it")''',
    r'''        # ROUND-37 SUBSTITUTION: 35 -> 37, the stamp's own revision number.
        ck("Source revision 37" not in _f35,
           f"35d: the build stamp rendered on p{_pg35}, inside the 9-page main "
           f"text -- it was costed as free because it lands after it")''',
    "(k) 35d stamp absent pp.1-9")

sub(r'''    ck("Source revision 35" in " ".join(subprocess.run(''',
    r'''    # ROUND-37 SUBSTITUTION: 35 -> 37, the stamp's own revision number. Still p11,
    # so Part F's availability sentence (which precedes it) is also outside p1-9.
    ck("Source revision 37" in " ".join(subprocess.run(''',
    "(k) 35d stamp present p11")

# ========================================== (l) 35f byte-identity, via UNDO37
sub(r'''        ck(UNCONVERT(read(_f35 + ".tex"), _f35) == _rename35(_was35),
           f"35f: {_f35}.tex differs from c9718cf by more than the two citation-key "''',
    r'''        # ROUND-37: un-do round 37 first (see UNDO37). Round 37 rewrote ten
        # paragraphs across appendix.tex and related_work.tex; UNDO37(UNCONVERT(.))
        # is by construction UNCONVERT(ea6faf9), so round 35's claim -- that
        # nothing but the two key renames and the two Gemma cites touched these
        # files -- is asserted byte-exactly, not restated more loosely.
        ck(UNDO37(UNCONVERT(read(_f35 + ".tex"), _f35), _f35)
           == _rename35(_was35),
           f"35f: {_f35}.tex differs from c9718cf by more than the two citation-key "''',
    "(l) 35f rename-tolerant identity")

sub(r'''            ck(UNCONVERT(read(_f35 + ".tex"), _f35) == _was35,
               f"35f: {_f35}.tex is not byte-identical to c9718cf once round 36's "
               f"repunctuation is inverted; it cites neither renamed key, so "
               f"nothing but round 36 may touch it")''',
    r'''            # ROUND-37: un-do round 37 too (see UNDO37). It is a no-op on these
            # two files -- neither appears in the round-37 ledger -- and applying
            # it makes that a consequence of the assertion rather than a comment.
            ck(UNDO37(UNCONVERT(read(_f35 + ".tex"), _f35), _f35) == _was35,
               f"35f: {_f35}.tex is not byte-identical to c9718cf once rounds 36 "
               f"and 37 are inverted; it cites neither renamed key, so nothing "
               f"but those two rounds may touch it")''',
    "(l) 35f strict identity, abstract/discussion")

# =============================================== (m) 35g the float-pin inventory
sub(r'''        ck(len(_a35) == 223 and len(_b35) == 223,
           f"35g: the document has {len(_b35)} labels, c9718cf had "
           f"{len(_a35)}, expected 223 in both")''',
    r'''        # ROUND-37 SUBSTITUTION: 223 -> 225 on the live side. EXP-XP adds exactly
        # two labels, app:pacchiardi_census and tab:pacchiardi_census, and the
        # added set is asserted exactly below -- so a third new label fires.
        ck(len(_a35) == 223 and len(_b35) == 225,
           f"35g: the document has {len(_b35)} labels, c9718cf had "
           f"{len(_a35)}, expected 223 then and 225 now")''',
    "(m) 35g label counts")

sub(r'''        _R36_MOVED = {"app:causal_probes": (("AQ", "86"), ("AQ", "87")),
                      "app:exp_i_4th_scenario": (("AQ.1", "86"), ("AQ.1", "87")),
                      "app:machine_icc": (("AR", "89"), ("AR", "88")),
                      "tab:td_vs_fd": (("62", "87"), ("62", "86"))}
        ck(set(_moved35) == set(_R36_MOVED),
           f"35g: the labels that moved off their c9718cf page are "
           f"{sorted(_moved35)}, not the four appendix pins round 36's em-dash "
           f"conversion is costed at ({sorted(_R36_MOVED)})")
        for _k36 in sorted(set(_moved35) & set(_R36_MOVED)):
            ck((_a35[_k36], _b35[_k36]) == _R36_MOVED[_k36],
               f"35g: {_k36} moved {_a35[_k36]} -> {_b35[_k36]}, not the "
               f"{_R36_MOVED[_k36][0]} -> {_R36_MOVED[_k36][1]} round 36 is "
               f"costed at")
        ck(not (set(_a35) ^ set(_b35)),
           f"35g: the label set changed: "
           f"{sorted(set(_a35) ^ set(_b35))[:8]}")''',
    r'''        # ROUND-37 SUBSTITUTION. Round 36's four-label exception list becomes a
        # 103-label one: round 37 adds ~17.4k characters of appendix text, so the
        # appendix tail repaginates. Transcribing 103 entries by hand is precisely
        # the near-miss substitution the read-back rule exists to prevent, so the
        # record is DATA -- /tmp/r37_label_moves.json, written by
        # gen_r37_label_moves.py, the same idiom as the round-23..37 edit ledgers.
        #
        # It is a record of the round's PRICE, not a licence, and it is STRICTER
        # than round 36's form on the property that matters: the moved set must be
        # exactly this one, each move exactly this delta, the delta histogram
        # exactly this, the added label set exactly EXP-XP's two, nothing removed,
        # and -- the costing claim itself -- NO label whose c9718cf page was inside
        # the 9-page main text may appear at all. A main-text pin sliding, or a
        # 104th label moving, still fires.
        _R37_MOVED = {_k: (tuple(_v[0]), tuple(_v[1])) for _k, _v in
                      json.load(io.open("/tmp/r37_label_moves.json",
                                        encoding="utf-8")).items()}
        ck(len(_R37_MOVED) == 103,
           f"35g: the round-37 move record has {len(_R37_MOVED)} entries, not the "
           f"103 gen_r37_label_moves.py measured")
        ck(set(_moved35) == set(_R37_MOVED),
           f"35g: the labels that moved off their c9718cf page are not the 103 "
           f"appendix pins round 37's appendix additions are costed at; "
           f"symmetric difference: "
           f"{sorted(set(_moved35) ^ set(_R37_MOVED))[:8]}")
        for _k37 in sorted(set(_moved35) & set(_R37_MOVED)):
            ck((_a35[_k37], _b35[_k37]) == _R37_MOVED[_k37],
               f"35g: {_k37} moved {_a35[_k37]} -> {_b35[_k37]}, not the "
               f"{_R37_MOVED[_k37][0]} -> {_R37_MOVED[_k37][1]} round 37 is "
               f"costed at")
        _hist37 = {}
        for _k37, (_x37, _y37) in _R37_MOVED.items():
            _d37 = int(_y37[1]) - int(_x37[1])
            _hist37[_d37] = _hist37.get(_d37, 0) + 1
        ck(_hist37 == {-1: 3, 1: 23, 2: 3, 3: 66, 4: 8},
           f"35g: the page-delta histogram of the moved appendix pins is "
           f"{dict(sorted(_hist37.items()))}, not the "
           f"{{-1: 3, 1: 23, 2: 3, 3: 66, 4: 8}} round 37 is costed at")
        ck(not [_k37 for _k37 in _R37_MOVED
                if int(_R37_MOVED[_k37][0][1]) <= 9],
           f"35g: a label whose c9718cf page was inside the 9-page main text "
           f"moved: "
           f"{[_k for _k in _R37_MOVED if int(_R37_MOVED[_k][0][1]) <= 9]} -- "
           f"round 37 is costed at zero main-text rulers and this contradicts it")
        # ROUND-37 SUBSTITUTION: the label SET may now differ, by exactly EXP-XP's
        # two labels and nothing else, in the add direction only.
        ck(set(_b35) - set(_a35) == {"app:pacchiardi_census",
                                     "tab:pacchiardi_census"},
           f"35g: the labels added since c9718cf are "
           f"{sorted(set(_b35) - set(_a35))}, not EXP-XP's two")
        ck(not (set(_a35) - set(_b35)),
           f"35g: labels were REMOVED since c9718cf: "
           f"{sorted(set(_a35) - set(_b35))[:8]}")''',
    "(m) 35g moved-label record")

# ===================================================== (n) 36a en-dash inventory
sub(r'''              ("related_work.tex", 0,  43,  11),''',
    r'''              # ROUND-37 SUBSTITUTION: 11 -> 12 en dashes. Part A's disposition
              # clause carries the correlation range `0.84$--$0.96`, which is a
              # RANGE, the one thing an en dash is for. The em-dash counts are
              # unchanged, which is the property that matters here.
              ("related_work.tex", 0,  43,  12),''',
    "(n) 36a related_work en dashes")

sub(r'''              ("appendix.tex",    31, 433, 249)]''',
    r'''              # ROUND-37 SUBSTITUTION: 249 -> 256 en dashes. Seven new ranges and
              # enumerations in the round's appendix additions (`§5.4--5.5`,
              # `(i)--(v)` twice, `12--23`, `1--3`, `(i)--(iv)`, `24/10/14`'s
              # neighbouring `(1)--(5)`). The em-dash counts are unchanged on both
              # sides of the conversion, which is what 36a is for.
              ("appendix.tex",    31, 433, 256)]''',
    "(n) 36a appendix en dashes")

# ================================================================ (o) 36e pages
sub(r'''    ck(re.search(r"Pages:\s+89", _pp36) is not None,
       f"36e: the document is not 89 pages: "''',
    r'''    # ROUND-37 SUBSTITUTION: 89 -> 93, the four appendix pages round 37 buys. The
    # ruler assertions below are UNCHANGED, which is the whole costing claim: the
    # main text still ends on p9 at 485 and the Ethics statement still opens p10 at
    # 486, so all four pages are appendix.
    ck(re.search(r"Pages:\s+93", _pp36) is not None,
       f"36e: the document is not 93 pages: "''',
    "(o) 36e pdfinfo page count")

# =================================================================== GROUP 37
GROUP37 = r'''    # ==================================================================== 37
    # ROUND 37: the NeurIPS 2026 workshop TAE review (Quality 3, Clarity 3,
    # Significance 3, Originality 3, Rating 4 Borderline Accept, Confidence 4),
    # mined into the ICLR tree.
    #
    # PROVENANCE, pinned as the group's first fact because it bounds everything
    # else: that review is of an EARLIER WORKSHOP-LENGTH version of the same
    # project. It describes Claims A/B/C and three diagnostics; this tree has
    # Claims 1-5, five criteria, the ECCP and the five-rung ladder. Same research,
    # so its items are measurable against this tree -- but two of its eight were
    # already closed here, and those are pinned as already-closed rather than
    # re-answered (37j).
    #
    #   37a  price       93 pages, main text still closing p9/485, 5 main pins
    #   37b  ledger      the round-37 ledger's integrity and its round-36 clearance
    #   37c  Part A      W1: Pacchiardi's own §5.4-5.5, with the numbers verified
    #   37d  Part B      W6: aliasing vs common causation, named at the definition
    #   37e  Part C      W2: bank width and frozen-weights transfer, disclosed
    #   37f  Part D      W5: claim-clustered intervals, cross-checked against JSON
    #   37g  Part E      W3: EXP-XP, the audit target's own release, pre-registered
    #   37h  Part F      W7: the availability statement, and that it is free
    #   37i  unchanged   what this round was not allowed to touch
    #   37j  closed      W4 and W8, pinned as already-answered
    _APP37 = read("appendix.tex")
    _RW37 = read("related_work.tex")
    _METH37 = read("methodology.tex")
    _MT37 = io.open("main.tex", encoding="utf-8").read()
    _PARENT37 = "ea6faf9"
    # NB: `CODE` is rebound inside main() to analyze_crit4b.py's path, so the
    # package directory gets its own name here.
    _ALD37 = CODEREPO

    def _git37(path):
        _r = subprocess.run(["git", "show", _PARENT37 + ":" + _PDIR35 + path],
                            cwd=_REPO35, capture_output=True, text=True)
        return _r.stdout if _r.returncode == 0 else None

    # ---- 37a. THE PRICE, measured. Four appendix pages and zero main-text
    # rulers. The four-part fit test is the same one every round since 32 has run:
    # p9 must still carry the conclusion's last sentence, p10 must not, the Ethics
    # statement must open p10, and the rulers must read 485 then 486. 36e pins the
    # rulers; this pins the other three and the five main-text float pages.
    _f9_37 = re.sub(r"\s+", " ", subprocess.run(
        ["pdftotext", "-layout", "-f", "9", "-l", "9", "main.pdf", "-"],
        capture_output=True, text=True).stdout)
    _f10_37 = re.sub(r"\s+", " ", subprocess.run(
        ["pdftotext", "-layout", "-f", "10", "-l", "10", "main.pdf", "-"],
        capture_output=True, text=True).stdout)
    ck("magnitude we measure only" in _f9_37,
       "37a: the conclusion's scope clause is no longer on p9 -- the main text "
       "has shrunk or reflowed, and the 9-page budget is measured from it")
    ck("magnitude we measure only" not in _f10_37,
       "37a: the conclusion's scope clause spilled onto p10; the main text must "
       "END on p9")
    ck("THICS STATEMENT" in _f10_37[:300],
       f"37a: the Ethics statement no longer opens p10; p10 starts "
       f"{_f10_37[:60]!r}")
    for _lab37, _num37, _pg37 in [("fig:dag", "1", "2"),
                                  ("tab:claim_ledger", "1", "5"),
                                  ("fig:ladder", "2", "5"),
                                  ("fig:r1c_collapse", "3", "7"),
                                  ("tab:external_audit", "2", "8")]:
        _m37 = re.search(r"newlabel\{" + re.escape(_lab37)
                         + r"\}\{\{([^}]*)\}\{(\d+)\}", aux)
        ck(_m37 is not None, f"37a: main-text float {_lab37} has no newlabel")
        if _m37:
            ck((_m37.group(1), _m37.group(2)) == (_num37, _pg37),
               f"37a: main-text float {_lab37} moved to {_m37.group(1)} on "
               f"p{_m37.group(2)}, from {_num37} on p{_pg37} -- round 37 is "
               f"costed at zero main-text movement")
    # Underfull boxes, pinned as an equality for the first time. Round 36 left 99;
    # round 37's appendix additions bring it to 107. It is a NEW pin rather than an
    # updated one because no earlier round had it, and it is pinned because an
    # Underfull count is the cheapest available detector of a table or list whose
    # column widths stopped fitting.
    _uf37 = log.count("Underfull \\hbox") + log.count("Underfull \\vbox")
    ck(_uf37 == 107,
       f"37a: the build reports {_uf37} Underfull boxes, not the 107 round 37 "
       f"measured (99 at round 36 plus the 8 its appendix additions add)")

    # ---- 37b. THE LEDGER. Ten paragraph blocks, and the round-36 hazard cleared
    # by measurement rather than by argument.
    ck(len(R37_EDITS) == 10,
       f"37b: the round-37 ledger has {len(R37_EDITS)} pairs, not 10")
    _byf37 = {}
    for _n37b, _t37b, _o37b, _x37b in R37_EDITS:
        _byf37[_n37b] = _byf37.get(_n37b, 0) + 1
    ck(_byf37 == {"methodology": 1, "appendix": 7, "related_work": 2},
       f"37b: the round-37 ledger's per-file shape is {_byf37}, not the "
       f"{{methodology: 1, appendix: 7, related_work: 2}} the round is costed at "
       f"-- one word-neutral main-text edit, nine appendix-side ones")
    # THE HAZARD. verify_r36.py un-converts live text to assert pre-conversion
    # literals, so a round-37 pre-image lying INSIDE a round-36 post-image would
    # couple the two ledgers and break 36d's invert-once property. Generating the
    # round-37 ledger from UNCONVERT(parent) vs UNCONVERT(tree) makes that
    # structurally impossible; "structurally impossible" is what a defect says
    # about itself, so it is measured.
    ck(not [_t37b for _n37b, _t37b, _o37b, _x37b in R37_EDITS
            for _r36b, _o36b, _n36b in R36_EDITS if _o37b in _n36b],
       "37b: a round-37 pre-image lies inside a round-36 post-image; re-widen the "
       "round-36 pair with gen_r36_edits.py and never hand-edit either ledger")
    # and the round-trip, which is the ledger's whole warrant: inverting round 36
    # and then round 37 on the live tree must reproduce the parent commit's
    # un-converted text, byte for byte, per file.
    for _f37b in BOLDED + ["appendix", "related_work"]:
        _was37b = _git37("sections/%s.tex" % _f37b)
        ck(_was37b is not None,
           f"37b: cannot read {_PARENT37}:{_f37b}.tex, so the round-37 ledger is "
           f"unverifiable")
        if _was37b is None:
            continue
        ck(UNDO37(UNCONVERT(read(_f37b + ".tex"), _f37b), _f37b)
           == UNCONVERT(_was37b, _f37b),
           f"37b: {_f37b}.tex does not reduce to {_PARENT37} under the round-37 "
           f"and round-36 ledgers -- an unledgered edit entered it")

    # ---- 37c. PART A, the review's W1 and the highest-value item in it: their
    # §5.4-5.5 already report the detector tracking a DISPOSITION to lie, which is
    # convergent prior evidence for this paper's mechanism, arrived at from the
    # other direction. The paper had left it unengaged, which was both a lost
    # corroboration and an open attack surface.
    #
    # CITATION-VERIFICATION RECORD. Every number below was read out of
    # arXiv:2309.15840 (bib key pacchiardi2024catch) before it was written, not
    # transcribed from the review: the correlation range is 0.84 to 0.96, the
    # disposition wording is their §5.5 quoting their Appendix D.5, and the
    # compliance worry is their §5.4. Pinned here so a later round cannot drift
    # them, and so the letter's claim to have checked is checkable.
    ck(_RW37.count("\\textbf{Their own~§5.5 reads that signal as a "
                   "\\emph{disposition} to lie} ($r\\!=\\!0.84$--$0.96$ with "
                   "lying \\emph{next}), and their~§5.4 bounds by argument the "
                   "confound we test by intervention.") == 1,
       "37c: related_work's disposition clause is gone or duplicated; it is W1's "
       "whole answer in the main text")
    for _cl37 in ["(1)~topically related, adaptive follow-ups",
                  "(2)~prompt-equalized and cross-family controls",
                  "(3)~the identifiability analysis their fixed-condition "
                  "evaluation leaves open"]:
        ck(_cl37 in _RW37,
           f"37c: the three-ways-we-differ clause {_cl37[:34]!r} was deleted "
           f"rather than compressed -- Part A pays for itself in place")
    # the price, measured: +21 characters and 0 rulers. The plan targeted <= 20 and
    # the rewrite came in one character over; it is pinned at what it measured
    # rather than at what it aimed for, and 37a shows the ruler cost is zero.
    _rw_was37 = _git37("sections/related_work.tex")
    ck(_rw_was37 is not None, "37c: cannot read the parent's related_work.tex")
    if _rw_was37 is not None:
        ck(len(_RW37) - len(_rw_was37) == 21,
           f"37c: related_work.tex moved by "
           f"{len(_RW37) - len(_rw_was37):+d} characters, not the +21 Part A is "
           f"costed at")
    for _p37c in ["\\paragraph{What their own §5.4--5.5 already says.}",
                  "strongly correlates with the probability that the LLM will "
                  "output a lie in subsequent responses",
                  "($r$ from 0.84 to 0.96; their Appendix~D.5)",
                  "identifying a latent intention or disposition of the model "
                  "to lie.",
                  "\\paragraph{What the disposition reading does not license.}",
                  "it lifts neither their evaluation nor ours above rung~4"]:
        ck(_p37c in _APP37,
           f"37c: the appendix treatment of their §5.4-5.5 lost {_p37c[:44]!r}")
    # the bound travels with the corroboration: convergent evidence does not lift
    # anything to rung 5, and the appendix says so at the same site.
    ck("A disposition correlate is still not $\\tau_D$" in _APP37,
       "37c: the appendix no longer bounds what the disposition reading licenses "
       "-- an unbounded corroboration is exactly what this paper objects to "
       "elsewhere")

    # ---- 37d. PART B, the review's W6: "confound" was used in the
    # design-of-experiments ALIASING sense inside causal-graph language where
    # deception is a MEDIATOR. The gloss names the sense at the definition site.
    # 31e and 35a pin the new literal; what is pinned here is that the SEPARATE
    # common-cause statement -- the residual latent U -- is byte-unchanged, because
    # the whole point of the gloss is that the paper makes both claims and had not
    # distinguished them.
    ck("any latent $U$ with $U\\!\\to\\!D$ and $U\\!\\to\\!S$" in _METH37,
       "37d: methodology lost the residual-latent-U sentence, which is the "
       "common-cause threat the aliasing gloss contrasts itself with")
    ck(_METH37.count("aliasing") == 1,
       f"37d: methodology.tex says 'aliasing' {_METH37.count('aliasing')} times, "
       f"expected once -- the gloss is a single naming at the definition site, "
       f"not a new vocabulary")
    ck("its premises~(A1)--(A5) are in Appendix" in _METH37,
       "37d: the funding edit that paid for the gloss was reverted; Part B is "
       "word-neutral to +20 characters and this is where 41 of the 61 came from")
    # the ECCP is NOT renamed. The review's stronger reading would have retitled
    # it; that is a multi-site rewrite across pinned text for a gain the gloss
    # delivers at ~0 characters, so it was declined and the name is pinned at all
    # three sites the letter cites.
    for _f37d, _t37d, _n37d in [("introduction", intro, 1),
                                ("methodology", _METH37, 1),
                                ("conclusion", concl, 1)]:
        ck(_t37d.count("Elicitation--Construct Confounding Principle") == _n37d,
           f"37d: {_f37d} names the ECCP in full "
           f"{_t37d.count('Elicitation--Construct Confounding Principle')} "
           f"times, not {_n37d}; the review asked for the SENSE to be named and "
           f"renaming the principle was declined, so all three naming sites stay "
           f"as they are")
    ck(_METH37.count("ECCP") == 2,
       f"37d: methodology.tex says 'ECCP' {_METH37.count('ECCP')} times, not 2; "
       f"the abbreviation is introduced at the definition and used once more")
    _meth_was37 = _git37("sections/methodology.tex")
    if _meth_was37 is not None:
        ck(len(_METH37) - len(_meth_was37) == 20,
           f"37d: methodology.tex moved by "
           f"{len(_METH37) - len(_meth_was37):+d} characters, not the +20 Part B "
           f"is costed at")

    # ---- 37e. PART C, the review's W2, the two fidelity gaps that were genuinely
    # open. Both are DISCLOSURES that cut against the paper, which is why they
    # belong in it: it is this paper that insists instructed accuracy is
    # uninterpretable, so being exact about what its reimplementation does and
    # does not reproduce is on-message rather than a concession.
    ck("their published battery is \\textbf{48} probes (24 lie-related, 10 "
       "factual, 14 ambiguous), ours is \\textbf{16} (5, 6, 5)" in _APP37,
       "37e: the bank-width disclosure is gone; without their count against our "
       "16 the reader cannot see the ratio, which was W2's actual complaint")
    ck("It cannot show that the original detector at full width would collapse "
       "by the same margin" in _APP37,
       "37e: the bank-width disclosure no longer says what a narrower bank "
       "cannot establish, which is the half of it that cuts against us")
    ck("\\paragraph{What this reimplementation does not test: frozen-weights "
       "transfer.}" in _APP37,
       "37e: the frozen-weights gap is unnamed again -- every EXP-R1/R1b/R1c cell "
       "is a per-target refit and prior work's headline property was one "
       "classifier frozen across targets")
    ck("\\textbf{No cell of EXP-R1/R1b/R1c tests that property}" in _APP37,
       "37e: the frozen-weights paragraph no longer states the gap plainly")
    # and the gap is BOUNDED by arms the paper did run, so the disclosure is not
    # open-ended: the frontier transfer cells and the pre-registered
    # leave-one-target-out battery transfer.
    for _b37e in ["it scores 50.5\\% and 45.0\\% while the parameter-free rule "
                  "reaches 84.8\\% and 83.0\\%",
                  "2 of 5 targets transferring, 2 uninformative by construction "
                  "and 1 genuine null"]:
        ck(_b37e in _APP37,
           f"37e: the frozen-weights disclosure lost its bound {_b37e[:40]!r}; "
           f"an unbounded 'we did not test this' overstates the gap")
    # the PRE-EXISTING disclosures are ADDITIONS' neighbours, not their casualties.
    for _pre37e in ["we did not obtain Pacchiardi et al.'s original code or data",
                    "this tests the published mechanism rather than reproducing "
                    "the exact original detector",
                    "per-model ambiguous rates range 0--23\\%"]:
        ck(_pre37e in _APP37,
           f"37e: a pre-existing W2 disclosure was replaced rather than extended: "
           f"{_pre37e[:46]!r}")
    ck("mechanism-faithful reimplementation" in expt,
       "37e: §3's 'mechanism-faithful reimplementation' phrase is gone; Part C "
       "scopes it in the appendix and deliberately leaves the pinned phrase")

    # ---- 37f. PART D, the review's W5: intervals, and the honest denominator.
    # The unit of evidence in EXP-C4B's H1 is the PAIRED CLAIM (12-23 per target),
    # not the trial (231-400), so a cluster bootstrap over claims is the estimator
    # the table was always implicitly about. The intervals are WIDE. That is the
    # point: reporting them makes the standing 1-of-5 more credible, not less.
    ck("\\paragraph{Claim-clustered intervals on H1 (descriptive, post-hoc).}"
       in _APP37,
       "37f: the claim-clustered interval paragraph is gone")
    ck("2{,}000 draws, seed~42" in _APP37,
       "37f: the bootstrap's draw count and seed are no longer stated, so the "
       "intervals are not reproducible from the text")
    ck("the unit is the paired claim, 12--23 of them per target, not the "
       "231--400 trials" in _APP37,
       "37f: the effective-n statement is gone, and it is the whole of W5's "
       "argument -- an interval without its denominator is decoration")
    # every interval quoted in the appendix must equal the one in the committed
    # result file, to three decimals, in table order. This is the check that makes
    # the paragraph a report of a computation rather than a claim about one.
    _CI37 = json.load(io.open(_ALD37 + "/data/results/crit4b_ci.json",
                              encoding="utf-8"))
    ck(_CI37.get("n_boot") == 2000 and _CI37.get("seed") == 42,
       f"37f: crit4b_ci.json was computed with n_boot={_CI37.get('n_boot')} "
       f"seed={_CI37.get('seed')}, not the 2,000 draws at seed 42 the appendix "
       f"states")
    ck(_CI37.get("all_cells_reproduce_published_accuracy") is True,
       "37f: crit4b_ci.json no longer reports that every cell reproduces its "
       "published accuracy -- if a published number moved, that is a DEFECT and "
       "the interval arm must not be reported at all")
    for _iv37 in ["$[0.827,0.936]$", "$[0.794,0.918]$", "$[0.525,0.795]$",
                  "$[0.793,0.924]$", "$[0.692,0.843]$",
                  "$[+0.172,+0.400]$", "$[+0.181,+0.382]$",
                  "$[-0.078,+0.105]$", "$[-0.011,+0.095]$",
                  "$[-0.031,+0.089]$",
                  "$[+0.092,+0.329]$", "accuracy $[0.468,0.800]$"]:
        ck(_iv37 in _APP37,
           f"37f: the interval {_iv37} left the appendix; all twelve quoted "
           f"bounds come from crit4b_ci.json")
    ck("the margin excludes zero on exactly the three cells committed as "
       "positive and on no other cell" in _APP37,
       "37f: the paragraph no longer states the one thing that makes the "
       "descriptive arm informative -- that it agrees with the pre-registered "
       "test rather than substituting for it")
    ck("descriptive and it is not a second test" in _APP37,
       "37f: the descriptive/confirmatory boundary is gone from the interval "
       "paragraph; the pre-registered inference is the permutation test")
    # THE POINT OF PART D: not one pre-existing cell of tab:crit4b_h1 moved. The
    # interval arm is an addition to an already-reported estimate, so if a verdict,
    # a count, an accuracy, a p-value or an MDE had changed, that would be a defect
    # and not a result. Asserted as byte-identity of the whole float against the
    # parent commit, which is stronger than pinning cells one at a time.
    def _float37(_s, _lab):
        _i = _s.index("\\label{%s}" % _lab)
        return _s[_s.rindex("\\begin{table}", 0, _i):
                  _s.index("\\end{table}", _i) + len("\\end{table}")]

    _app_was37 = _git37("sections/appendix.tex")
    ck(_app_was37 is not None, "37f: cannot read the parent's appendix.tex")
    if _app_was37 is not None:
        for _t37f in ["tab:crit4b_h1", "tab:crit4b_h1_e"]:
            ck(_float37(_APP37, _t37f) == _float37(_app_was37, _t37f),
               f"37f: {_t37f} is not byte-identical to {_PARENT37}; Part D adds "
               f"intervals to an already-reported estimate and may not move a "
               f"single published cell")
    # the post-hoc addition is logged where the discipline requires: PREREG_EXP_C4B
    # §12 is append-only, and the file must differ from the pinned commit by
    # exactly one contiguous insertion beginning with the new entry's own marker.
    # The pinned commit is abc7d04, not d3bb92d as first written. Both name the
    # SAME commit -- "PREREG_EXP_FS §10: log the §7 branch adjudication" -- and the
    # same tree. On 2026-09-22 the code repo's history was rewritten with
    # `git filter-repo --strip-blobs-bigger-than 50M` to drop four blobs that
    # exceeded GitHub's 100 MB per-file limit and made the repo unpushable, which
    # renumbered every commit SHA while leaving every surviving blob SHA untouched.
    # So this is a renamed pin, not a weakened one: the bytes it asserts against are
    # bit-for-bit the ones d3bb92d carried.
    _C4B37 = io.open(_ALD37 + "/docs/PREREG_EXP_C4B.md", encoding="utf-8").read()
    _c4b_was37 = subprocess.run(
        ["git", "show", "abc7d04:adaptive_lie_detector/docs/PREREG_EXP_C4B.md"],
        cwd=_ALD37, capture_output=True, text=True)
    ck(_c4b_was37.returncode == 0,
       "37f: cannot read abc7d04:PREREG_EXP_C4B.md, so the append-only claim is "
       "unverifiable")
    if _c4b_was37.returncode == 0:
        _w37 = _c4b_was37.stdout
        _ins37 = _C4B37[49943:49943 + 2300]
        ck(_C4B37 == _w37[:49943] + _ins37 + _w37[49943:],
           "37f: PREREG_EXP_C4B.md differs from abc7d04 by more than one "
           "contiguous 2,300-character insertion -- the file is frozen except "
           "for its append-only log")
        ck(_ins37.startswith("**(17) A post-hoc DESCRIPTIVE arm: "
                             "claim-clustered bootstrap intervals on H1.**"),
           f"37f: the PREREG_EXP_C4B insertion does not begin with the interval "
           f"arm's own entry marker: {_ins37[:60]!r}")
        ck("## 12A. CORRECTION 1" in _C4B37 and _ins37 in _C4B37.split(
            "## 12A. CORRECTION 1")[0],
           "37f: the new entry is not inside §12, the append-only adjudication "
           "log -- §§0-11 are frozen")
        ck("no verdict" in _ins37 and "no $p$" in _ins37 or "descriptive"
           in _ins37,
           "37f: the log entry does not state that the arm is descriptive and "
           "moves no verdict, count or p-value")

    # ---- 37g. PART E, the review's W3 and the only genuine experiment in the
    # round: the criterion-4 census had never been run over the AUDIT TARGET'S OWN
    # release. It now is, pre-registered, and the verdict is that no design in it
    # supplies all five -- so claim 4 survives a test it had not faced.
    _XP37 = os.path.join(_ALD37, "docs", "PREREG_EXP_XP.md")
    ck(os.path.exists(_XP37),
       "37g: docs/PREREG_EXP_XP.md is missing; EXP-XP's numbers are not reportable "
       "without it")
    _xp37 = io.open(_XP37, encoding="utf-8").read() if os.path.exists(_XP37) else ""
    for _s37g in ["## 0. Integrity disclosure", "## 5. Verdict rule",
                  "## 6. Reporting branches", "## 9. Deviations",
                  "## 10. Outcome"]:
        ck(_s37g in _xp37,
           f"37g: PREREG_EXP_XP.md has no {_s37g!r}; it follows the sixteen "
           f"existing files' structure and §10 carries the outcome")
    ck("DEVIATION 1" in _xp37 and "exploratory" in _xp37,
       "37g: PREREG_EXP_XP.md no longer records that the arm is exploratory by "
       "construction -- a feasibility gate preceded it and that travels with "
       "every number")
    ck("c5689fa2615368cd7c3f3c15dbb60ea2126006c7" in _xp37,
       "37g: the pre-registration no longer pins the upstream commit, so the "
       "materials are not identified")
    # the other sixteen are BYTE-IDENTICAL to the pinned commit. A new file is not
    # an edit to a frozen one, and this is what makes that statement checkable.
    _frozen37 = []
    for _f37g in sorted(os.listdir(os.path.join(_ALD37, "docs"))):
        if not (_f37g.startswith("PREREG_EXP_") and _f37g.endswith(".md")):
            continue
        if _f37g in ("PREREG_EXP_XP.md", "PREREG_EXP_C4B.md"):
            continue
        _r37g = subprocess.run(
            ["git", "show", "abc7d04:adaptive_lie_detector/docs/" + _f37g],
            cwd=_ALD37, capture_output=True, text=True)
        if _r37g.returncode != 0 or _r37g.stdout != io.open(
                os.path.join(_ALD37, "docs", _f37g), encoding="utf-8").read():
            _frozen37.append(_f37g)
    ck(not _frozen37,
       f"37g: these pre-registrations are not byte-identical to abc7d04: "
       f"{_frozen37} -- all sixteen but C4B's append-only log are frozen")
    # THE CENSUS ITSELF, cross-checked between the committed JSON and the prose.
    _CEN37 = json.load(io.open(_ALD37 + "/data/results/pacchiardi_census.json",
                               encoding="utf-8"))
    ck(_CEN37.get("claim4_survives") is True,
       "37g: pacchiardi_census.json no longer reports claim 4 surviving -- if a "
       "design DID supply all five, branch 1 fires and the abstract, claim "
       "ledger, tab:prior_work_criteria and §external_audit all have to narrow")
    ck(_CEN37.get("verdicts_differ") is False
       and _CEN37.get("split_prior_work_row") is False,
       "37g: the census now reports differing per-design verdicts, which fires "
       "branch 2's split of tab:prior_work_criteria's pacchiardi2024catch row")
    ck(_CEN37.get("reporting_branch") == "2+3",
       f"37g: the census selected branch {_CEN37.get('reporting_branch')!r}, not "
       f"the '2+3' the appendix reports")
    ck(_CEN37.get("strongest_near_miss", {}).get("design") == "finetuned_liar"
       and sorted(_CEN37.get("strongest_near_miss", {}).get("failed", []))
       == ["ii", "v"],
       f"37g: the strongest near-miss is no longer the fine-tuned design failing "
       f"(ii) and (v): {_CEN37.get('strongest_near_miss')}")
    # the prose numbers, each traceable to the census file
    for _n37g in ["200 populated cells over 11 datasets and 26 instruction texts",
                  "138 rollouts over three files (42, 54 and 42)",
                  "138 distinct prompts and \\textbf{0 items carrying both "
                  "outcomes}",
                  "\\textbf{1{,}109 prompts occur in both conditions "
                  "byte-for-byte}",
                  "the group widths are \\textbf{24, 14 and 10, so 48}"]:
        ck(_n37g in _APP37,
           f"37g: EXP-XP's appendix subsection lost the measured quantity "
           f"{_n37g[:46]!r}")
    # the SUPERLATIVE the pre-registration licensed only conditionally, and that
    # the numbers did not support, must stay withheld. This is the check that
    # stops branch 3 being written up as a discovery.
    ck("Branch~3 of the pre-registration licensed calling the near-miss "
       "\\emph{closer to criterion~4 than any Apollo set} only if the numbers "
       "said so. They do not." in _APP37,
       "37g: the superlative branch 3 conditioned on is no longer quoted and "
       "declined in the same breath -- the words may appear ONLY inside that "
       "frame, because the numbers do not support them")
    ck(_APP37.count("closer to criterion~4 than any Apollo set") == 1,
       f"37g: the cross-release superlative occurs "
       f"{_APP37.count('closer to criterion~4 than any Apollo set')} times, not "
       f"once; a second occurrence outside the declining sentence is the claim "
       f"being made after all")
    ck("so the reported statement is the weaker true one: strongest near-miss "
       "\\emph{within the audit target's own release}" in _APP37,
       "37g: the weaker true statement that replaces the superlative is gone; "
       "the Apollo insider-trading corpus clears (i)-(iv) and the fine-tuned "
       "design clears three of five")
    ck("\\textsc{undecidable}" in _APP37,
       "37g: UNDECIDABLE_FROM_RELEASE is no longer a first-class verdict in the "
       "census table; rounding it to a cross is what §4 of the pre-registration "
       "forbids")
    # materials pinned by manifest, and nothing redistributed.
    _MAN37 = json.load(io.open(
        _ALD37 + "/data/external/pacchiardi_release_manifest.json",
        encoding="utf-8"))
    ck(_MAN37.get("commit") == "c5689fa2615368cd7c3f3c15dbb60ea2126006c7",
       f"37g: the manifest pins commit {_MAN37.get('commit')!r}, not the one the "
       f"pre-registration names")
    ck(len(_MAN37.get("files", [])) == 6
       and all(len(_e37.get("sha256", "")) == 64
               for _e37 in _MAN37.get("files", [])),
       f"37g: the manifest does not carry six files each with a sha256; the "
       f"corpus is git-ignored and the manifest is the only thing that makes the "
       f"census reproducible")
    ck("EXP-XP & 3 & 3 designs" in _APP37,
       "37g: EXP-XP has no row in tab:experiment_summary, so the experiment "
       "inventory no longer matches the appendix")
    ck("(\\ref{app:pacchiardi_census})" in _APP37
       or "\\ref{app:pacchiardi_census}" in _APP37,
       "37g: nothing cross-references EXP-XP's subsection")

    # ---- 37h. PART F, the review's W7: the paper forward-references "the code"
    # at eight or more sites and named no release. One sentence, in the
    # Reproducibility statement, with NO URL -- the anonymized repository does not
    # exist yet and inventing one would be worse than the gap.
    ck("\\textbf{What the release contains.}" in _MT37,
       "37h: the availability sentence is gone from main.tex; W7's complaint was "
       "that the appendix's eight forward references to 'the code' resolve to "
       "nothing")
    ck(_MT37.index("\\subsection*{Reproducibility statement}")
       < _MT37.index("\\textbf{What the release contains.}")
       < _MT37.index("\\textbf{Build identity.}"),
       "37h: the availability sentence is not inside the Reproducibility "
       "statement, which is the one place a reviewer looks for it")
    for _i37h in ["\\textbf{17 pre-registrations}",
                  "\\textbf{2{,}765-check verification harness}",
                  "citation-verification script",
                  "committed result files"]:
        ck(_i37h in _MT37,
           f"37h: the availability sentence no longer names {_i37h!r}; the point "
           f"is to say WHAT is released, since it cannot yet say where")
    # THE SELF-REFERENCE, pinned as a constant like every other fact here: the
    # number the sentence advertises is THIS verifier's own final total, and this
    # check is the 2,765th. Any round that adds or retires a check has to move
    # both the constant and the printed sentence, which is the point -- an
    # advertised count that has drifted from the harness is a false claim in the
    # paper, and the harness is the only thing that can catch it.
    ck("2{,}765-check" in _MT37,
       "37h: the advertised check count is not 2,765; re-pin it here and in "
       "main.tex together, and re-read the final line of verification/run.py's "
       "output for the true number")
    # anonymity: no URL, and no author-identifying content anywhere in the
    # sentence. The submission is double-blind.
    _avail37 = _MT37[_MT37.index("\\textbf{What the release contains.}"):
                     _MT37.index("\\textbf{Build identity.}")]
    for _bad37 in ["http", "github", "anonymous.4open", "Mediratta", "Anupam"]:
        ck(_bad37 not in _avail37,
           f"37h: the availability sentence carries {_bad37!r}; the user's "
           f"decision for this round was a statement with no URL, and the "
           f"submission is double-blind")
    # and it is FREE, asserted from the render: nothing of it appears in p1-p9.
    for _pg37h in range(1, 10):
        ck("What the release contains" not in " ".join(subprocess.run(
            ["pdftotext", "-f", str(_pg37h), "-l", str(_pg37h), "main.pdf", "-"],
            capture_output=True, text=True).stdout.split()),
           f"37h: the availability sentence rendered on p{_pg37h}, inside the "
           f"9-page main text -- it was costed as free because it lands after it")

    # ---- 37i. WHAT THIS ROUND WAS NOT ALLOWED TO TOUCH. Five standing
    # constraints, each from an earlier round's user decision, asserted here
    # because a round that adds 17.4k characters is exactly when they get eroded.
    for _f37i in ["abstract", "introduction", "experiments", "discussion",
                  "conclusion"]:
        _w37i = _git37("sections/%s.tex" % _f37i)
        ck(_w37i is not None, f"37i: cannot read the parent's {_f37i}.tex")
        if _w37i is not None:
            ck(read(_f37i + ".tex") == _w37i,
               f"37i: {_f37i}.tex is not byte-identical to {_PARENT37}; round 37 "
               f"edits methodology.tex, related_work.tex, appendix.tex and "
               f"main.tex only, and discussion.tex plus the abstract are "
               f"standing no-fund sites")
    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "37i: the three structured caution boxes must survive; every reviewer who "
       "has commented on them named them a strength")
    # the 42 genuine em-dash survivors and the abstract's ratchet are pinned by
    # 36b and 29z respectively; what 37i adds is that the round's OWN new prose
    # obeys the punctuation discipline the em-dash round established. Measured on
    # the live text of the two new appendix regions, where the round's prose is.
    _xpreg37 = _APP37[_APP37.index("\\subsection{EXP-XP:"):]
    _xpreg37 = _xpreg37[:_xpreg37.index("\\subsection{", 12)]
    ck("---" not in _xpreg37,
       "37i: EXP-XP's subsection carries an em dash; round 36 removed every prose "
       "dash from the paper and new prose may not reintroduce one")
    _sent37 = re.split(r"(?<=[.!?])\s+", _xpreg37)
    ck(not [_s37i for _s37i in _sent37 if _s37i.count(": ") > 1],
       f"37i: a sentence in EXP-XP's subsection carries two grammatical colons: "
       f"{[_s[:70] for _s in _sent37 if _s.count(': ') > 1][:2]}")
    ck(not [_s37i for _s37i in _xpreg37.split(";")[1:]
            if not re.match(r"\s+\w", _s37i)],
       "37i: a semicolon in EXP-XP's subsection has no clause after it")

    # ---- 37j. THE TWO ITEMS THAT WERE ALREADY CLOSED, pinned rather than
    # re-answered, because the response letter quotes both back and if either
    # regresses the letter becomes false.
    #   W4: "the factorial is V x E, not C x E, and the T/D cell is not
    #        human-verified deception"
    #   W8: "the recommendation is broader than the evidence"
    ck("Crossing truth-value with the instruction" in expt,
       "37j: §3's factorial is no longer described as crossing truth-value with "
       "the instruction, which is W4's correction and was already in the tree")
    ck("does \\textbf{not} establish that latent $D$ is fixed: $D$ is never "
       "observed" in _APP37,
       "37j: the T/D-vs-F/D contrast no longer disclaims fixing latent D, which "
       "is the stronger form of W4 the paper already carried")
    ck("no magnitude of the confound is measured outside deception" in _APP37,
       "37j: EXP-AF's branch-(b) disclosure is gone, and it is W8's whole answer")
    ck("no sentence in this paper may round it up" in _APP37,
       "37j: the appendix no longer forbids rounding the decidability result up "
       "to a magnitude result")

'''

sub(r'''    # ---- report -----------------------------------------------------------
    if fails:''',
    GROUP37 + r'''    # ---- report -----------------------------------------------------------
    if fails:''',
    "GROUP 37")

# ============================================================== apply, in order
for old, new, label in subs:
    n = out.count(old)
    if n != 1:
        sys.exit("anchor %r matched %d times (need exactly 1):\n%r"
                 % (label, n, old[:140]))
    out = out.replace(old, new)
print("substitutions applied: %d" % len(subs))
for _o, _n, _l in subs:
    print("  %-42s %+6d chars" % (_l, len(_n) - len(_o)))

io.open(OUT, "w", encoding="utf-8").write(out)
print("\nwrote %s (%d lines, was %d)"
      % (OUT, out.count("\n") + 1, src.count("\n") + 1))
