#!/usr/bin/env python3
"""Build /tmp/verify_r38.py from /tmp/verify_r37.py.

Round 38 closes the two items of the NeurIPS 2026 workshop TAE review that round
37 left genuinely open:

  Part A  intervals on the equalization panel (tab:r1_faithful, tab:r1c_v2) --
          Wilson on the out-of-fold correct counts plus a claim-pair-clustered
          bootstrap, descriptive and post-hoc, computed by
          experiments/analyze_r1_intervals.py. Four new appendix paragraphs.
  Part B  the T/D deception grade -- a blind, four-cell, 144-item hand-coding
          sheet (experiments/make_factorial_coding_sheet.py), released UNCODED
          because §11-step-7 hand-coding is the user's job, plus a disclosure
          paragraph stating that no grade of D exists in either instructed cell.

Under the standing rule ALL 2,766 checks the round-37 harness scores against
this tree are RETAINED. The ones this
round deliberately changes are UPDATED, each with the round-38 reason in a
comment, never deleted. Every substitution's `old` must occur EXACTLY ONCE in the
source or nothing is written -- that assertion is what enforces the read-back
rule, and it is why a paraphrased anchor fails loudly instead of landing in the
wrong place.

WHY 2766 AND NOT 2765. verify_r37.py's advertised total was 2,765 and check 37h
pinned that literal as the harness's own fixed point. Round 38's appendix names
`ministral-3:8b` in the roster-pinning sentence, and check 11's NEW_TAGS loop
raises one check per appendix sentence mentioning a post-panel model, asserting
the sentence does not claim the model was run. So the parent harness scores 2766
against the round-38 tree before a single new check is added: the count moved
because the paper grew a sentence the harness already knew how to interrogate,
which is the mechanism working. Both the literal and the pin move together to the
new measured total, as 37h's comment requires.

THE STRUCTURAL ADDITION is UNDO38, the exact analogue of UNDO37. The round-38
ledger is generated by gen_r38_edits.py as a diff of UNCONVERT(8f18687) against
UNCONVERT(tree), so it lives in PRE-round-36 punctuation, and therefore:

  * a forward R38 stage appends to 13g's replay after the R37 stage, because
    `rebuilt` is in pre-round-36 punctuation at that point; and
  * every historical pin that reads the live tree becomes
    UNDO37(UNDO38(UNCONVERT(text, name), name), name), which by construction
    restores UNCONVERT(ea6faf9) byte-for-byte -- so rounds 30-35's pins pass for
    the same reason they passed at the parent commit, not because they were
    weakened. The inner-to-outer order matters and is the inverse of the forward
    replay: strip round 38 first, then round 37.
"""
import io
import json
import sys

D = ("/Users/mediratta/code/paper_writing/AI-Researcher-align/output/"
     "adaptive_lie_detector_paper")
SRC = "/tmp/verify_r37.py"
OUT = "/tmp/verify_r38.py"

src = io.open(SRC, encoding="utf-8").read()
out = src

subs = []


def sub(old, new, label):
    subs.append((old, new, label))


# =========================================================== (a) UNDO38 itself
sub(r'''    for _o, _n in reversed(R37_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text
''',
    r'''    for _o, _n in reversed(R37_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text


# ROUND-38: the round that closes the TAE review's last two open items, plus the
# clibib bibliography re-audit of 24 Sep 2026. Six paragraph-level edits in three
# files: four in appendix.tex (Part A's two interval paragraphs, the estimator and
# row-order disclosures on the equalization panel, and Part B's T/D coding-sheet
# paragraph), one in introduction.tex and one in related_work.tex (the re-audit's
# two citation-key renames, burns2022discovering -> burns2023discovering and
# goodfellow2014explaining -> goodfellow2015explaining, both promoted from @article
# to @inproceedings with their ICLR booktitle; a key lives wherever it is cited, so
# the rename reaches every file that cites it). Both renames are CHARACTER-NEUTRAL
# -- 2022/2023 and 2014/2015 are the same width -- so no main-text ruler moves and
# the 9-page budget is untouched. The ledger is generated by gen_r38_edits.py as a
# diff of UNCONVERT(8f18687) against UNCONVERT(tree), so it is expressed in
# PRE-round-36 punctuation -- which is what lets 13g replay it forward after the
# R37 stage, and what makes an `old` overlapping a round-36 or round-37 post-image
# structurally impossible (asserted in 38a anyway).
R38_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r38_edits.json",
                                                 encoding="utf-8"))]
R38_BY_FILE = {}
for _n38, _t38, _o38, _x38 in R38_EDITS:
    R38_BY_FILE.setdefault(_n38, []).append((_o38, _x38))


def UNDO38(text, name):
    """Invert round 38 on already-un-converted text: UNDO38(UNCONVERT(live)).

    Composed as UNDO37(UNDO38(UNCONVERT(live))) at every historical call site,
    which is the exact inverse of the forward replay order and restores
    UNCONVERT(ea6faf9). Keyed by FILE NAME, so it inverts whatever the ledger names
    and is a no-op on every file the round did not touch -- which is why widening
    the round from appendix-only to appendix + introduction + related_work (the
    clibib re-audit's citation-key renames) is a change to the CALL SITES, never to
    this function. gen_r38_edits.py refuses to write a ledger naming any other file,
    so the set of wrapped call sites is checkable against the ledger, and 38a
    measures it.
    """
    for _o, _n in reversed(R38_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text''',
    "(a) R38_EDITS + UNDO38")

# ====================================================== (b) the page count, x2
# ROUND-38 SUBSTITUTION: 93 -> 94. Part A's four paragraphs and Part B's one add
# ~7.1k characters of APPENDIX text, which buys exactly one page. The 9-page main
# text is unchanged, which 37a and 36e's own ruler assertions still prove from the
# margin rulers -- and those assertions are untouched below, which is the costing
# claim: the one new page is appendix.
sub(r'''    ck("Output written on main.pdf (93 pages" in log,
       "page count is not 93 (89 + the four appendix pages round 37's "
       "EXP-XP census and Parts A/C/D disclosures cost)")''',
    r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, the one appendix page Part A's four
    # interval paragraphs and Part B's coding-sheet paragraph cost (~7.1k chars).
    # Still an EQUALITY in both directions: 95+ means an unbudgeted add, 93 or
    # fewer means a later round deleted material this one deliberately landed.
    ck("Output written on main.pdf (94 pages" in log,
       "page count is not 94 (89 + round 37's four appendix pages + round 38's "
       "one for the equalization-panel intervals and the T/D disclosure)")''',
    "(b) check 1 page count 93->94")

sub(r'''    ck(re.search(r"Pages:\s+93", _pp36) is not None,
       f"36e: the document is not 93 pages: "''',
    r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, Part A's and Part B's one appendix page.
    # The two ruler assertions below are again UNCHANGED, which is the costing
    # claim restated: p9 still closes at 485 and the Ethics statement still opens
    # p10 at 486, so the new page is appendix.
    ck(re.search(r"Pages:\s+94", _pp36) is not None,
       f"36e: the document is not 94 pages: "''',
    "(b) check 36e page count 93->94")

# ============================================ (c) the code repo's round-38 files
sub(r'''    R37_TRACKED = {".gitignore",
                   "adaptive_lie_detector/docs/PREREG_EXP_C4B.md"}''',
    r'''    R37_TRACKED = {".gitignore",
                   "adaptive_lie_detector/docs/PREREG_EXP_C4B.md"}
    # ROUND-38 ADDITION, same discipline as round 37's allow-set: this round's
    # code-repo deliverables are enumerated, so a stray untracked file still
    # fails. Part A's analysis arm and its committed output; Part B's sheet
    # generator and the data/human_coding/ directory it writes (git reports an
    # untracked directory with a trailing slash). Commit happens only on request,
    # so the tree is dirty by design between the work and the commit, and this
    # set passes unchanged once the round is committed.
    R38_UNTRACKED = {
        "adaptive_lie_detector/experiments/analyze_r1_intervals.py",
        "adaptive_lie_detector/experiments/make_factorial_coding_sheet.py",
        "adaptive_lie_detector/data/results/r1_intervals.json",
        "adaptive_lie_detector/data/human_coding/",
    }''',
    "(c) R38_UNTRACKED")

sub(r'''        if _st37 == "??" and _pt37 in R37_UNTRACKED:''',
    r'''        if _st37 == "??" and _pt37 in R37_UNTRACKED | R38_UNTRACKED:''',
    "(c) allow-set at check 9")

sub(r'''        return ((_s == "??" and _p in R37_UNTRACKED)
                or (_s == "M" and _p in R37_TRACKED))''',
    r'''        return ((_s == "??" and _p in R37_UNTRACKED | R38_UNTRACKED)
                or (_s == "M" and _p in R37_TRACKED))''',
    "(c) allow-set at check 28o")

# ================================================= (d) 28p's two appendix floats
sub(r'''                           ("tab:dimension_transfer", "52", "70"),
                           ("tab:covariate_audit", "53", "72")]:''',
    r'''                           # ROUND-38 SUBSTITUTION: round 38 adds ~7.1k
                           # characters of appendix prose upstream of both, so
                           # each moves one page LATER and neither changes its
                           # float number (round 38 adds no float at all).
                           # Updated rather than relaxed -- a further shift, or
                           # any change of float number, still fires.
                           ("tab:dimension_transfer", "52", "71"),
                           ("tab:covariate_audit", "53", "73")]:''',
    "(d) 28p float pages +1")

# ================================================= (e) 34a's live character band
sub(r'''    ck(len(app34) < 400_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441 and round 37 added 17,390 for EXP-XP and "
       f"Parts A/C/D -- a value this high means more than that landed")
    ck(len(app34) > 390_000,
       f"34a: appendix.tex is {len(app34)} chars, below round 34's 379,441 plus "
       f"round 37's 17,390 -- something was deleted that one of the two rounds "
       f"deliberately kept; see 34g and 37e")''',
    r'''    # ROUND-38 SUBSTITUTION: the LIVE band moves again, by round 38's measured
    # +7,149 characters (Part A's four paragraphs, Part B's one). Round 34's claim
    # is still not weakened by re-banding the live number: it is RESTORED at full
    # strength immediately below, where un-doing rounds 38 and 37 and un-converting
    # round 36 must land back inside round 34's original 372,000-382,000 window --
    # and THAT pair of checks is untouched by this round.
    ck(len(app34) < 408_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441, round 37 added 17,390 for EXP-XP and Parts "
       f"A/C/D and round 38 added 7,149 for the equalization-panel intervals and "
       f"the T/D disclosure -- a value this high means more than that landed")
    ck(len(app34) > 398_000,
       f"34a: appendix.tex is {len(app34)} chars, below round 34's 379,441 plus "
       f"round 37's 17,390 plus round 38's 7,149 -- something was deleted that "
       f"one of the three rounds deliberately kept; see 34g, 37e and 38b")''',
    "(e) 34a live band")

# ========================================== (f) UNDO38 at the historical pin sites
for _lbl, _old in [
    ("(f) 13g round-30 pin",
     '    appx_led = UNDO37(UNCONVERT(read("appendix.tex"), "appendix"), "appendix")'),
]:
    sub(_old,
        '    appx_led = UNDO37(UNDO38(UNCONVERT(read("appendix.tex"), "appendix"),\n'
        '                             "appendix"), "appendix")',
        _lbl)

# r32_side and r34_side are appendix-only bags, so wrapping the one entry is the
# whole job. r31_side and r35_side ALSO carry a related_work entry, and round 38 now
# edits related_work.tex (the clibib re-audit's goodfellow key rename lands in the
# white-box/black-box paragraph, which is exactly where round 35's citation-key pins
# live), so those two are rewritten whole, below, rather than through this loop --
# an appendix-only wrap would leave UNDO37 reading a related_work.tex that still
# carries the round-38 rename, and round 35's pin on the OLD key would fail.
for _tag, _var in [("(f) 13g round-32 bag", "r32_side"),
                   ("(f) 13g round-34 bag", "r34_side")]:
    sub('    %s = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),\n'
        '                                   "appendix")}' % _var,
        '    %s = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),\n'
        '                                            "appendix"), "appendix"),\n'
        '                                   "appendix")}' % _var,
        _tag)

# ROUND-38 SUBSTITUTION, the one the clibib re-audit forced: both two-entry side
# bags gain UNDO38 on BOTH files. The two blocks are byte-identical in verify_r37.py,
# so each is anchored by its own variable name and replaced whole -- a partial
# anchor would match twice and the generator's count==1 assertion would refuse to
# write, which is that assertion doing its job rather than an obstacle.
_WHY31 = ("    # related_work.tex is wrapped because round 38 edits it, and round\n"
          "    # 31's pins on that file sit in the very paragraph the rename\n"
          "    # touches.\n")
_WHY35 = ("    # related_work.tex is wrapped because round 38 edits it, and round\n"
          "    # 35's pins on that file ARE citation keys -- a later key rename is\n"
          "    # precisely the drift they exist to catch, so reading the live file\n"
          "    # without stripping round 38 would fail them for the right reason at\n"
          "    # the wrong time.\n")
for _tag, _var, _why in [("(f) 13g round-31 bag", "r31_side", _WHY31),
                         ("(f) 13g round-35 bag", "r35_side", _WHY35)]:
    sub('    %s = {"appendix": UNDO37(UNCONVERT(read("appendix.tex"), "appendix"),\n'
        '                                   "appendix"),\n'
        '                "related_work": UNDO37(UNCONVERT(read("related_work.tex"),\n'
        '                                                 "related_work"),\n'
        '                                       "related_work")}' % _var,
        '    # ROUND-38: un-do round 38 on BOTH files before round 37 (see UNDO38).\n'
        + _why +
        '    %s = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),\n'
        '                                            "appendix"), "appendix"),\n'
        '                                   "appendix"),\n'
        '                "related_work": UNDO37(UNDO38(\n'
        '                    UNCONVERT(read("related_work.tex"), "related_work"),\n'
        '                    "related_work"), "related_work")}' % _var,
        _tag)

sub(r'''    _app34_r34 = UNDO37(UNCONVERT(app34, "appendix"), "appendix")''',
    r'''    # ROUND-38: strip round 38 before round 37 (see UNDO38) -- the composition is
    # the inverse of the forward replay, and it is what keeps round 34's original
    # 372,000-382,000 assertion below byte-exact rather than re-banded.
    _app34_r34 = UNDO37(UNDO38(UNCONVERT(app34, "appendix"), "appendix"),
                        "appendix")''',
    "(f) 34a inverted appendix")

# =========================================== (g) 35f's two byte-identity asserts
sub(r'''        ck(UNDO37(UNCONVERT(read(_f35 + ".tex"), _f35), _f35)
           == _rename35(_was35),''',
    r'''        # ROUND-38: un-do round 38 first (see UNDO38). UNDO38 is keyed by file
        # name, so this loop strips the round from whichever of its three files
        # (appendix, introduction, related_work) it is looking at and is a no-op on
        # the rest, and UNDO37(UNDO38(UNCONVERT(.))) is by construction
        # UNCONVERT(ea6faf9) -- so round 35's claim stays byte-exact even though
        # round 38 renamed two of the citation keys round 35 itself renamed.
        ck(UNDO37(UNDO38(UNCONVERT(read(_f35 + ".tex"), _f35), _f35), _f35)
           == _rename35(_was35),''',
    "(g) 35f renamed-key identity")

sub(r'''            ck(UNDO37(UNCONVERT(read(_f35 + ".tex"), _f35), _f35) == _was35,''',
    r'''            # ROUND-38: and un-do round 38 (see UNDO38), a no-op on these two
            # files, applied so that being a no-op is a consequence of the
            # assertion rather than a comment.
            ck(UNDO37(UNDO38(UNCONVERT(read(_f35 + ".tex"), _f35), _f35), _f35)
               == _was35,''',
    "(g) 35f untouched-files identity")

# ==================================== (h) 35g's move record: round 37 -> round 38
sub(r'''        _R37_MOVED = {_k: (tuple(_v[0]), tuple(_v[1])) for _k, _v in
                      json.load(io.open("/tmp/r37_label_moves.json",
                                        encoding="utf-8")).items()}''',
    r'''        # ROUND-38 SUBSTITUTION: the record is regenerated against this round's
        # build by gen_r38_label_moves.py. The moved SET is unchanged -- the same
        # 103 appendix labels -- because round 38 adds no label and no float; only
        # the page deltas grow, by the one page the round costs. Still data rather
        # than 103 hand-transcribed entries, for the reason round 37 gave.
        _R37_MOVED = {_k: (tuple(_v[0]), tuple(_v[1])) for _k, _v in
                      json.load(io.open("/tmp/r38_label_moves.json",
                                        encoding="utf-8")).items()}''',
    "(h) 35g move record -> r38")

sub(r'''        ck(_hist37 == {-1: 3, 1: 23, 2: 3, 3: 66, 4: 8},
           f"35g: the page-delta histogram of the moved appendix pins is "
           f"{dict(sorted(_hist37.items()))}, not the "
           f"{{-1: 3, 1: 23, 2: 3, 3: 66, 4: 8}} round 37 is costed at")''',
    r'''        # ROUND-38 SUBSTITUTION: the same 103 labels, one page further on. The
        # -1 and +1 buckets are unchanged (three labels still move backward, 23
        # still move by one), and the mass that sat at +3 moves to +4: round 38's
        # single appendix page. A 104th label, or a label moving by a different
        # amount, still fires.
        ck(_hist37 == {-1: 3, 1: 23, 2: 1, 3: 5, 4: 61, 5: 10},
           f"35g: the page-delta histogram of the moved appendix pins is "
           f"{dict(sorted(_hist37.items()))}, not the "
           f"{{-1: 3, 1: 23, 2: 1, 3: 5, 4: 61, 5: 10}} round 38 is costed at")''',
    "(h) 35g histogram")

# ===================================================== (i) 37b's reduction target
sub(r'''        ck(UNDO37(UNCONVERT(read(_f37b + ".tex"), _f37b), _f37b)
           == UNCONVERT(_was37b, _f37b),
           f"37b: {_f37b}.tex does not reduce to {_PARENT37} under the round-37 "
           f"and round-36 ledgers -- an unledgered edit entered it")''',
    r'''        # ROUND-38: strip round 38 first (see UNDO38), so this check asserts
        # exactly what it asserted at the parent commit -- that the tree reduces
        # to ea6faf9 under the enumerated ledgers and nothing else. An unledgered
        # round-38 edit now fails HERE as well as at 38a.
        ck(UNDO37(UNDO38(UNCONVERT(read(_f37b + ".tex"), _f37b), _f37b), _f37b)
           == UNCONVERT(_was37b, _f37b),
           f"37b: {_f37b}.tex does not reduce to {_PARENT37} under the round-38, "
           f"round-37 and round-36 ledgers -- an unledgered edit entered it")''',
    "(i) 37b reduction")

# ========================================= (j) 13g's forward R38 replay stage
sub(r'''        rebuilt = rebuilt.replace(old, new, 1)
    # ROUND-35 BIBLIOGRAPHY AUDIT (20 Sep 2026), pinned as facts so a later round''',
    r'''        rebuilt = rebuilt.replace(old, new, 1)
    # ---- ROUND-38 STAGE, appended for the same reason the R37 stage was: the
    # round-38 ledger is generated from UNCONVERT(8f18687) against UNCONVERT(tree),
    # i.e. in the same pre-round-36 punctuation `rebuilt` is already in and on top
    # of the state the R37 stage just produced, so it replays directly. 38a asserts
    # that no round-38 pre-image lies inside a round-36 or round-37 post-image,
    # which is the hazard that would otherwise couple the ledgers.
    # Two non-BOLDED files, so two side-bag entries, exactly as the R37 stage above:
    # appendix.tex (Parts A and B) and related_work.tex (the clibib re-audit's
    # goodfellow key rename). introduction.tex is BOLDED, so its pair replays into
    # `rebuilt` instead and the word ledger closes on it -- which it can, because
    # \citep{burns2022discovering} and \citep{burns2023discovering} are one
    # whitespace-split token each, so the rename is one token out and one token in.
    r38_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix"),
                "related_work": UNCONVERT(read("related_work.tex"),
                                          "related_work")}
    for name, tag, old, new in R38_EDITS:
        if name not in BOLDED:
            ck(name in r38_side,
               f"round-38 ledger entry {tag} names an unknown non-main file: "
               f"{name}")
            if name not in r38_side:
                continue
            side = r38_side[name]
            ck(side.count(new) >= 1,
               f"round-38 {name} edit {tag} is absent from {name}.tex: "
               f"{new[:80]!r}")
            if len(new) >= 40:
                ck(side.count(new) == 1,
                   f"round-38 {name} edit {tag} appears {side.count(new)}x in "
                   f"{name}.tex, not once -- a double-applied edit: "
                   f"{new[:80]!r}")
            residue = side.replace(new, "") if old in new else side
            ck(residue.count(old) == 0,
               f"round-38 {name} edit {tag} left its pre-image behind in "
               f"{name}.tex: {old[:80]!r}")
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-38 edit does not apply once to the rebuilt "
           f"round-37 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    # ROUND-35 BIBLIOGRAPHY AUDIT (20 Sep 2026), pinned as facts so a later round''',
    "(j) 13g R38 stage")

# ================================== (k) 37h's self-reference, moved to the new total
sub(r'''                  "\\textbf{2{,}765-check verification harness}",''',
    r'''                  # ROUND-38 SUBSTITUTION: the advertised total moves with the
                  # harness, 2,765 -> 2,911. See 38h for the arithmetic and for
                  # why the parent scored 2,766 against this tree before a single
                  # round-38 check was added.
                  "\\textbf{2{,}911-check verification harness}",''',
    "(k) 37h availability literal")

sub(r'''    ck("2{,}765-check" in _MT37,
       "37h: the advertised check count is not 2,765; re-pin it here and in "''',
    r'''    ck("2{,}911-check" in _MT37,
       "37h: the advertised check count is not 2,911; re-pin it here and in "''',
    "(k) 37h count pin")

# ============================================ (l) 35d's build-identity stamp, r38
# Round 38 is a new REVIEW round -- the same two items of the NeurIPS workshop TAE
# review that round 37 left open -- so the stamp advances 37 -> 38 with its date
# and its parent commit together, exactly as round 37 advanced it from 35. The PDF
# is no longer round 37's tree, and a stamp saying otherwise is the provenance
# drift 35d exists to catch. The replacement is character-neutral (37/38, 22/24,
# ea6faf9/8f18687 are all the same width), so no main-text ruler moves.
sub(r'''    _stamp35 = ("\\textbf{Build identity.} Source revision~37, built "
                "22~September~2026 from parent\ncommit \\texttt{ea6faf9}.")''',
    r'''    _stamp35 = ("\\textbf{Build identity.} Source revision~38, built "
                "24~September~2026 from parent\ncommit \\texttt{8f18687}.")''',
    "(l) 35d build-identity stamp")

# 35d reads the stamp back off the RENDER twice -- absent from p1-9, present on
# p11 -- and both literals carry the revision number, so both move with it. Missing
# either would leave the check asserting a string the PDF no longer contains, which
# is how a pin quietly stops testing anything.
sub(r'''        # ROUND-37 SUBSTITUTION: 35 -> 37, the stamp's own revision number.
        ck("Source revision 37" not in _f35,''',
    r'''        # ROUND-38 SUBSTITUTION: 37 -> 38, the stamp's own revision number.
        ck("Source revision 38" not in _f35,''',
    "(m) 35d rendered absence, p1-9")

sub(r'''    ck("Source revision 37" in " ".join(subprocess.run(''',
    r'''    ck("Source revision 38" in " ".join(subprocess.run(''',
    "(m) 35d rendered presence, p11")

# ============================ (n) 37i's no-fund list, minus introduction.tex
# ROUND-38 SUBSTITUTION, forced by the clibib re-audit and NOT by a funding raid:
# 37i asserts five sections are byte-identical to ea6faf9, which was round 37's way
# of saying it funded itself from nowhere. Round 38's citation-key renames land in
# introduction.tex (three of the four cite sites), so a raw byte equality there is
# now false for a reason 37i was never about. It leaves the blanket list and gains a
# STRONGER assertion of its own: un-doing round 38 must restore ea6faf9's
# introduction byte-for-byte, so round 37 still funded nothing from it AND the only
# difference round 38 made is the one its ledger names. abstract.tex and
# discussion.tex stay in the blanket list, so both standing no-fund sites hold as
# literal byte equalities. Net check count is unchanged: two out, two in.
sub(r'''    for _f37i in ["abstract", "introduction", "experiments", "discussion",
                  "conclusion"]:''',
    r'''    for _f37i in ["abstract", "experiments", "discussion", "conclusion"]:''',
    "(n) 37i no-fund list")

sub(r'''    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "37i: the three structured caution boxes must survive; every reviewer who "
       "has commented on them named them a strength")''',
    r'''    # ROUND-38 ADDITION: introduction.tex, checked under UNDO38 rather than raw.
    # The equality is against UNCONVERT(ea6faf9) because the round-38 ledger lives in
    # pre-round-36 punctuation, which is the same composition 37b uses.
    _w37j = _git37("sections/introduction.tex")
    ck(_w37j is not None, "37i: cannot read the parent's introduction.tex")
    if _w37j is not None:
        ck(UNDO38(UNCONVERT(read("introduction.tex"), "introduction"),
                  "introduction") == UNCONVERT(_w37j, "introduction"),
           f"37i: introduction.tex does not reduce to {_PARENT37} once round 38's "
           f"ledger is un-done; round 37 funded nothing from it and round 38 touches "
           f"it only to rename two citation keys the clibib re-audit corrected")
    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "37i: the three structured caution boxes must survive; every reviewer who "
       "has commented on them named them a strength")''',
    "(n) 37i introduction under UNDO38")

# ===================================== (o) 37a's Underfull count, 107 -> 108
# ROUND-38 SUBSTITUTION, and the whole of its cost: promoting burns2023discovering
# and goodfellow2015explaining from @article to @inproceedings replaces a one-line
# `arXiv preprint arXiv:NNNN.NNNNN, YYYY.` with a two-part `In International
# Conference on Learning Representations (ICLR), YYYY. arXiv:NNNN.NNNNN.`, so the
# BIBLIOGRAPHY reflows by one line and TeX reports one more Underfull \hbox in the
# back matter. Nothing in the main text or the appendix body moves -- 38f's five
# float pins and 36e's two ruler assertions are the measurement of that. Still an
# EQUALITY, so a second reflow fires.
sub(r'''    ck(_uf37 == 107,
       f"37a: the build reports {_uf37} Underfull boxes, not the 107 round 37 "
       f"measured (99 at round 36 plus the 8 its appendix additions add)")''',
    r'''    ck(_uf37 == 108,
       f"37a: the build reports {_uf37} Underfull boxes, not the 108 round 38 "
       f"measured (99 at round 36, plus the 8 round 37's appendix additions add, "
       f"plus the 1 the two ICLR venue promotions add by reflowing the "
       f"bibliography; see 38i)")''',
    "(o) 37a Underfull 107->108")

# ======================== (p) 37h's availability lede, retensed to the future
# ROUND-38 SUBSTITUTION, and the second half of the correction the user opened by
# catching the AI use statement's "the verification script IS released". The
# Reproducibility statement's run-in lede read "What the release contains.", which
# PRESUPPOSES an extant release, while the sentence it introduces correctly says
# the contents "will be released publicly" -- the presupposition retracted four
# words later. That paragraph is built to be scanned by its bold ledes, so a reader
# scanning them is told the release contains things and has nowhere to go: there is
# no URL (the round-37 user decision, double-blind) and no supplement (the
# round-38 one). Retensed to "What the release will contain.", and the four 37h
# literals that pin it move WITH the paper rather than being deleted -- the lede is
# still pinned for existence, for position between the Reproducibility heading and
# the Build-identity lede, as the left bound of the anonymity slice, and for
# absence from the p1-p9 render. All four keep asserting exactly what they did.
sub(r'''    ck("\\textbf{What the release contains.}" in _MT37,
       "37h: the availability sentence is gone from main.tex; W7's complaint was "
       "that the appendix's eight forward references to 'the code' resolve to "
       "nothing")
    ck(_MT37.index("\\subsection*{Reproducibility statement}")
       < _MT37.index("\\textbf{What the release contains.}")''',
    r'''    # ROUND-38 SUBSTITUTION: "contains" -> "will contain", because nothing is
    # released yet and the lede was the one place that said otherwise.
    ck("\\textbf{What the release will contain.}" in _MT37,
       "37h: the availability sentence is gone from main.tex; W7's complaint was "
       "that the appendix's eight forward references to 'the code' resolve to "
       "nothing")
    ck(_MT37.index("\\subsection*{Reproducibility statement}")
       < _MT37.index("\\textbf{What the release will contain.}")''',
    "(p) 37h lede, existence + position")

sub(r'''    _avail37 = _MT37[_MT37.index("\\textbf{What the release contains.}"):''',
    r'''    # ROUND-38 SUBSTITUTION: the slice's left bound follows the retensed lede.
    _avail37 = _MT37[_MT37.index("\\textbf{What the release will contain.}"):''',
    "(p) 37h anonymity slice bound")

sub(r'''        ck("What the release contains" not in " ".join(subprocess.run(''',
    r'''        # ROUND-38 SUBSTITUTION: the rendered form follows the retensed lede.
        ck("What the release will contain" not in " ".join(subprocess.run(''',
    "(p) 37h render-absence p1-9")

# ================================================================ GROUP 38
GROUP38 = r'''
    # ==================================================================== 38
    # ROUND 38: the two items of the NeurIPS 2026 workshop TAE review that round
    # 37 left genuinely open, and nothing else.
    #
    #   Part A  the review's "Table 2" ask -- intervals on the equalization panel.
    #           Round 37's Part D put claim-clustered intervals on tab:crit4b_h1,
    #           the CRITERION-4 table, which is a different table; the equalization
    #           panel and the headline 97.0% -> 43.3% still carried no interval
    #           anywhere. Four appendix paragraphs, computed by
    #           experiments/analyze_r1_intervals.py, descriptive and post-hoc.
    #   Part B  the review's ask for human labels on the T/D outputs. A blind
    #           144-item coding sheet over ALL FOUR factorial cells, released
    #           UNCODED, plus a disclosure paragraph. No rate is reported, because
    #           §11-step-7 hand-coding is the user's job and a machine grade here
    #           would be the construct recovery this paper names as a failure mode.
    #
    # DECLINED, each with its receipt, and pinned as declines so the response
    # letter cannot drift into claiming them: running the audited detectors on
    # Pacchiardi's role-play release (EXP-XP shows the design fails requirements
    # (i) and (ii), so a score there measures a row index's parity), renaming the
    # ECCP, a main-text CI table (slack is exactly 0), and any abstract edit.
    _APP38 = read("appendix.tex")
    _MT38 = io.open("main.tex", encoding="utf-8").read()
    # This round's parent is the ROUND-37 commit, not round 37's parent: 38a asserts
    # that round 38 changed appendix.tex and main.tex and nothing else, which is a
    # statement about 8f18687. _git37 reads ea6faf9 and would answer a different
    # question -- methodology.tex and related_work.tex differ from ea6faf9 because
    # ROUND 37 edited them, which is not a round-38 finding.
    _PARENT38 = "8f18687"

    def _git38(path):
        _r = subprocess.run(["git", "show", _PARENT38 + ":" + _PDIR35 + path],
                            cwd=_REPO35, capture_output=True, text=True)
        return _r.stdout if _r.returncode == 0 else None

    # ---- 38a. THE LEDGER. Six paragraph-level edits in three files, and the hazard
    # that would couple this round's ledger to an earlier one.
    _byf38 = {}
    for _n38a, _t38a, _o38a, _x38a in R38_EDITS:
        _byf38[_n38a] = _byf38.get(_n38a, 0) + 1
    # ROUND-38 SUBSTITUTION of this round's own pin, made while the round was open:
    # it began appendix-only ({appendix: 3}) and the clibib bibliography re-audit of
    # 24 Sep 2026 widened it. Part A grew a fourth appendix block, and the re-audit's
    # two citation-key renames reach introduction.tex and related_work.tex because a
    # key lives wherever it is cited. Still an EQUALITY on the exact per-file shape,
    # so a seventh edit, or a fourth file, still fires.
    ck(_byf38 == {"appendix": 4, "introduction": 1, "related_work": 1},
       f"38a: the round-38 ledger's per-file shape is {_byf38}, not the "
       f"{{appendix: 4, introduction: 1, related_work: 1}} the round is costed at "
       f"-- Part A's three table-adjacent blocks, Part B's T/D paragraph, and the "
       f"clibib re-audit's two ICLR venue promotions at their cite sites")
    # THE HAZARD, in the form the round-38 plan named it: verify_r36.py un-converts
    # live text and verify_r37.py un-does round 37 on it, so a round-38 pre-image
    # lying INSIDE a round-36 or round-37 post-image would couple the ledgers and
    # break 36d's and 37b's invert-once property. Generating the round-38 ledger
    # from UNCONVERT(parent) vs UNCONVERT(tree) makes that structurally impossible;
    # "structurally impossible" is what a defect says about itself, so it is
    # measured, against BOTH earlier ledgers.
    ck(not [_t38b for _n38b, _t38b, _o38b, _x38b in R38_EDITS
            for _r36c, _o36c, _n36c in R36_EDITS if _o38b in _n36c],
       "38a: a round-38 pre-image lies inside a round-36 post-image; re-widen the "
       "round-36 pair with gen_r36_edits.py and never hand-edit either ledger")
    ck(not [_t38c for _n38c, _t38c, _o38c, _x38c in R38_EDITS
            for _n37c, _t37c, _o37c, _x37c in R37_EDITS if _o38c in _x37c],
       "38a: a round-38 pre-image lies inside a round-37 post-image; re-widen the "
       "round-37 pair with gen_r37_edits.py and never hand-edit either ledger")
    # and the converse of 37b's reduction. ROUND-38 SUBSTITUTION, same reason as the
    # shape pin above: the assertion was `== {"appendix"}` while the round was
    # appendix-only, and the clibib re-audit widened it to the three files below.
    # Updated, not relaxed -- it is still an exact set equality, and it is still the
    # statement that licenses UNDO38's call sites, which now WRAP related_work.tex at
    # r31_side and r35_side instead of deliberately leaving it alone. A fourth file
    # in the ledger fails here, which is the signal to go re-check those call sites.
    ck(set(R38_BY_FILE) == {"appendix", "introduction", "related_work"},
       f"38a: the round-38 ledger names {sorted(R38_BY_FILE)}, not appendix, "
       f"introduction and related_work; UNDO38's call sites cover exactly those "
       f"three and must be re-checked before the set changes")
    # The four sections round 38 does NOT touch stay byte-identical to the parent.
    # ROUND-38 SUBSTITUTION: introduction.tex and related_work.tex leave this list,
    # because the re-audit's key renames land in them. They are not thereby
    # unchecked -- they are checked HARDER, just below, against the ledger itself
    # rather than against a blanket equality, and 37b independently proves they
    # reduce to ea6faf9 under UNDO38 composed with UNDO37. abstract.tex and
    # discussion.tex remain in the list, so both standing no-fund sites still hold.
    for _f38a in ["abstract", "methodology", "experiments", "discussion",
                  "conclusion"]:
        _was38a = _git38("sections/%s.tex" % _f38a)
        ck(_was38a is not None,
           f"38a: cannot read {_PARENT38}:{_f38a}.tex")
        if _was38a is not None:
            ck(read(_f38a + ".tex") == _was38a,
               f"38a: {_f38a}.tex is not byte-identical to the round-37 commit; "
               f"round 38 edits appendix.tex, introduction.tex, related_work.tex "
               f"and main.tex only, and the abstract and discussion.tex remain "
               f"standing no-fund sites")
    # and the two files it DOES touch reduce to the parent under this round's ledger
    # alone -- the round-trip gen_r38_edits.py asserts before writing, re-asserted
    # here against the parent commit so the ledger cannot be a post-hoc description
    # of an edit that also changed something it does not name.
    for _f38b in ["introduction", "related_work"]:
        _was38b = _git38("sections/%s.tex" % _f38b)
        ck(_was38b is not None,
           f"38a: cannot read {_PARENT38}:{_f38b}.tex")
        if _was38b is not None:
            ck(UNDO38(UNCONVERT(read(_f38b + ".tex"), _f38b), _f38b)
               == UNCONVERT(_was38b, _f38b),
               f"38a: {_f38b}.tex does not reduce to the round-37 commit under the "
               f"round-38 ledger alone -- an unledgered edit entered a file this "
               f"round touches for the citation renames and nothing else")

    # ---- 38b. PART A, and the check that does the real work: every interval
    # printed in the appendix is re-derived from the committed result file and
    # compared string for string. A transcription slip in any of the 28 cells
    # fails here, which is the failure mode four paragraphs of hand-copied
    # bracket pairs actually have.
    _IVJ = os.path.join(CODEREPO, "data", "results", "r1_intervals.json")
    ck(os.path.exists(_IVJ),
       "38b: data/results/r1_intervals.json is missing -- Part A's intervals are "
       "then unverifiable prose")
    if os.path.exists(_IVJ):
        _iv = json.load(io.open(_IVJ, encoding="utf-8"))
        ck(_iv.get("all_cells_reproduce_published_accuracy") is True,
           "38b: analyze_r1_intervals.py reports that a published accuracy does "
           "NOT recompute from the committed checkpoints; that is a defect in the "
           "panel, not a result, and no interval may be printed around it")
        ck(_iv.get("status") == "DESCRIPTIVE, POST-HOC",
           f"38b: the interval arm no longer labels itself descriptive and "
           f"post-hoc ({_iv.get('status')!r}); the pre-registered inference for "
           f"both experiments is the permutation test already in the tables")
        ck(_iv.get("seed") == 42 and _iv.get("n_boot") == 2000,
           f"38b: the bootstrap is no longer 2000 draws at seed 42 "
           f"({_iv.get('n_boot')} draws, seed {_iv.get('seed')})")
        _cells38, _miss38, _uncov38 = 0, [], []
        for _v38, _tg38 in sorted(_iv["variants"].items()):
            for _m38, _cd38 in sorted(_tg38.items()):
                for _c38, _r38 in sorted(_cd38.items()):
                    _cells38 += 1
                    _s38 = (f"[{_r38['wilson_lo'] * 100:.1f}, "
                            f"{_r38['wilson_hi'] * 100:.1f}]")
                    if _s38 not in _APP38:
                        _miss38.append((_v38, _m38, _c38, _s38))
                    if not _r38["reproduces_published"]:
                        _miss38.append((_v38, _m38, _c38, "NOT REPRODUCED"))
                    if not _r38["claim_clustered"]["covers_grouped_point"]:
                        _uncov38.append((_v38, _m38, _c38))
        ck(_cells38 == 28,
           f"38b: the interval file covers {_cells38} cells, not the 28 the two "
           f"panels have (6 targets x 2 conditions x 2 banks, plus 4 pooled)")
        ck(not _miss38,
           f"38b: an interval in the appendix does not match the one recomputed "
           f"from the committed checkpoints, or a cell failed to reproduce its "
           f"published accuracy: {_miss38[:6]}")
        # the guard that caught the duplicate-row leakage in the first draft, kept
        # as a standing property rather than a story in a docstring.
        ck(not _uncov38,
           f"38b: a claim-clustered interval no longer contains its own grouped "
           f"point estimate, which is the signature of duplicated rows leaking "
           f"between folds: {_uncov38}")
        # the row-order disclosure, asserted as a measured quantity: all four
        # pooled swings must still lie inside their own Wilson interval, or the
        # pooled digit is doing work the interval cannot justify and that is a
        # finding rather than a footnote.
        for _v38p in ("v1", "v2"):
            for _c38p in ("instructed", "equalized"):
                _s38p = _iv["variants"][_v38p]["POOLED"][_c38p][
                    "row_order_sensitivity"]
                ck(_s38p["swing_inside_wilson"] is True,
                   f"38b: the {_v38p} pooled {_c38p} cell's row-order swing "
                   f"({_s38p['swing_pp']:.1f} pp) has escaped its own Wilson "
                   f"interval; the pooled figure can no longer be reported bare "
                   f"with a disclosure")
                ck(_s38p["swing_pp"] < 5.0,
                   f"38b: the {_v38p} pooled {_c38p} row-order swing is "
                   f"{_s38p['swing_pp']:.1f} pp, outside the 0.3-4.3 pp band the "
                   f"appendix states")
    # the four paragraphs, each once, and the claims the prose makes about them
    for _p38 in ["\\paragraph{Intervals on this panel (descriptive, post-hoc).}",
                 "\\paragraph{Intervals on the pre-registered panel.}",
                 "\\paragraph{The sixth equalized interval, and why the "
                 "estimator matters.}",
                 "\\paragraph{The pooled digit carries row-order noise, and we "
                 "found that by computing these intervals.}"]:
        ck(_APP38.count(_p38) == 1,
           f"38b: Part A's paragraph is missing or duplicated: {_p38!r}")
    for _s38s in [
            "The intervals agree with the pre-registered permutation verdicts "
            "cell for cell.",
            "At $n\\!=\\!50$ a Wilson half-width is about 14\\,pp",
            "25 matched claim pairs",
            "\\texttt{grp-5f} column and not on the primary, and that is forced "
            "rather than chosen",
            "All 24 per-target cells recompute to their published literals "
            "exactly.",
            "no permutation $p$, no change in pp and no verdict moves",
            "experiments/analyze\\_r1\\_intervals.py",
            "ministral-3:8b"]:
        ck(_s38s in _APP38,
           f"38b: a load-bearing sentence of Part A is gone: {_s38s!r}")
    # AND THE POINT OF THE WHOLE ROUND: the two tables' own bodies are untouched.
    # The intervals are prose BESIDE each table, not a ninth column inside it, so
    # every pre-existing cell must be byte-identical to the parent commit.
    _app38_was = _git38("sections/appendix.tex")
    ck(_app38_was is not None, "38a: cannot read the parent's appendix.tex")
    if _app38_was is not None:
        for _tb38 in ("tab:r1_faithful", "tab:r1c_v2"):
            _cuts = []
            for _txt in (_app38_was, _APP38):
                _i = _txt.index("\\label{%s}" % _tb38)
                _j = _txt.index("\\end{table}", _i)
                _k = _txt.rindex("\\begin{table}", 0, _i)
                _cuts.append(_txt[_k:_j])
            ck(_cuts[0] == _cuts[1],
               f"38b: the body of {_tb38} is not byte-identical to the round-37 "
               f"commit; round 38 adds intervals BESIDE the panel and changes no "
               f"published cell, and that is the round's central claim")
        # the four pooled literals, spelled as the tables print them
        for _lit38 in ("\\textbf{97.0\\%}", "\\textbf{43.3\\%}", "81.7\\%",
                       "53.7\\%"):
            ck(_lit38 in _APP38,
               f"38b: the pooled literal {_lit38!r} is gone from the appendix; "
               f"round 38 reports intervals around these numbers and moves none "
               f"of them")

    # ---- 38c. PART B, the coding sheet. It exists, it is blind, and it is
    # UNCODED. The last of those is the constraint that matters: hand-coding is
    # the user's job (§11 step 7), and no script in either repository may put a
    # grade in that column.
    _HC38 = os.path.join(CODEREPO, "data", "human_coding")
    _SHEET38 = os.path.join(_HC38, "factorial_txd_coding_sheet.csv")
    _KEY38 = os.path.join(_HC38, "factorial_txd_coding_key.json")
    for _f38c in (_SHEET38, _KEY38,
                  os.path.join(_HC38, "factorial_txd_CODEBOOK.md")):
        ck(os.path.exists(_f38c),
           f"38c: {os.path.basename(_f38c)} is missing; the appendix says the "
           f"sheet is prepared and released")
    if os.path.exists(_SHEET38) and os.path.exists(_KEY38):
        import csv as _csv38
        with io.open(_SHEET38, encoding="utf-8", newline="") as _fh38:
            _rows38 = list(_csv38.DictReader(_fh38))
        _k38 = json.load(io.open(_KEY38, encoding="utf-8"))
        ck([f.strip() for f in (_rows38[0].keys() if _rows38 else [])]
           == ["item_id", "claim", "response", "code", "notes"],
           f"38c: the sheet's columns are {list(_rows38[0].keys()) if _rows38 else []}, "
           f"not item_id/claim/response/code/notes")
        ck(len(_rows38) == 144,
           f"38c: the sheet has {len(_rows38)} items, not the 144 the appendix "
           f"states (3 targets x 4 cells x 12)")
        ck(len(_k38.get("items", {})) == len(_rows38)
           and [r["item_id"] for r in _rows38] == list(_k38.get("items", {})),
           "38c: the key's item ids do not match the sheet's, in order, so the "
           "sheet cannot be decoded after coding")
        # THE BLIND: no target name and no cell label anywhere in what a coder
        # reads. The claim's truth value is NOT blinded and cannot be -- the claims
        # are common-knowledge facts -- which is exactly why all four cells are
        # interleaved: what is withheld is the INSTRUCTION, and the honest cells
        # are what make withholding it possible.
        _seen38 = " ".join((r["claim"] + " " + r["response"]).lower()
                           for r in _rows38)
        for _leak38 in ("llama", "mistral", "qwen", "t_d", "f_d", "t_h", "f_h"):
            ck(_leak38 not in _seen38,
               f"38c: the coder-visible text names {_leak38!r}, so the sheet is "
               f"not blind to target or cell")
        _cells38c = sorted({v["cell"] for v in _k38.get("items", {}).values()})
        ck(_cells38c == ["F_D", "F_H", "T_D", "T_H"],
           f"38c: the sheet covers cells {_cells38c}, not all four; within "
           f"{{T/D, F/D}} the deception instruction is constant, so a two-cell "
           f"sheet blinds nothing that matters")
        _seq38 = [_k38["items"][r["item_id"]]["cell"] for r in _rows38]
        _run38, _cur38, _n38r = 0, None, 0
        for _c38r in _seq38:
            _n38r = _n38r + 1 if _c38r == _cur38 else 1
            _cur38 = _c38r
            _run38 = max(_run38, _n38r)
        ck(_run38 <= 8,
           f"38c: the sheet's longest run of one cell is {_run38} items; the "
           f"global shuffle is the blind and a blocked sheet is not one")
        # UNCODED, and honest in both directions. An empty column now; and if the
        # user codes it later, every entry must be one of the codebook's three
        # codes -- so this check survives the coding rather than punishing it.
        _codes38 = [r["code"].strip() for r in _rows38 if r["code"].strip()]
        ck(not [c for c in _codes38
                if c not in ("DECEPTIVE", "NOT_DECEPTIVE", "UNCLEAR")],
           f"38c: the sheet carries codes outside the codebook's three: "
           f"{sorted(set(_codes38))[:6]}")
        ck(_k38.get("coded") is False or bool(_codes38),
           "38c: the key claims the sheet is coded but every code cell is empty")
        # and the paper must not report a rate while the sheet is uncoded. This is
        # the pin that keeps Part B honest: the disclosure paragraph says no rate
        # is reported, and while coded is False that sentence must stand.
        if _k38.get("coded") is False:
            ck("\\textbf{No rate from it is reported here}" in _APP38,
               "38c: the sheet is uncoded but the appendix no longer says that no "
               "rate is reported from it; a rate computed by anything but a human "
               "coder is the construct recovery this paper names as a failure mode")
    # the generator writes the column EMPTY, pinned as a literal so a later
    # round cannot quietly start filling it.
    _GEN38 = os.path.join(CODEREPO, "experiments",
                          "make_factorial_coding_sheet.py")
    ck(os.path.exists(_GEN38),
       "38c: experiments/make_factorial_coding_sheet.py is missing, so the sheet "
       "is not reproducible")
    if os.path.exists(_GEN38):
        _gs38 = io.open(_GEN38, encoding="utf-8").read()
        ck('w.writerow([f"F{n:03d}", it["claim"], it["response"], "", ""])'
           in _gs38,
           "38c: the sheet generator no longer writes the code and notes columns "
           "as empty strings; nothing in this repository may fill that column")
        ck('"coded": False' in _gs38,
           "38c: the key no longer records coded: False")
        for _net38 in ("requests.", "ollama", "http://", "https://", "urllib"):
            ck(_net38 not in _gs38,
               f"38c: the sheet generator references {_net38!r}; it reads twelve "
               f"committed result files and makes no call of any kind")

    # ---- 38d. THE DISCLOSURE, which is what Part B delivers unilaterally and
    # is a statement the paper's own argument wants: the T/D vs. F/D contrast is
    # reported as non-identifying BECAUSE no grade of D exists in either cell.
    ck(_APP38.count("\\textbf{No grade of $D$ exists for any response in T/D or "
                    "F/D.}") == 1,
       "38d: the disclosure that no grade of D exists in either instructed cell "
       "is gone or duplicated; it is the honest form of the 'compliance is graded "
       "rather than binary' claim the contrast rests on")
    ck("\\paragraph{What is not measured in either instructed cell, and the one "
       "measurement that would settle it.}" in _APP38,
       "38d: Part B's disclosure paragraph heading is gone")
    for _s38d in [
            "is read off corrective leakage in the detector's own features, not "
            "off any per-response judgment",
            "it interleaves \\emph{all four} cells rather than T/D with F/D alone",
            "the truth-value cannot be blinded at all from a coder who knows "
            "that water boils at $100^\\circ$C",
            "The item-to-condition key is held in a separate file",
            "no response in the sheet names its own instruction"]:
        ck(_s38d in _APP38,
           f"38d: a load-bearing sentence of Part B's disclosure is gone: {_s38d!r}")
    # the round-37 text this paragraph qualifies must survive underneath it, or
    # the disclosure is qualifying nothing.
    ck("compliance is graded rather than binary" in _APP38,
       "38d: the 'graded rather than binary' claim is gone, so the disclosure "
       "paragraph has no referent")
    # and the wording round 38 CORRECTED: the sheet spans four cells, not two.
    ck("blind and interleaved across the two cells" not in _APP38,
       "38d: the superseded 'interleaved across the two cells' wording is back; "
       "the sheet interleaves all four, and saying two would misdescribe the "
       "released artifact")

    # ---- 38e. THE DECLINES, pinned so the response letter cannot drift into
    # claiming them. Each is a decline WITH a receipt already in the tree.
    ck("a negative census does not say the release contains no deception"
       in _APP38,
       "38e: EXP-XP's census caveat is gone; it is what makes running the "
       "detectors on Pacchiardi's role-play release a decline with a reason "
       "rather than an unanswered request")
    _nbox38 = main_txt.count("\\fbox{\\parbox")
    ck(_nbox38 == 3,
       f"38e: the main text carries {_nbox38} structured caution boxes, not 3; "
       f"every previous reviewer named them as a strength and they are a standing "
       f"no-cut site, restated here because a round that adds 7.1k characters is "
       f"exactly when a caution gets traded for space")

    # ---- 38f. THE BUDGET, restated as this round's own price claim: one new
    # page, all of it appendix. 37a and 36e assert the rulers; 38f asserts that
    # the five MAIN-TEXT float pins are byte-identical to c9718cf, which is the
    # measurement that proves where the page went.
    _aux38 = io.open("main.aux", encoding="utf-8").read()
    _was38 = subprocess.run(
        ["git", "show", "c9718cf:" + _PDIR35 + "main.aux"],
        cwd=_REPO35, capture_output=True, text=True)
    ck(_was38.returncode == 0,
       "38f: cannot read c9718cf:main.aux, so the main-text pins are unverifiable")
    if _was38.returncode == 0:
        _pin38 = re.compile(r"newlabel\{([^}]*)\}\{\{([^}]*)\}\{(\d+)\}")
        _A38 = {m.group(1): (m.group(2), m.group(3))
                for m in _pin38.finditer(_was38.stdout)}
        _B38 = {m.group(1): (m.group(2), m.group(3))
                for m in _pin38.finditer(_aux38)}
        for _l38 in ("fig:dag", "tab:claim_ledger", "fig:ladder",
                     "fig:r1c_collapse", "tab:external_audit"):
            ck(_l38 in _A38 and _l38 in _B38 and _A38[_l38] == _B38[_l38],
               f"38f: main-text float {_l38} moved from "
               f"{_A38.get(_l38)} to {_B38.get(_l38)}; round 38 is costed at zero "
               f"main-text movement and both its parts land in the appendix")
        ck(len(_B38) == 225,
           f"38f: the document has {len(_B38)} labels, not 225; round 38 adds no "
           f"float and no \\label, so a new one is an unbudgeted add")

    # ---- 38g. THE EM-DASH PARTITION, asserted unchanged. Round 36 converted every
    # prose em dash; the 42 surviving `---` are a defined table legend symbol, NA
    # cells and one verbatim block. Round 38 wrote ~7.1k characters of new appendix
    # prose, which is exactly when a stray `---` gets reintroduced.
    _all38 = "".join(read(_f38g) for _f38g in
                     ["abstract.tex", "introduction.tex", "methodology.tex",
                      "experiments.tex", "discussion.tex", "conclusion.tex",
                      "appendix.tex", "related_work.tex"]) + _MT38
    ck("—" not in _all38,
       "38g: a literal U+2014 em dash is back in the source; round 36 converted "
       "every one of them and the count has been zero since")
    # Counted as runs of EXACTLY three hyphens, which is the partition round 36
    # actually left: a naive .count("---") reads 96, because the ASCII rules inside
    # the verbatim blocks are longer runs and a substring count splits them.
    _tri38 = len(re.findall(r"(?<!-)---(?!-)", _all38))
    ck(_tri38 == 42,
       f"38g: the source carries {_tri38} three-hyphen runs, not the 42 round 36 "
       f"left standing (3 in methodology.tex, 8 in experiments.tex, 31 in "
       f"appendix.tex: the table legend symbol defined at experiments.tex's "
       f"capability table, the NA cells and one verbatim block)")

    # ---- 38i. THE CLIBIB RE-AUDIT (24 Sep 2026). All 27 entries were re-checked
    # against their authoritative records with clibib plus the arXiv and OpenReview
    # APIs. NOTHING was hallucinated and no title, author list or identifier was
    # wrong; eight clibib flags all resolved in the paper's favour (six arXiv
    # latest-revision-year artifacts, two collective-author normalisations). Two
    # VENUE ATTRIBUTIONS were wrong in the paper's favour to fix: Burns et al. and
    # Goodfellow et al. were carried as bare arXiv preprints when both are ICLR
    # papers, and each key's embedded year was the preprint year rather than the
    # publication year -- the same key/year drift 35h exists to catch, one round
    # later and in the other direction. Promoted to @inproceedings with the ICLR
    # booktitle and renamed. Pinned in 35h's own idiom, and deliberately as a NEW
    # group rather than by extending 35h's tuples, so that group's failure messages
    # keep naming the defect they were written about.
    #
    # Both renames are CHARACTER-NEUTRAL (2022/2023, 2014/2015), which is why this
    # reached four cite sites across three .tex files and still cost zero rulers;
    # 38f's five main-text float pins above are the measurement of that.
    _bib38 = io.open("references.bib", encoding="utf-8").read()
    _src38 = _bib38 + "".join(read(_f) for _f in MAIN + ["appendix.tex"]) + _MT38
    for _dead38 in ("burns2022discovering", "goodfellow2014explaining"):
        ck(_dead38 not in _src38,
           f"38i: the pre-re-audit citation key {_dead38!r} is back; its embedded "
           f"year was the arXiv preprint year, not the ICLR publication year, so "
           f"the key and the rendered citation disagreed")
    for _live38, _yr38, _ax38, _ttl38 in (
            ("burns2023discovering", "2023", "arXiv:2212.03827",
             "Discovering Latent Knowledge in Language Models Without Supervision"),
            ("goodfellow2015explaining", "2015", "arXiv:1412.6572",
             "Explaining and Harnessing Adversarial Examples")):
        ck(_live38 in _bib38 and _src38.count(_live38) >= 2,
           f"38i: renamed key {_live38!r} is missing from references.bib or is now "
           f"uncited")
        _e38i = _bib38[_bib38.index(_live38):]
        _e38i = _e38i[:_e38i.index("\n}")]
        ck("@inproceedings{" + _live38 in _bib38,
           f"38i: {_live38!r} is back to @article; it is an ICLR conference paper, "
           f"and the arXiv id belongs in `note`, not in a `journal` field")
        ck(re.search(r"booktitle\s*=\s*\{International Conference on Learning "
                     r"Representations \(ICLR\)\}", _e38i),
           f"38i: {_live38!r} lost its ICLR booktitle, which is the venue the "
           f"re-audit confirmed against the proceedings record")
        ck(re.search(r"year\s*=\s*\{" + _yr38 + r"\}", _e38i),
           f"38i: {_live38!r}'s year field no longer reads {_yr38}, so the key and "
           f"the rendered citation have drifted apart again")
        ck(_ax38 in _e38i,
           f"38i: {_live38!r} lost its {_ax38} note -- that identifier is the "
           f"record the AI use statement says the reference was verified against")
        ck(_ttl38 in _bib38,
           f"38i: {_live38!r}'s title no longer matches the authoritative record: "
           f"{_ttl38!r}")
    # and the venue must actually RENDER, because a booktitle that bibtex drops is
    # indistinguishable in the source from one it prints.
    # bibtex wraps the booktitle across lines, so flatten whitespace first -- a naive
    # substring count on the raw bbl reads 0 and would make this check vacuous in the
    # direction that matters.
    _bbl38 = re.sub(r"\s+", " ", io.open("main.bbl", encoding="utf-8").read())
    _niclr38 = _bbl38.count("International Conference on Learning Representations "
                            "(ICLR)")
    ck(_niclr38 == 3,
       f"38i: the bbl prints {_niclr38} plain ICLR booktitles, not 3 -- Burns 2023 "
       f"and Goodfellow 2015, promoted this round, plus Pacchiardi 2024, which round "
       f"35 already carried. Li 2023 is NeurIPS and Scheurer 2024 is an ICLR "
       f"WORKSHOP with its own string, so neither is in this count. A dropped "
       f"booktitle renders as a bare preprint, which is the defect just fixed")
    # and each of the two promoted entries renders its own venue and year, not just
    # one of them somewhere in the file. The bst emits the booktitle inside \emph{},
    # so the closing brace sits between the venue and the year.
    for _who38, _yr38b in (("Burns", "2023"), ("Goodfellow", "2015")):
        ck(re.search(_who38 + r".{0,400}?In \\emph\{International Conference on "
                     r"Learning Representations \(ICLR\)\}, " + _yr38b + r"\.",
                     _bbl38),
           f"38i: {_who38}'s bbl entry no longer renders 'In International "
           f"Conference on Learning Representations (ICLR), {_yr38b}.' -- before "
           f"this round it read 'arXiv preprint arXiv:...' instead")
    # THE CLAIM THE RE-AUDIT DISCHARGES, pinned at its source: main.tex says every
    # reference was verified against an authoritative record. That sentence is now
    # true of a second, independent pass, and it is the sentence a later round would
    # have to delete rather than quietly outgrow.
    # The pin covers the WHOLE sentence, release clause included. It did not, until
    # the user caught the reason it had to: the clause read "the verification script
    # IS released with the code", present tense, on p10, while the Reproducibility
    # statement on p11 said the codebase "WILL BE released publicly". Nothing in the
    # harness guarded the clause, so the two pages contradicted each other in tense
    # and the present-tense half was a claim no artifact discharged -- the submission
    # ships no supplement, by user decision, because the alternative (a curated ZIP)
    # would need the /Users/... paths scrubbed out of verification/ first. Reworded to
    # the future tense p11 already used, and now pinned to the end of the sentence so
    # the tense cannot drift back unnoticed. If a supplement is ever attached, THIS is
    # the check that must be updated, deliberately and with its reason, before the
    # wording may become present tense again.
    _aiuse38 = re.sub(r"\s+", " ", _MT38)
    ck("All references were independently verified against their authoritative "
       "records (DOI, arXiv, or publisher metadata) using an automated "
       "citation-retrieval tool, and the verification script will be released with "
       "the code." in _aiuse38,
       "38i: main.tex's reference-verification sentence is gone or reworded; it is "
       "what the clibib audits of rounds 35 and 38 exist to make true, and its "
       "closing clause must stay FUTURE tense while no supplement is attached")
    # the named script must actually exist, or the promise has no referent, and it
    # must locate its own inputs relatively -- an absolute /Users/... path in the one
    # file the AI use statement names by function would deanonymize the submission
    # the moment the code is released.
    ck(os.path.exists("verify_bib.py"),
       "38i: verify_bib.py is gone; it is the citation-retrieval script the AI use "
       "statement promises to release, so its absence makes that sentence empty")
    if os.path.exists("verify_bib.py"):
        _vb38 = io.open("verify_bib.py", encoding="utf-8").read()
        ck("os.path.dirname(os.path.abspath(__file__))" in _vb38,
           "38i: verify_bib.py no longer resolves references.bib relative to its own "
           "location, so it cannot run outside this machine")
        ck("/Users/" not in _vb38,
           "38i: verify_bib.py has acquired an absolute /Users/... path; that is a "
           "double-blind leak in the one script the paper promises to release")

    # EVERY RELEASE CLAIM IN THE STATEMENTS PAGES IS FUTURE TENSE. The user caught
    # the AI use statement asserting the verification script "is released" and then,
    # reading p11, asked whether "What the release contains." is misleading. It is:
    # it presupposes the release exists. Three sentences were retensed together --
    # the p11 lede (pinned by 37h, moved there, see substitution (p)), the p10
    # Ethics sentence below, which was the STRONGEST instance because nothing nearby
    # corrected it and NO CHECK GUARDED IT AT ALL, and the deixis in the same p11
    # sentence. What is deliberately NOT retensed is "are committed as JSONL" at two
    # sites: committed is not released, those files really are in the repository,
    # and the claim built on them is only that the numbers recompute from it.
    # These are the checks to update, deliberately and with the reason, on the day a
    # release actually exists -- the same note 38i's sentence pin carries.
    ck("The study's per-rater CSVs will be released." in _aiuse38,
       "38i: the Ethics statement's per-rater-CSV sentence is gone or reworded; it "
       "must stay FUTURE tense while nothing is public, which is the defect the "
       "user caught in the AI use statement and this is the same sentence shape")
    ck("per-rater CSVs are released" not in _aiuse38,
       "38i: the Ethics statement has reverted to the present tense 'per-rater CSVs "
       "are released'; no release exists, there is no URL by the round-37 decision "
       "and no supplement by the round-38 one")
    ck("cited by name throughout the appendix" in _aiuse38,
       "38i: the availability sentence no longer says the 17 pre-registrations are "
       "cited by name throughout the appendix")
    ck("throughout this appendix" not in _aiuse38,
       "38i: main.tex says 'throughout this appendix' again; that sentence is in "
       "the Reproducibility statement, NOT in the appendix, so the deixis has no "
       "referent -- it is leftover from when the text lived in the appendix")

    # ---- 38h. THE SELF-REFERENCE, at its new fixed point. The count main.tex
    # advertises is this verifier's own final total, and this check is the last
    # one. Round 38's arithmetic, in full, because an advertised count that has
    # drifted from the harness is a false claim in the paper:
    #
    #   2,765  verify_r37.py's total at 8f18687
    #      +1  check 11's NEW_TAGS loop, which raises one check per appendix
    #          sentence naming a post-panel model: Part A's roster-pinning
    #          sentence names ministral-3:8b, and the loop asserts it does not
    #          claim the model was run. The parent harness therefore scores 2,766
    #          against this tree with no round-38 check added at all.
    #    +145  groups 38a-38i, measured from the harness's own output, not counted
    #          by hand: 38a's ledger, byte-identity and reduction pins, 38b's
    #          28-cell interval re-derivation and table-body identity, 38c's
    #          coding-sheet blind and uncoded pins, 38d's disclosure, 38e's
    #          declines, 38f's budget, 38g's em-dash partition, 38i's clibib
    #          re-audit pins on the two ICLR venue promotions, and this
    #          paragraph's own check. 37i's no-fund list is NET ZERO: it loses the
    #          blanket byte equality on introduction.tex and gains the stronger
    #          under-UNDO38 reduction in its place. The last SEVEN of the 145 are
    #          the release-tense correction, in two instalments, both opened by the
    #          user reading the statements pages rather than by any check:
    #            +3  38i's verify_bib.py pins (existence, relative-path
    #                resolution, no absolute /Users/ path), after the user caught
    #                the AI use statement claiming the script "is released" while
    #                nothing ships. 2,904 -> 2,907.
    #            +4  38i's four release-tense pins, after the user asked whether
    #                p11's "What the release contains." is misleading. It is -- it
    #                presupposes an extant release -- so the lede was retensed
    #                (substitution (p) moves 37h's four literals with it, which is
    #                why the lede itself costs no check), and with it the p10
    #                Ethics sentence "per-rater CSVs are released", which was the
    #                strongest instance precisely BECAUSE no check guarded it, and
    #                the "this appendix" deixis in a sentence that is not in the
    #                appendix. Two present + two absent pins. 2,907 -> 2,911.
    #          Note the asymmetry the two instalments share: retensing a sentence
    #          37h already pinned is free, and retensing one nothing pinned costs
    #          checks. That is the harness working, not a coincidence.
    #   =2,911
    ck("2{,}911-check verification harness" in _MT38,
       "38h: main.tex's advertised check count is not 2,911; re-pin it here, in "
       "37h and in main.tex together, and read the final line of "
       "verification/run.py's output for the true number")

'''

sub(r'''    # ---- report -----------------------------------------------------------
    if fails:''',
    GROUP38 + r'''    # ---- report -----------------------------------------------------------
    if fails:''',
    "GROUP 38")

# ============================================================== apply, in order
for old, new, label in subs:
    n = out.count(old)
    if n != 1:
        sys.exit("anchor %r matched %d times (need exactly 1):\n%r"
                 % (label, n, old[:140]))
    out = out.replace(old, new)
print("substitutions applied: %d" % len(subs))
for _o, _n, _l in subs:
    print("  %-42s %+6d chars" % (_l, len(_n) - len(_o)))

io.open(OUT, "w", encoding="utf-8").write(out)
print("\nwrote %s (%d lines, was %d)"
      % (OUT, out.count("\n") + 1, src.count("\n") + 1))
