#!/usr/bin/env python3
"""Build /tmp/verify_r33.py from /tmp/verify_r32.py.

Retains all 1735 round-32 checks. The 13 that round 33 deliberately changes are
UPDATED IN PLACE with the round-33 reason in a comment, never deleted, per the
standing Part C rule. Then appends GROUP 33.
"""
import io

SRC = "/tmp/verify_r32.py"
DST = "/tmp/verify_r33.py"
s = io.open(SRC, encoding="utf-8").read()
n = 0


def sub(old, new, label):
    global s, n
    assert s.count(old) == 1, (label, s.count(old))
    s = s.replace(old, new, 1)
    n += 1
    print(f"  patched: {label}")


# ---- P1. the round-33 edit ledger --------------------------------------------
sub('''R32_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r32_edits.json",
                                                 encoding="utf-8"))]
''',
    '''R32_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r32_edits.json",
                                                 encoding="utf-8"))]
# ROUND-33 EXTENSION: the 14 paragraph-level blocks round 33 applied on top of
# the round-32 commit (79d39b6). This was a presentation-only round answering a
# 6/10 Weak Accept whose follow-up argued clarity 7 -> 9 was reachable without
# new science: A1's four rung tags on §3's subsection titles (experiments-1/3/
# 4/5), A2's numbered step column in fig:ladder plus its caption's "run steps
# 1--5 bottom-up" instruction (methodology-2/3/4), A4's criteria-vs-requirements
# disambiguation (methodology-5), A5's "identification, not classification"
# anchor folded into two figure captions (introduction-1, experiments-2), and
# the five restatement compressions that funded them inside a 9-page limit at
# slack 0: the reviewer's own §18 ask to demote round 31's monotone-estimator
# clause (introduction-2, methodology-1) plus four conclusion/§3.5 cuts
# (conclusion-1, experiments-6). Generated by /tmp/gen_r33_edits.py, the same
# coalescing opcode walk that produced r29..r32_edits.json.
R33_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r33_edits.json",
                                                 encoding="utf-8"))]
''', "P1 R33_EDITS load")

# ---- P2. replay the round-33 blocks before the word-multiset comparison ------
sub('''    predicted = words(rebuilt)
    actual = words(cur_cat)''',
    '''    # ROUND-33 EXTENSION: replay the round-33 blocks on top of the rebuilt
    # round-32 baseline. Every round-33 block is in a BOLDED file -- the clarity
    # round touched no appendix and no related_work text -- so unlike rounds
    # 30-32 there is no side bag, and that absence is asserted rather than
    # assumed.
    for name, tag, old, new in R33_EDITS:
        ck(name in BOLDED,
           f"round-33 ledger entry {tag} names a non-main file ({name}); the "
           f"clarity round was main-text only")
        if name not in BOLDED:
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-33 edit does not apply once to the rebuilt "
           f"round-32 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    predicted = words(rebuilt)
    actual = words(cur_cat)''', "P2 R33 replay stage")

sub('''    ck(not lost, f"WORDS LOST that no enumerated round-23..32 edit accounts for: "
                 f"{dict(list(lost.items())[:12])}")
    ck(not gained, f"WORDS GAINED that no enumerated round-23..32 edit accounts "
                   f"for: {dict(list(gained.items())[:12])}")''',
    '''    ck(not lost, f"WORDS LOST that no enumerated round-23..33 edit accounts for: "
                 f"{dict(list(lost.items())[:12])}")
    ck(not gained, f"WORDS GAINED that no enumerated round-23..33 edit accounts "
                   f"for: {dict(list(gained.items())[:12])}")''',
    "P2b ledger message range")

# ---- P3. fig:dag's pinned diff gains A5's anchor -----------------------------
sub('''                ck(x == y.replace(
                       "not better data}---only \\\\textbf{criterion 4}, deception "
                       "varying at fixed elicitation, removes the elicitation "
                       "confound (Table",
                       "not better data} (Table")
                       .replace("not better data} (Table",
                                "not better data} (Appendix Table"),
                   "fig:dag differs from baseline by more than the round-28 "
                   "caption funding cut and round 29's Appendix-Table pointer")''',
    '''                # ROUND-33 SUBSTITUTION (A5, their clarity item #1): the anchor
                # "the problem is identification, not classification" is folded
                # into the caption's existing bold TITLE rather than appended as
                # a sentence -- measured, the same 58 characters cost 3 rulers in
                # §3.2's body and 0 here. Chained on so fig:dag's diff stays
                # pinned EXACTLY across four rounds of caption edits.
                ck(x == y.replace(
                       "not better data}---only \\\\textbf{criterion 4}, deception "
                       "varying at fixed elicitation, removes the elicitation "
                       "confound (Table",
                       "not better data} (Table")
                       .replace("not better data} (Table",
                                "not better data} (Appendix Table")
                       .replace("cannot attribute itself.}",
                                "cannot attribute itself: the problem is "
                                "identification, not classification.}"),
                   "fig:dag differs from baseline by more than the round-28 "
                   "caption funding cut, round 29's Appendix-Table pointer and "
                   "round 33's identification-not-classification anchor")''',
    "P3 fig:dag chain")

# ---- P4. fig:r1c_collapse's pinned diff gains the same anchor ----------------
sub('''                          .replace("\\\\textbf{EXP-R1c: the pre-registered collapse, "
                                   "on every target.}",
                                   "\\\\textbf{The pre-registered equalization "
                                   "collapse, on every target} (EXP-R1c)."),
                   "fig:r1c_collapse differs from baseline by more than the two "
                   "3B grouped-5-fold values (46.0 -> 36.0) and the round-28 "
                   "shaded-band caption cut")''',
    '''                          .replace("\\\\textbf{EXP-R1c: the pre-registered collapse, "
                                   "on every target.}",
                                   "\\\\textbf{The pre-registered equalization "
                                   "collapse, on every target} (EXP-R1c).")
                          # ROUND-33 SUBSTITUTION (A5): the anchor's second
                          # occurrence, at the caption's END, which measured 0
                          # rulers where the same text in §3.2's body cost 3.
                          .replace("grouped folds give 36.0\\\\%).}",
                                   "grouped folds give 36.0\\\\%). \\\\textbf{The "
                                   "problem is identification, not "
                                   "classification.}}"),
                   "fig:r1c_collapse differs from baseline by more than the two "
                   "3B grouped-5-fold values (46.0 -> 36.0), the round-28 "
                   "shaded-band caption cut and round 33's anchor")''',
    "P4 fig:r1c_collapse chain")

# ---- P5. 25g: §3.3's heading gains its rung tag ------------------------------
sub('''    ck("\\\\subsection{Q2: What Survives Is Reproducible from Surface Behavior and "
       "Model Knowledge}" in expt,
       "25g: the §3.3 heading is not the round-25 'Model Knowledge' wording "
       "behind its round-29 Q2 tag")''',
    '''    # ROUND-33 SUBSTITUTION (A1, their §25C): the heading gains a rung tag in
    # front of round 25's wording, exactly as round 29 put the Q-tag there. The
    # tags compose; neither replaces the other, and round 25's noun phrase is
    # still the tail of the heading.
    ck("\\\\subsection{Q2, Rung 2 to 3: What Survives Is Reproducible from Surface "
       "Behavior and Model Knowledge}" in expt,
       "25g: the §3.3 heading is not the round-25 'Model Knowledge' wording "
       "behind its round-29 Q2 tag and round-33 rung tag")''', "P5 check 25g")

# ---- P6. 29a: the heading list gains four rung tags --------------------------
sub('''    ck(heads29 == [
        "Q2: Why the Instructed Contrast Cannot Be Attributed",
        "Q2/Q3: An Audit Protocol for Behavioral Deception Benchmarks",
        "Experimental Setup",
        "Q1, then Q2: The Prior Detector Collapses Under Equalization "
        "(EXP-R1, EXP-R1b/R1c)",
        "Q2: What Survives Is Reproducible from Surface Behavior and Model "
        "Knowledge",
        "Q2: A Third Detector Paradigm, and Supporting Analyses",
        "Q3: Criterion 4 on Public Corpora, and on Materials Built for It "
        "(EXP-XA/XJ/XL, EXP-C4)",
    ], f"29a: the Q-tagged subsection headings changed: {heads29}")''',
    '''    # ROUND-33 SUBSTITUTION (A1, their §25C + clarity item #3): §3's four
    # subsections now also name the rung each one moves the evidence to, so the
    # table of contents reads as the ladder. §2's two headings and "Experimental
    # Setup" are unchanged -- §2 states the protocol rather than climbing it.
    ck(heads29 == [
        "Q2: Why the Instructed Contrast Cannot Be Attributed",
        "Q2/Q3: An Audit Protocol for Behavioral Deception Benchmarks",
        "Experimental Setup",
        "Q1, then Q2, Rung 1 to 2: The Prior Detector Collapses Under "
        "Equalization (EXP-R1, EXP-R1b/R1c)",
        "Q2, Rung 2 to 3: What Survives Is Reproducible from Surface Behavior "
        "and Model Knowledge",
        "Q2, Rung 2 to 3 Again: A Third Detector Paradigm, and Supporting "
        "Analyses",
        "Q3, Rung 3 to 4: Criterion 4 on Public Corpora, and on Materials Built "
        "for It (EXP-XA/XJ/XL, EXP-C4)",
    ], f"29a: the Q-tagged subsection headings changed: {heads29}")''',
    "P6 check 29a")

# ---- P7. 31d: the monotone clause is the round's funding, at both sites ------
sub('''    ck("\\\\textbf{Nor is accuracy a monotone estimator of $\\\\tau_E$\'s magnitude}"
       in meth31,
       "31d: methodology.tex lost the monotonicity caveat their §21.4 asked for")''',
    '''    # ROUND-33 SUBSTITUTION (funding, and a reviewer-vs-reviewer reversal):
    # round 31 ADDED this clause for a prior reviewer's §21.4; the round-33
    # reviewer's §18 asked to demote it as a distraction ("a reviewer might
    # spend time asking why are you introducing tau_E if accuracy isn't
    # estimating it"), and the user authorized the cut at both sites to fund the
    # clarity edits. The check is UPDATED, not deleted: it now pins the ABSENCE
    # of the clause and, immediately below, the SUBSTANCE that had to survive --
    # what tau_E is, and the abstract's own disclaimer, which was untouched.
    ck("monotone" not in meth31,
       "31d: the monotone-estimator clause is back in methodology.tex; round "
       "33's funding decision, on their §18, was to drop it at both sites")''',
    "P7a check 31d methodology")

sub('''    ck("their accuracy is not even a \\\\emph{monotone} estimator of its "
       "magnitude" in intro31,
       "31d: the introduction's contribution 1 lost the monotonicity clause")''',
    '''    ck("monotone" not in intro31,
       "31d: the monotone clause is back in the introduction's contribution 1; "
       "see the round-33 note above")
    ck("the \\\\emph{instruction}'s effect, while deception-detection claims"
       in intro31,
       "31d: dropping the monotone clause also dropped contribution 1's "
       "estimand contrast, which was the half round 31 was actually asked for")''',
    "P7b check 31d introduction")

# ---- P8. 31g: the ladder's operational cells gain step numbers ---------------
sub('''    for _op in ["{$\\\\mathrm{do}(D)$: $D$ set or randomised}",
                "{\\\\textbf{criterion 4}: fix $E$, grade $D$ off-label}",
                "{\\\\textbf{criteria 2--3}: re-extract cross-family}",
                "{\\\\textbf{criterion 1}: one neutral prompt}",
                "{the benchmark as published}"]:''',
    '''    # ROUND-33 SUBSTITUTION (A2, their §25B): they asked for the audit
    # "executable in ~10 lines". The column already WAS the step list, so each
    # cell gained its step number and the caption gained the instruction to run
    # them bottom-up. The header stays "Reached by: the operational test" --
    # renaming it to "Step" would desynchronize 31h's appendix sentence, which
    # pins that exact string, so the numbers went into the cells instead.
    for _op in ["{\\\\textbf{5.} $\\\\mathrm{do}(D)$: $D$ set or randomised}",
                "{\\\\textbf{4. criterion 4}: fix $E$, grade $D$ off-label}",
                "{\\\\textbf{3. criteria 2--3}: re-extract cross-family}",
                "{\\\\textbf{2. criterion 1}: one neutral prompt}",
                "{\\\\textbf{1.} the benchmark as published}"]:''',
    "P8 check 31g ladder cells")

# ---- P9. GROUP 33 ------------------------------------------------------------
GROUP33 = r'''
    # ==== GROUP 33 -- the clarity round: rung tags, an executable ladder, and
    # the two numbering schemes named apart =================================
    # Round 33 answers a 6/10 Weak Accept (confidence 0.86) whose follow-up
    # argued clarity 7 -> 9 was reachable without new science. It is
    # presentation-only: no experiment, no pre-registration, no number changed.
    # Its defining constraint was budget -- 9 pages at slack 0, where an add
    # upstream of the spill costs ~1:1 and an upstream CUT refunds 0 -- so two of
    # the seven planned items were withdrawn by MEASUREMENT, and this group pins
    # what landed AND what was deliberately not bought, so a later round does not
    # assume otherwise.
    intro33, meth33, expt33, concl33 = intro, meth, expt, concl

    # ---- 33a. A1, their §25C: every §3 subsection names the rung it moves the
    # evidence to, composed with round 29's Q-tag rather than replacing it.
    for _t33 in ["Rung 1 to 2", "Rung 2 to 3", "Rung 2 to 3 Again",
                 "Rung 3 to 4"]:
        ck(_t33 in expt33, f"33a: §3 lost the rung tag {_t33!r}")
    _heads33 = re.findall(r"\\subsection\{([^}]*)\}", expt33)
    ck(len([h for h in _heads33 if "Rung" in h]) == 4,
       f"33a: {len([h for h in _heads33 if 'Rung' in h])} of §3's subsections "
       f"carry a rung tag, expected 4 ('Experimental Setup' correctly does not)")
    for _h33 in _heads33:
        if "Rung" in _h33:
            ck(re.match(r"Q[123]", _h33),
               f"33a: {_h33[:44]!r} carries a rung tag but lost its round-29 "
               f"Q-tag -- the two tags compose, neither replaces the other")
    # ASCII, not math: $\to$ inside \subsection makes hyperref emit "token not
    # allowed in a PDF string", so the tags read "Rung 1 to 2".
    ck("Rung 1 $\\to$ 2" not in expt33 and "Rung 2 $\\to$ 3" not in expt33,
       "33a: a rung tag uses math inside a sectioning command, which corrupts "
       "the PDF bookmark string")
    # the tags must agree with the ladder they point at: §3.2 climbs to rung 2,
    # §3.3/§3.4 to rung 3, §3.5 to rung 4, and NOTHING claims rung 5.
    ck("Rung 4 to 5" not in expt33 and "Rung 5" not in expt33,
       "33a: a §3 heading claims rung 5, which no design audited here reaches")

    # ---- 33b. A2, their §25B: the ladder's middle column is numbered, so the
    # figure reads bottom-up as steps 1--5 and IS the audit algorithm they asked
    # to see. No new object: the column already existed (31g); only its cells
    # gained numbers and the caption gained the instruction to run them.
    _lad33 = meth33[meth33.index("\\newcommand{\\rungrow}"):]
    _lad33 = _lad33[:_lad33.index("\\end{tikzpicture}")]
    for _st33 in ["{\\textbf{5.} $\\mathrm{do}(D)$: $D$ set or randomised}",
                  "{\\textbf{4. criterion 4}: fix $E$, grade $D$ off-label}",
                  "{\\textbf{3. criteria 2--3}: re-extract cross-family}",
                  "{\\textbf{2. criterion 1}: one neutral prompt}",
                  "{\\textbf{1.} the benchmark as published}"]:
        ck(_st33 in _lad33,
           f"33b: the ladder's operational column lost numbered step {_st33!r}")
    ck("\\textbf{The middle column is the audit}: run steps 1--5 bottom-up and "
       "report the highest rung reached." in meth33,
       "33b: fig:ladder's caption no longer tells the reader that the middle "
       "column is the executable protocol, which is all their §25B asked for")
    ck("{Reached by: the operational test}" in _lad33,
       "33b: the ladder's column header changed, which breaks 31h's appendix "
       "sentence pinning that exact string")
    # the caption sentence A2 displaced said the same thing non-operationally
    ck("Each control rules out one alternative explanation" not in meth33,
       "33b: fig:ladder's caption kept the vague sentence the step instruction "
       "replaced, so the caption now says it twice")
    # five steps, five rungs: the numbering must not drift from the rung labels
    for _n33 in "12345":
        ck(_lad33.count("\\textbf{" + _n33 + ".") >= 1,
           f"33b: no ladder cell carries step number {_n33}")

    # ---- 33c. A4, the defect the review itself DEMONSTRATES. Their §14 mapped
    # "C5 -> detector reading its own annotation/label mechanism", conflating the
    # paper's two disjoint five-item schemes: criterion 5 is cross-target
    # transfer, while annotation leakage and circularity are requirements (iv)
    # and (v). A careful reviewer made that slip at the one paragraph where both
    # schemes appear within a few clauses, which is where the gloss now sits.
    ck("\\textbf{Criteria 1--5 and requirements~(i)--(v) are different lists}: "
       "the criteria are the audit's controls, (i)--(v) operationalize "
       "criterion~4." in meth33,
       "33c: §2.2 lost the clause that tells the reader the two numbering "
       "schemes are not the same list -- the one defect this review proves")
    _div33 = meth33[meth33.index("\\paragraph{How the criteria divide"):]
    _div33 = _div33[:_div33.index("\\noindent\\fbox")]
    ck("are different lists" in _div33,
       "33c: the disambiguation left the A/B/C paragraph, the one place the two "
       "schemes collide within a few clauses")
    ck("criterion~5 is \\emph{robustness}" in _div33,
       "33c: the paragraph lost round 32's criterion-5 reading, which is the "
       "half of the correction their §14 got wrong")
    # and the correct mapping still stands where (iv) and (v) are earned
    ck("\\textbf{annotation-channel leakage}, whence~(iv)" in expt33,
       "33c: §3.5 no longer earns (iv) at the annotation-leakage finding, so "
       "the reviewer's slip has nothing to be corrected against")
    ck("\\textbf{construct recovery}, whence~(v)" in expt33,
       "33c: §3.5 no longer earns (v) at the construct-recovery finding")
    ck("\\textbf{Criterion~5 (transfer) is exploratory}" in expt33,
       "33c: §3.5 no longer says criterion 5 is transfer, which is the fact "
       "their §14 mis-stated")

    # ---- 33d. A5, their clarity item #1: one short repeatable anchor. Placed
    # in two figure CAPTIONS, not in body prose: measured, the same 58 characters
    # cost 3 rulers inside §3.2's body and 0 at a caption's end.
    for _f33, _t33 in [("introduction.tex", intro33), ("experiments.tex", expt33)]:
        ck(_t33.count("the problem is identification, not classification") == 1
           or _t33.count("The problem is identification, not classification") == 1,
           f"33d: {_f33} does not carry the round-33 anchor exactly once")
    ck("\\textbf{Why instructed-roleplay accuracy cannot attribute itself: the "
       "problem is identification, not classification.}" in intro33,
       "33d: fig:dag's caption title no longer carries the anchor -- it was "
       "folded into the existing bold title precisely so it cost nothing")
    ck("\\textbf{The problem is identification, not classification.}}" in expt33,
       "33d: fig:r1c_collapse's caption no longer ends on the anchor")
    # the anchor restates the paper's own framing, so that framing must remain
    ck("an \\emph{identification} claim about a class of benchmarks, not a "
       "capability claim about detectors" in intro33,
       "33d: the Q-box lost the sentence the anchor compresses")

    # ---- 33e. the funding, and the reviewer-vs-reviewer reversal it records.
    # Their §18 asked us to demote round 31 A4's monotone-estimator clause;
    # round 31 had ADDED it for a prior reviewer's §21.4. The user authorized the
    # cut. 31d above is updated, not deleted, and the SUBSTANCE survives here.
    ck("monotone" not in intro33 and "monotone" not in meth33,
       "33e: the monotone-estimator clause is back in the main text")
    ck("$\\tau_E$ is the estimand that separation belongs to, not a quantity "
       "the score measures" in meth33,
       "33e: dropping the monotone clause also dropped what tau_E IS, which "
       "was the half round 31 was actually asked for")
    ck("not a magnitude accuracy estimates" in absr,
       "33e: the abstract's tau_E disclaimer went with it -- the 403-word "
       "ratchet (29z) was explicitly not to be touched this round")

    # ---- 33f. what the five funding cuts removed: RESTATEMENTS ONLY. Every
    # fact each one carried still stands at its canonical site.
    for _tag33, _s33, _t33, _where33 in [
            ("the factorial's sign flip", "changes sign", expt33, "§3.4"),
            ("the 28 pinned corpora", "\\textbf{28} pinned public corpora",
             meth33, "§2.1's ECCP paragraph"),
            ("the four non-deception designs", "four outside deception",
             intro33, "contribution 2"),
            ("EXP-AD's probe swap", "rank~1 on none of the five shared targets",
             expt33, "§3.5's EXP-AD narrative"),
            ("the criterion-4 effect sizes", "0.650--0.903", expt33,
             "tab:external_audit's last row"),
            ("the identification-failure framing",
             "identify the \\emph{instruction}'s effect and cannot bound",
             concl33, "the conclusion's claim (1)")]:
        ck(_s33 in _t33,
           f"33f: the round-33 cut of {_tag33} also removed the fact itself, "
           f"which had to stay at {_where33}")
    ck("(EXP-AD)" in concl33,
       "33f: the conclusion's claim (5) lost its EXP-AD pointer along with the "
       "gloss, leaving the claim with no experiment attached")
    # this one was CUT, measured at 0 rulers, and RESTORED rather than spent for
    # nothing -- the rule being that content is never traded for zero budget.
    ck(concl33.count("that deception is undetectable") == 1,
       "33f: the conclusion's undetectability sentence is gone; it freed 0 "
       "rulers when cut, so it was restored")
    # §3.5 keeps a reference to its own table after the effect-size pointer went
    ck("Table~\\ref{tab:external_audit}" in
       expt33[expt33.index("\\subsection{Q3, Rung 3 to 4"):],
       "33f: §3.5 no longer references tab:external_audit at all, so the table "
       "floats on p8 with no citation in the section that owns it")

    # ---- 33g. WITHDRAWN BY MEASUREMENT, pinned so a later round does not
    # assume they landed. A3 (name what each criterion rules out, in the main
    # text) cost 1--3 rulers at every site measured -- 3 in fig:ladder's caption,
    # 3 in tab:external_audit's, 2 in §2.2's body -- and after the authorized
    # funding source measured 0, there was no unpinned funding left. A6 (the
    # compact novelty ledger, their "highest priority") cost 5--8. Both objects
    # already exist in the APPENDIX, which is where the reviewer found them, and
    # saying so is the honest core of the reply rather than a claim to have
    # moved them.
    ck("Rules out \\emph{instruction asymmetry}" in app,
       "33g: A3's content is no longer in tab:criteria either, so the paper "
       "states the per-criterion alternatives nowhere")
    ck("Rules out an \\emph{evaluator artifact}" in app,
       "33g: tab:criteria lost the criterion-2 alternative")
    ck("\\textbf{The five are not claimed to characterize every valid deception "
       "benchmark}---they rule out specific alternative explanations." in meth33,
       "33g: §2.2's generic 'specific alternative explanations' was edited, but "
       "A3 was withdrawn for budget -- this sentence must read exactly as round "
       "32 left it")
    # A6 was not bought as a float, and no sixth main-text float appeared
    ck(sum(_t33.count("\\begin{table}") + _t33.count("\\begin{figure}")
           for _t33 in [absr, intro33, meth33, expt33, read("discussion.tex"),
                        concl33]) == 5,
       "33g: the main text float count left 5 (fig:dag, tab:claim_ledger, "
       "fig:ladder, fig:r1c_collapse, tab:external_audit) -- A6 was withdrawn "
       "for budget, so a sixth float means one was added without funding")
    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "33g: the three structured caution boxes must survive a clarity round "
       "unchanged; every prior reviewer named them a strength")

    # ---- 33h. THE HARNESS FLAW THIS ROUND FOUND, now pinned. Both budget
    # arbiters -- /tmp/pos28.py above and the ruler-485 grep -- PASSED while the
    # conclusion's last two lines sat on p10. They read the last ruler printed
    # BEFORE the anchor, so a closing sentence that WRAPS is measured one line
    # short and its continuation is invisible. The robust test is what is on p10.
    _p9_33 = subprocess.run(["pdftotext", "-layout", "-f", "9", "-l", "9",
                             "main.pdf", "-"], capture_output=True,
                            text=True).stdout
    _p10_33 = subprocess.run(["pdftotext", "-layout", "-f", "10", "-l", "10",
                              "main.pdf", "-"], capture_output=True,
                             text=True).stdout
    _flat9 = re.sub(r"\s+", " ", _p9_33)
    _flat10 = re.sub(r"\s+", " ", _p10_33)
    ck("magnitude we measure only" in _flat9,
       "33h: the conclusion's closing sentence is not on p9 (whitespace-"
       "normalized, because the anchor straddles a pdftotext line break)")
    ck("magnitude we measure only" not in _flat10,
       "33h: the conclusion's closing sentence is on p10 -- the spill both "
       "older arbiters are blind to")
    ck("THICS STATEMENT" in _flat10[:300],
       f"33h: p10 does not open on the Ethics Statement, so main text spilled "
       f"past the 9-page limit: {_flat10[:200]!r}")
    # p9's last ruler is the number the two older arbiters report; keep it
    # pinned too, so a future round sees BOTH signals and not just the weak one.
    _r9_33 = re.findall(r"^ *(\d{3})", _p9_33, re.M)
    ck(_r9_33 and _r9_33[-1] == "485",
       f"33h: p9's last margin ruler is {_r9_33[-1] if _r9_33 else None}, not "
       f"485; the 9-page main text is no longer at the committed baseline")
'''

sub("""
    # ---- report -----------------------------------------------------------
    if fails:""", GROUP33 + """
    # ---- report -----------------------------------------------------------
    if fails:""", "P9 GROUP 33")

io.open(DST, "w", encoding="utf-8").write(s)
print(f"wrote {DST} ({n} patches, {len(s)} chars)")
