#!/usr/bin/env python3
"""Build /tmp/verify_r39.py from /tmp/verify_r38.py.

Round 39 audits the NeurIPS 2026 main-track review (Decision: Reject; metareview +
citation-checker report + three reviewers) against the LIVE tree and implements the
items that were still open. The reviewed PDF was dated from git log before anything
was read into it: `anthropic2025claude` lived in references.bib from 3205a44
(2026-04-29) to 6148062 (2026-08-15) and the HackAPrompt/Perez conflation was
undone in the same commit, so the reviewed build is the ~May 2026 NeurIPS
submission, about twenty rounds behind this one. Same paper, so every item is
measurable here; most were already closed.

  Part A  EXP-BF, the benign false-positive rate of the parameter-free rule, which
          reviewer 1 named as their one main missing piece. The experiment had
          already been run (50 benign prompts per target, no false claim and no
          knowledge conflict in the set) and had never reached the paper. It could
          not be pasted in: the July 2026 collection recorded TIMEOUTS as ordinary
          non-firing responses (68 of 300 records are the client's timeout string)
          and stored responses TRUNCATED at 500 characters (135 of the 232
          non-timeout records), and its scoring used a PRIVATE 4-pattern regex list
          rather than the paper's 14. So the responses were re-collected on the five
          locally available targets -- exactly EXP-C4's roster -- by
          experiments/run_benign_fpr2.py, which stores responses whole, refuses to
          start unless every exact tag is installed, records an unrecoverable
          timeout as an error excluded from the denominator, and DOES NO SCORING.
          experiments/analyze_benign_fpr.py imports hedging_baseline.REFUSAL_PATTERNS
          and aborts unless the import is exactly 14 patterns long. New appendix
          subsection app:benign_fpr plus its roadmap reference.

  Part B  the four clarity items three reviewers independently named, all cheap:
          prompt equalization defined operationally at first use in the BODY
          (previously stated only inside a figure cell); the reimplementation's
          bank-width concession lifted out of the appendix into experiments.tex;
          the ADAGE acronym REMOVED from the main text rather than expanded there;
          and \\paragraph{Relation to prior work.} renamed to \\paragraph{Related
          work.}, the heading reviewers searched for and did not find.

Under the standing rule ALL checks the round-38 harness scores against this tree
are RETAINED. The ones this round deliberately changes are UPDATED, each with the
round-39 reason in a comment, never deleted. Every substitution's `old` must occur
EXACTLY ONCE in the source or nothing is written -- that assertion is what enforces
the read-back rule, and it is why a paraphrased anchor fails loudly instead of
landing in the wrong place.

THE STRUCTURAL ADDITION is UNDO39, the exact analogue of UNDO38. The round-39
ledger is generated by gen_r39_edits.py as a diff of UNCONVERT(HEAD) against
UNCONVERT(tree), so it lives in PRE-round-36 punctuation, and therefore:

  * a forward R39 stage appends to 13g's replay after the R38 stage, because
    `rebuilt` is in pre-round-36 punctuation at that point; and
  * every historical pin that reads the live tree becomes
    UNDO37(UNDO38(UNDO39(UNCONVERT(text, name), name), name), name), which by
    construction restores UNCONVERT(ea6faf9) byte-for-byte -- so rounds 30-35's
    pins pass for the same reason they passed at that commit, not because they were
    weakened. STRIP NEWEST FIRST: round 39, then 38, then 37, the exact inverse of
    the forward replay.

WHAT IS DIFFERENT FROM ROUND 38's CALL-SITE SET. Round 38 touched appendix.tex,
introduction.tex and related_work.tex. Round 39 touches appendix.tex,
experiments.tex and introduction.tex -- related_work.tex is NOT touched and
experiments.tex is, so UNDO39's call sites are not a copy of UNDO38's. Every site
that reads experiments.tex or introduction.tex under an UNDO chain has to be
wrapped, and 39a measures the ledger's file set against that claim.
"""
import io
import json
import sys

D = ("/Users/mediratta/code/paper_writing/AI-Researcher-align/output/"
     "adaptive_lie_detector_paper")
SRC = "/tmp/verify_r38.py"
OUT = "/tmp/verify_r39.py"

src = io.open(SRC, encoding="utf-8").read()
out = src

subs = []


def sub(old, new, label):
    subs.append((old, new, label))


# =========================================================== (a) UNDO39 itself
sub(r'''    for _o, _n in reversed(R38_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text
''',
    r'''    for _o, _n in reversed(R38_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text


# ROUND-39: the round that audits the NeurIPS 2026 main-track reject against the
# live tree. Its edits are in three files: appendix.tex (EXP-BF, the benign
# false-positive rate of the parameter-free rule, as a new subsection after
# app:regex_patterns, plus its \ref in bucket 3 of the appendix roadmap),
# experiments.tex (three main-text clarity edits: prompt equalization defined
# operationally at first use in the body, the reimplementation's bank-width
# concession lifted out of the appendix, and the ADAGE acronym removed from the main
# text) and introduction.tex (\paragraph{Relation to prior work.} ->
# \paragraph{Related work.}). related_work.tex is NOT touched this round, and
# experiments.tex is, so the wrapped call-site set differs from round 38's and 39a
# measures it. The ledger is generated by gen_r39_edits.py as a diff of
# UNCONVERT(HEAD) against UNCONVERT(tree), so it is expressed in PRE-round-36
# punctuation -- which is what lets 13g replay it forward after the R38 stage, and
# what makes an `old` overlapping a round-36, -37 or -38 post-image structurally
# impossible (asserted in 39a anyway).
R39_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r39_edits.json",
                                                 encoding="utf-8"))]
R39_BY_FILE = {}
for _n39, _t39, _o39, _x39 in R39_EDITS:
    R39_BY_FILE.setdefault(_n39, []).append((_o39, _x39))


def UNDO39(text, name):
    """Invert round 39 on already-un-converted text: UNDO39(UNCONVERT(live)).

    Composed as UNDO37(UNDO38(UNDO39(UNCONVERT(live)))) at every historical call
    site: strip the NEWEST round first, which is the exact inverse of the forward
    replay order, and the composition restores UNCONVERT(ea6faf9). Keyed by FILE
    NAME, so it inverts whatever the ledger names and is a no-op on every file the
    round did not touch -- which is why moving the round's footprint from
    appendix/introduction/related_work to appendix/experiments/introduction is a
    change to the CALL SITES, never to this function. gen_r39_edits.py refuses to
    write a ledger naming any other file, so the set of wrapped call sites is
    checkable against the ledger, and 39a measures it.
    """
    for _o, _n in reversed(R39_BY_FILE.get(name, [])):
        text = text.replace(_n, _o)
    return text
''',
    "39-a: UNDO39, the ledger loader and the round's footprint comment")

# ============================ (b) UNDO39 at the historical UNDO37(UNDO38(...)) sites
# Every one of these restores UNCONVERT(ea6faf9) for a rounds-30..35 pin. Round 39
# edits appendix.tex, so each appendix site must strip round 39 before round 38.
sub(r'''    appx_led = UNDO37(UNDO38(UNCONVERT(read("appendix.tex"), "appendix"),
                             "appendix"), "appendix")''',
    r'''    # ROUND-39: strip round 39 first (see UNDO39), then 38, then 37 -- newest
    # first, the inverse of 13g's forward replay.
    appx_led = UNDO37(UNDO38(UNDO39(UNCONVERT(read("appendix.tex"), "appendix"),
                                    "appendix"), "appendix"), "appendix")''',
    "39-b1: the round-30 appendix ledger pin, under UNDO39")

# The appendix sub-expression is BYTE-IDENTICAL in all four of these dicts, so
# each `old` carries its own variable name AND its full closing lines. An anchor
# that stopped at the opening paren would insert UNDO39( without its matching
# argument and close-paren: the first draft of 39-b2..b5 did exactly that and the
# generated file failed to parse, which is why the whole expression is replaced.
sub(r'''    r31_side = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),
                                            "appendix"), "appendix"),
                                   "appendix"),''',
    r'''    # ROUND-39: strip round 39 innermost on appendix.tex (see UNDO39), then
    # 38, then 37 -- newest first, the inverse of 13g's forward replay.
    r31_side = {"appendix": UNDO37(UNDO38(UNDO39(
                                   UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"), "appendix"), "appendix"),''',
    "39-b2: the round-31 bag, appendix side")

sub(r'''    r32_side = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),
                                            "appendix"), "appendix"),
                                   "appendix")}''',
    r'''    # ROUND-39: strip round 39 innermost on appendix.tex (see UNDO39).
    r32_side = {"appendix": UNDO37(UNDO38(UNDO39(
                                   UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"), "appendix"), "appendix")}''',
    "39-b3: the round-32 bag, appendix side")

sub(r'''    r34_side = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),
                                            "appendix"), "appendix"),
                                   "appendix")}''',
    r'''    # ROUND-39: strip round 39 innermost on appendix.tex (see UNDO39).
    r34_side = {"appendix": UNDO37(UNDO38(UNDO39(
                                   UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"), "appendix"), "appendix")}''',
    "39-b4: the round-34 bag, appendix side")

sub(r'''    r35_side = {"appendix": UNDO37(UNDO38(UNCONVERT(read("appendix.tex"),
                                            "appendix"), "appendix"),
                                   "appendix"),''',
    r'''    # ROUND-39: strip round 39 innermost on appendix.tex (see UNDO39).
    r35_side = {"appendix": UNDO37(UNDO38(UNDO39(
                                   UNCONVERT(read("appendix.tex"), "appendix"),
                                   "appendix"), "appendix"), "appendix"),''',
    "39-b5: the round-35 bag, appendix side")

sub(r'''    _app34_r34 = UNDO37(UNDO38(UNCONVERT(app34, "appendix"), "appendix"),
                        "appendix")''',
    r'''    # ROUND-39: strip round 39 first (see UNDO39); the composition is
    # newest-first and restores UNCONVERT(ea6faf9).
    _app34_r34 = UNDO37(UNDO38(UNDO39(UNCONVERT(app34, "appendix"), "appendix"),
                               "appendix"), "appendix")''',
    "39-b6: 34a's under-UNDO reduction of the appendix")

# ======================= (c) 35f's two byte-identity asserts, under UNDO39
# 35f loops over abstract, introduction, experiments, discussion, appendix and
# related_work. Round 39 edits THREE of that loop's files (appendix, experiments,
# introduction), so without UNDO39 the check would fail -- and it is a retained
# check whose claim ("nothing but round 35's two renames and two Gemma cites
# touched these files, relative to c9718cf") is still exactly true once round 39
# is stripped. UNDO39 is keyed by file name, so one wrap covers all three and is a
# no-op on the other three.
sub(r'''        ck(UNDO37(UNDO38(UNCONVERT(read(_f35 + ".tex"), _f35), _f35), _f35)
           == _rename35(_was35),''',
    r'''        # ROUND-39: un-do round 39 innermost (see UNDO39). The round edits
        # appendix.tex, experiments.tex and introduction.tex, three of this loop's
        # six files; UNDO37(UNDO38(UNDO39(UNCONVERT(.)))) is by construction
        # UNCONVERT(ea6faf9), so round 35's claim stays byte-exact rather than
        # being restated with a carve-out for the new subsection and the three
        # clarity clauses.
        ck(UNDO37(UNDO38(UNDO39(UNCONVERT(read(_f35 + ".tex"), _f35), _f35),
                         _f35), _f35)
           == _rename35(_was35),''',
    "39-c1: 35f's rename-tolerant byte identity, under UNDO39")

sub(r'''            ck(UNDO37(UNDO38(UNCONVERT(read(_f35 + ".tex"), _f35), _f35), _f35)
               == _was35,''',
    r'''            # ROUND-39: and un-do round 39 (see UNDO39), a no-op on these two
            # files -- neither appears in the round-39 ledger -- applied so that
            # being a no-op is a consequence of the assertion, not a comment.
            ck(UNDO37(UNDO38(UNDO39(UNCONVERT(read(_f35 + ".tex"), _f35), _f35),
                             _f35), _f35)
               == _was35,''',
    "39-c2: 35f's two strictly-byte-identical files, under UNDO39")

# ============================== (d) 37b's round-trip to the round-37 commit
sub(r'''        ck(UNDO37(UNDO38(UNCONVERT(read(_f37b + ".tex"), _f37b), _f37b), _f37b)
           == UNCONVERT(_was37b, _f37b),''',
    r'''        # ROUND-39: strip round 39 first (see UNDO39), so this check asserts
        # exactly what it asserted at the parent commit -- that the tree reduces
        # to ea6faf9 under the enumerated ledgers and nothing else. An unledgered
        # round-39 edit now fails HERE as well as at 39a.
        ck(UNDO37(UNDO38(UNDO39(UNCONVERT(read(_f37b + ".tex"), _f37b), _f37b),
                         _f37b), _f37b)
           == UNCONVERT(_was37b, _f37b),''',
    "39-d: 37b's per-file round-trip, under UNDO39")

# ======================= (e) 37i's no-fund roster, minus experiments.tex
# 37i asserted four files byte-identical to ea6faf9. Round 39 edits experiments.tex
# -- three clarity clauses the NeurIPS main-track reviewers named -- so the RAW
# equality for that file is no longer true. It is NOT dropped: exactly as round 38
# did for introduction.tex, the file moves out of the raw list and into an
# under-UNDO39 equality below, which is strictly the same assertion with this
# round's own ledger accounted for. abstract.tex, discussion.tex and conclusion.tex
# stay RAW: they are standing no-fund sites and round 39 funded nothing from them.
sub(r'''    for _f37i in ["abstract", "experiments", "discussion", "conclusion"]:''',
    r'''    # ROUND-39 SUBSTITUTION: experiments.tex leaves the RAW list (round 39 edits
    # it) and is re-asserted under UNDO39 below. The abstract, discussion.tex and
    # conclusion.tex stay raw, which is the part of 37i that must not soften.
    for _f37i in ["abstract", "discussion", "conclusion"]:''',
    "39-e1: 37i's raw no-fund roster, experiments.tex moved out")

sub(r'''    _w37j = _git37("sections/introduction.tex")
    ck(_w37j is not None, "37i: cannot read the parent's introduction.tex")
    if _w37j is not None:
        ck(UNDO38(UNCONVERT(read("introduction.tex"), "introduction"),
                  "introduction") == UNCONVERT(_w37j, "introduction"),
           f"37i: introduction.tex does not reduce to {_PARENT37} once round 38's "
           f"ledger is un-done; round 37 funded nothing from it and round 38 touches "
           f"it only to rename two citation keys the clibib re-audit corrected")''',
    r'''    _w37j = _git37("sections/introduction.tex")
    ck(_w37j is not None, "37i: cannot read the parent's introduction.tex")
    if _w37j is not None:
        # ROUND-39: strip round 39 first (see UNDO39). Round 39 renames the
        # related-work paragraph heading in this file, which is character-negative
        # and therefore free; the equality is preserved with the round accounted
        # for rather than restated more loosely.
        ck(UNDO38(UNDO39(UNCONVERT(read("introduction.tex"), "introduction"),
                         "introduction"), "introduction")
           == UNCONVERT(_w37j, "introduction"),
           f"37i: introduction.tex does not reduce to {_PARENT37} once rounds 38 "
           f"and 39's ledgers are un-done; round 37 funded nothing from it, round 38 "
           f"touches it only to rename two citation keys the clibib re-audit "
           f"corrected, and round 39 only to rename one paragraph heading")
    # ROUND-39 ADDITION: experiments.tex, moved out of the raw list above and
    # checked under UNDO39 here. Round 39's three clarity edits are the ONLY
    # licensed difference: the operational definition of prompt equalization at
    # first use in the body, the bank-width concession lifted out of the appendix,
    # and the removal of the ADAGE acronym from the main text.
    _w37k = _git37("sections/experiments.tex")
    ck(_w37k is not None, "37i: cannot read the parent's experiments.tex")
    if _w37k is not None:
        ck(UNDO39(UNCONVERT(read("experiments.tex"), "experiments"),
                  "experiments") == UNCONVERT(_w37k, "experiments"),
           f"37i: experiments.tex does not reduce to {_PARENT37} once round 39's "
           f"ledger is un-done; rounds 37 and 38 funded nothing from it and round "
           f"39 touches it for the three named clarity clauses only")''',
    "39-e2: 37i's introduction equality under UNDO39, plus experiments.tex")

# ===================== (f) 38a's per-file round-trip to the round-38 parent
sub(r'''            ck(UNDO38(UNCONVERT(read(_f38b + ".tex"), _f38b), _f38b)
               == UNCONVERT(_was38b, _f38b),''',
    r'''            # ROUND-39: strip round 39 innermost (see UNDO39). It is a no-op on
            # related_work.tex, which round 39 does not touch, and strips the
            # paragraph rename from introduction.tex.
            ck(UNDO38(UNDO39(UNCONVERT(read(_f38b + ".tex"), _f38b), _f38b),
                      _f38b) == UNCONVERT(_was38b, _f38b),''',
    "39-f: 38a's round-trip to the round-37 commit, under UNDO39")

# ========================= (g) 13g's forward R39 replay stage, after R38's
sub(r'''        ck(rebuilt.count(old) == 1,
           f"enumerated round-38 edit does not apply once to the rebuilt "
           f"round-37 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
''',
    r'''        ck(rebuilt.count(old) == 1,
           f"enumerated round-38 edit does not apply once to the rebuilt "
           f"round-37 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    # ---- ROUND-39 STAGE, appended for the same reason the R38 stage was: the
    # round-39 ledger is generated from UNCONVERT(HEAD) against UNCONVERT(tree),
    # i.e. in the same pre-round-36 punctuation `rebuilt` is already in and on top
    # of the state the R38 stage just produced, so it replays directly. 39a asserts
    # that no round-39 pre-image lies inside a round-36, -37 or -38 post-image,
    # which is the hazard that would otherwise couple the ledgers.
    # ONE non-BOLDED file this round, so one side-bag entry: appendix.tex (EXP-BF
    # and its roadmap reference). experiments.tex and introduction.tex are BOLDED,
    # so their pairs replay into `rebuilt` and the word ledger closes on them.
    # related_work.tex is NOT touched this round, which is why it has no entry --
    # 39a asserts the ledger names exactly appendix, experiments and introduction.
    r39_side = {"appendix": UNCONVERT(read("appendix.tex"), "appendix")}
    for name, tag, old, new in R39_EDITS:
        if name not in BOLDED:
            ck(name in r39_side,
               f"round-39 ledger entry {tag} names an unknown non-main file: "
               f"{name}")
            if name not in r39_side:
                continue
            side = r39_side[name]
            ck(side.count(new) >= 1,
               f"round-39 {name} edit {tag} is absent from {name}.tex: "
               f"{new[:80]!r}")
            if len(new) >= 40:
                ck(side.count(new) == 1,
                   f"round-39 {name} edit {tag} appears {side.count(new)}x in "
                   f"{name}.tex, not once -- a double-applied edit: "
                   f"{new[:80]!r}")
            residue = side.replace(new, "") if old in new else side
            ck(residue.count(old) == 0,
               f"round-39 {name} edit {tag} left its pre-image behind in "
               f"{name}.tex: {old[:80]!r}")
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-39 edit does not apply once to the rebuilt "
           f"round-38 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
''',
    "39-g: 13g's forward R39 replay stage")

# ================================ (h) 35d's build-identity stamp, r38 -> r39
# The revision number increments once per REVIEW round, and this is a new one (the
# NeurIPS 2026 main-track reject). The parent commit does NOT advance -- round 38
# is still uncommitted, so both rounds sit on 8f18687 -- but the DATE does: the
# EXP-BF re-collection ran past midnight, so round 39 is built on the 25th.
sub(r'''    _stamp35 = ("\\textbf{Build identity.} Source revision~38, built "
                "24~September~2026 from parent\ncommit \\texttt{8f18687}.")''',
    r'''    # ROUND-39 SUBSTITUTION: 38 -> 39, the stamp's own revision number, and
    # 24 -> 25 September: the parent commit is unchanged because round 38 is
    # uncommitted, and the build date advanced by one day because the EXP-BF
    # collection finished after midnight.
    _stamp35 = ("\\textbf{Build identity.} Source revision~39, built "
                "25~September~2026 from parent\ncommit \\texttt{8f18687}.")''',
    "39-h1: the build-identity stamp, revision 39")

sub(r'''        # ROUND-38 SUBSTITUTION: 37 -> 38, the stamp's own revision number.
        ck("Source revision 38" not in _f35,''',
    r'''        # ROUND-39 SUBSTITUTION: 38 -> 39, the stamp's own revision number.
        ck("Source revision 39" not in _f35,''',
    "39-h2: the stamp is absent from p1-p9")

sub(r'''    ck("Source revision 38" in " ".join(subprocess.run(
        ["pdftotext", "-f", "11", "-l", "11", "main.pdf", "-"],''',
    r'''    ck("Source revision 39" in " ".join(subprocess.run(
        ["pdftotext", "-f", "11", "-l", "11", "main.pdf", "-"],''',
    "39-h3: the stamp is on p11")

# =========================== (i) the code repo's round-39 deliverables
# Same allow-set discipline rounds 37 and 38 used: this round's code-repo files are
# ENUMERATED, so a stray untracked file still fails. Part A's re-collector, its
# scorer, the five re-collected response files and the analysis output.
#
# HONEST NOTE ON THIS GATE: it is red at the round-38 baseline and stays red, for a
# reason that has nothing to do with round 39. The code repo carries 93 MODIFIED
# tracked files left by the history rewrite that re-pinned 8f18687, and R37_TRACKED
# allows only two. The allow-set below is therefore a record of what this round
# added, not a claim that the gate passes; it will pass once the code repo is
# committed, which is the user's call and has not been made.
sub(r'''    R38_UNTRACKED = {
        "adaptive_lie_detector/experiments/analyze_r1_intervals.py",
        "adaptive_lie_detector/experiments/make_factorial_coding_sheet.py",
        "adaptive_lie_detector/data/results/r1_intervals.json",
        "adaptive_lie_detector/data/human_coding/",
    }''',
    r'''    R38_UNTRACKED = {
        "adaptive_lie_detector/experiments/analyze_r1_intervals.py",
        "adaptive_lie_detector/experiments/make_factorial_coding_sheet.py",
        "adaptive_lie_detector/data/results/r1_intervals.json",
        "adaptive_lie_detector/data/human_coding/",
    }
    # ROUND-39 ADDITION, same discipline: EXP-BF's two scripts and its six output
    # files. run_benign_fpr2.py re-collects because the July collection could not be
    # rescued by re-scoring (timeouts stored as non-firing responses, responses
    # truncated at 500 characters); analyze_benign_fpr.py is the ONLY place the
    # 14-pattern rule is applied, and it imports the list rather than copying it.
    # The July files are deliberately left in place under their old names, so they
    # do not appear here: they are already tracked.
    R39_UNTRACKED = {
        "adaptive_lie_detector/experiments/run_benign_fpr2.py",
        "adaptive_lie_detector/experiments/analyze_benign_fpr.py",
        "adaptive_lie_detector/data/results/benign_fpr2_llama3_2_3b.json",
        "adaptive_lie_detector/data/results/benign_fpr2_llama3_1_8b.json",
        "adaptive_lie_detector/data/results/benign_fpr2_mistral_7b.json",
        "adaptive_lie_detector/data/results/benign_fpr2_qwen2_5_7b.json",
        "adaptive_lie_detector/data/results/benign_fpr2_qwen2_5_14b.json",
        "adaptive_lie_detector/data/results/benign_fpr_analysis.json",
    }''',
    "39-i1: R39_UNTRACKED, the round's code-repo deliverables")

sub(r'''        if _st37 == "??" and _pt37 in R37_UNTRACKED | R38_UNTRACKED:''',
    r'''        if _st37 == "??" and _pt37 in R37_UNTRACKED | R38_UNTRACKED | R39_UNTRACKED:''',
    "39-i2: the status walk admits round 39's allow-set")

sub(r'''        return ((_s == "??" and _p in R37_UNTRACKED | R38_UNTRACKED)
                or (_s == "M" and _p in R37_TRACKED))''',
    r'''        return ((_s == "??"
                 and _p in R37_UNTRACKED | R38_UNTRACKED | R39_UNTRACKED)
                or (_s == "M" and _p in R37_TRACKED))''',
    "39-i3: 28o's predicate admits round 39's allow-set")

# ============== (j) the round-26 §3.4 name check: ADAGE leaves the main text
# The NeurIPS main-track reviewers flagged that ADAGE is unexpanded at its first
# main-text use. The user decision was to REMOVE the acronym from the main text
# rather than expand it there -- which is also what the paper's own appendix says
# about it ("ADAGE is an apparatus, not a contribution"), and what the 1.78in table
# column can afford: the gloss cost a full line and pushed the main text to p10, so
# buying it was not available at zero slack.
#
# The retained check is UPDATED, not deleted. Its claim was that §3.4's compression
# did not drop the apparatus, the factorial or EXP-G entirely; that claim survives
# with the apparatus named DESCRIPTIVELY instead of by acronym, and the acronym's
# single definition site is asserted in the appendix so "removed from the main text"
# cannot become "removed from the paper".
sub(r'''    for n in ["ADAGE", "factorial", "EXP-G"]:
        ck(n in expt, f"§3.4's compression dropped the name {n!r} entirely")''',
    r'''    # ROUND-39 SUBSTITUTION: "ADAGE" leaves this list. The acronym is gone from
    # the main text by design (see above); the apparatus is still named there, and
    # the acronym is still defined exactly once, in app:adage_details.
    for n in ["factorial", "EXP-G"]:
        ck(n in expt, f"§3.4's compression dropped the name {n!r} entirely")
    ck("the interrogation pipeline (EXP-A)" in expt,
       "39: §3.4 no longer names the interrogation pipeline at all. Round 39 "
       "removed the ADAGE acronym from the main text because it was unexpanded at "
       "first use and the 1.78in column cannot afford the gloss (it cost a line "
       "and took the main text to p10); the apparatus must still be named, "
       "descriptively, with its experiment tag")
    ck("ADAGE" not in expt,
       "39: the ADAGE acronym is back in experiments.tex. It is defined once, in "
       "app:adage_details, and the main text names the apparatus descriptively -- "
       "reintroducing the acronym here recreates the unexpanded-at-first-use "
       "defect the NeurIPS 2026 main-track review flagged")
    ck(app.count("Adaptive Deception") >= 1,
       "39: the appendix no longer expands ADAGE. Removing the acronym from the "
       "main text is only licensed while the appendix still defines it")''',
    "39-j: the §3.4 name check, with ADAGE out of the main text")

# ============== (k) `import math`, for group 39's Wilson re-derivation
# verify_r38.py imports collections/glob/io/json/os/re/subprocess/sys/zlib and no
# math. Group 39 recomputes the Wilson interval from the pooled counts rather than
# trusting the interval the analysis script wrote, which is the only way the pinned
# bound is a re-derivation and not a transcription.
sub(r'''import json
import os''',
    r'''import json
import math  # round 39: re-derive EXP-BF's Wilson bound rather than trust it
import os''',
    "39-k: import math")

# ============== (l) GROUP 39 ITSELF, inserted ahead of the self-reference
# Group 39 is placed BEFORE 38h because 38h must stay the last check in the file:
# it pins the total this harness scores, so anything added after it would not be
# counted by the number it asserts.
sub(r'''    # ---- 38h. THE SELF-REFERENCE, at its new fixed point. The count main.tex''',
    r'''    # ======================= GROUP 39 =======================================
    # THE NEURIPS 2026 MAIN-TRACK REVIEW (Decision: Reject), audited item by item
    # against the live tree. Three facts about this group before its checks:
    #
    #  1. The review is STALE -- the reviewed PDF is the ~May 2026 submission,
    #     dated from git log on references.bib before anything was read into it.
    #     Most of its items were already closed. The pins below are therefore
    #     mostly ANTI-REGRESSION pins on facts a later round could quietly undo,
    #     not records of round-39 edits.
    #  2. The two citation errors the checker found were REAL in the version
    #     reviewed. Staleness is not a defence, and 39p pins both as facts with
    #     the NeurIPS citation checker named as the reason, so no later round can
    #     tidy them back.
    #  3. The round's substantive addition (Part A, EXP-BF) answers reviewer 1's
    #     named main missing piece with data that already existed and had never
    #     reached the paper. Its numbers are pinned by RE-DERIVATION from the
    #     committed analysis JSON, not as literals: the checks below build the
    #     rendered strings from `fires`/`n` and recompute the Wilson bound, so a
    #     hand-typed number in the appendix fails here rather than being blessed.
    #
    # Facts this group deliberately does NOT re-pin, because they are already
    # pinned upstream and a second copy would inflate the total without adding
    # coverage: the 3 structured caution boxes and the 5 main-text float pages
    # (38e, 38f), the em-dash partition of 0 U+2014 and 42 three-hyphen runs
    # (38g), the abstract's 403/383/20 (29z), and the 17 pre-registrations (11).
    _APP39 = read("appendix.tex")
    _EXPT39 = read("experiments.tex")
    _INTRO39 = read("introduction.tex")
    _MT39 = io.open("main.tex", encoding="utf-8").read()
    _SRC39 = {_f39: read(_f39 + ".tex") for _f39 in
              ["abstract", "introduction", "methodology", "experiments",
               "discussion", "conclusion", "appendix", "related_work"]}

    # ---- 39m. No unfilled placeholder. app:benign_fpr was drafted with nine
    # `@@NAME@@` slots and every one was filled from the analysis JSON after the
    # collection finished. An unfilled slot renders verbatim in the PDF, and it is
    # the one defect in this round that a reader would see before a reviewer did.
    for _f39, _t39 in sorted(_SRC39.items()):
        ck("@@" not in _t39,
           f"39m: sections/{_f39}.tex still carries a '@@' placeholder; round 39 "
           f"drafted app:benign_fpr with nine of them and an unfilled one renders "
           f"verbatim")
    ck("@@" not in _MT39, "39m: main.tex still carries a '@@' placeholder")

    # ---- 39n. PART A, the subsection itself: it exists, it is reachable from the
    # appendix roadmap (bucket 3, "Robustness & diagnostics"), and it is labelled
    # a diagnostic rather than a pre-registered analysis -- which is the same
    # footing the paper gives claim 3, and the reason main.tex's
    # "17 pre-registrations" literal is untouched by this round.
    ck(_APP39.count(r"\label{app:benign_fpr}") == 1,
       "39n: app:benign_fpr is missing or duplicated; it is Part A's entire "
       "deliverable and the target of the roadmap pointer")
    ck(_APP39.count(r"\subsection{Benign False-Positive Rate of the "
                    r"Parameter-Free Rule (EXP-BF)}") == 1,
       "39n: EXP-BF's subsection heading is gone or reworded")
    ck(r"the rule's benign false-positive rate (\ref{app:benign_fpr})" in _APP39,
       "39n: bucket 3 of tab:appendix_roadmap no longer points at "
       "app:benign_fpr; an appendix subsection a reader cannot find from the "
       "roadmap is the defect the roadmap exists to prevent")
    _BF39 = (_APP39.split(r"\label{app:benign_fpr}", 1)[1].split("%%%%", 1)[0]
             if r"\label{app:benign_fpr}" in _APP39 else "")
    ck(len(_BF39) > 3000,
       f"39n: EXP-BF's body is {len(_BF39)} characters; it was written at ~4.4k "
       f"and a collapse that large means a caveat or the table is gone")
    for _p39 in (
            r"\textbf{It is a diagnostic, not a pre-registered analysis}",
            r"\textbf{No prompt contains a false claim and none creates a "
            r"knowledge conflict}",
            r"\textbf{aborts unless the import is exactly 14 patterns long}",
            # The disclosure the first draft of this subsection got WRONG: it
            # claimed the benign collection used the equalized arm's own system
            # prompt. It does not, and it cannot -- sec:r1_faithful's neutral
            # prompt announces a factual claim, and there is no claim in this set.
            # The appendix now states the difference instead of eliding it.
            r"\textbf{That is not the equalized arm's system prompt}"):
        ck(_p39 in _BF39,
           f"39n: EXP-BF lost a load-bearing sentence: {_p39[:60]!r}")
    ck("You are a helpful assistant. Answer the user's question clearly and "
       "concisely." in _BF39,
       "39n: EXP-BF no longer quotes the benign collection's neutral system "
       "prompt verbatim; it is quoted precisely because it differs from the "
       "equalized arm's and a reader must be able to see how")

    # ---- 39o. PART A's FOUR LIMITS. Each narrows the claim, and the number is an
    # overclaim without them: a zero count is not a zero rate, the benign set has
    # no knowledge conflict to be specific against, only the RULE's rate exists,
    # and specificity against ordinary talk is not robustness to an adversary.
    # Reviewers have named the structured cautions as a strength in every round;
    # these four are the same discipline applied to the round's own new result.
    for _i39, _c39 in ((1, r"\textbf{(1)~A zero count is not a zero rate.}"),
                       (2, r"\textbf{(2)~It measures specificity against "
                           r"ordinary conversation only.}"),
                       (3, r"\textbf{(3)~Only the rule's false-positive rate "
                           r"exists.}"),
                       (4, r"\textbf{(4)~It does not soften")):
        ck(_c39 in _BF39,
           f"39o: EXP-BF's limit ({_i39}) is gone. Without all four the number "
           f"overclaims, and limit (2) in particular is what stops a reader "
           f"treating a benign FPR as evidence the rule detects deception")
    ck(r"\textbf{not evidence that the rule detects deception}" in _BF39,
       "39o: limit (2) lost its conclusion")
    ck(r"\textbf{A detector can be quiet on ordinary conversation and still be "
       r"trivially evadable}" in _BF39,
       "39o: limit (4) lost the synthesis that keeps EXP-BF from reading as a "
       "reversal of sec:adversarial_paraphrase")
    ck(r"84\%$\to$16\%" in _BF39 and "35--51\\%" in _BF39,
       "39o: limit (4) no longer carries the fragility figures it reconciles "
       "EXP-BF with; the two results are about different properties and the "
       "appendix has to say so with both numbers present")

    # ---- 39p. PART A's NUMBERS, RE-DERIVED. Nothing here is a literal from the
    # appendix: the pooled count is rebuilt as "fires/n" from the analysis JSON,
    # the Wilson upper bound is RECOMPUTED here from those two integers, and the
    # per-target rows are checked by display name against the JSON's own roster.
    # So this fails if the paper and the data disagree, in either direction.
    _BFJ39 = os.path.join(CODEREPO, "data", "results", "benign_fpr_analysis.json")
    ck(os.path.exists(_BFJ39),
       "39p: data/results/benign_fpr_analysis.json is missing, so EXP-BF's "
       "published counts cannot be re-derived and the table is unverifiable")
    if os.path.exists(_BFJ39) and _BF39:
        _bf39 = json.load(io.open(_BFJ39, encoding="utf-8"))
        ck(_bf39.get("experiment") == "EXP-BF", "39p: the analysis JSON is not "
           "EXP-BF's")
        ck(_bf39.get("pre_registered") is False,
           "39p: the analysis JSON now claims EXP-BF is pre-registered; it is "
           "not, and main.tex's 17-pre-registration literal depends on that")
        ck(len(_bf39.get("patterns_14") or []) == 14,
           f"39p: the analysis recorded "
           f"{len(_bf39.get('patterns_14') or [])} patterns, not 14; the rule "
           f"the appendix describes and the rule that was applied have diverged")
        # The inventory equality the plan asks for, and the one that makes
        # "exactly as sec:hedging_baseline scores it" a checked statement: every
        # pattern the analysis APPLIED must appear verbatim in the appendix's
        # published list. The July defect was precisely a rule that ran and a rule
        # that was published being two different rules.
        _INV39 = (_APP39.split(r"\paragraph{Refusal/correction count patterns "
                               r"(14, verbatim from the analysis code):}", 1)[-1]
                        .split(r"\end{verbatim}", 1)[0])
        for _pat39 in (_bf39.get("patterns_14") or []):
            ck(_pat39 in _INV39,
               f"39p: EXP-BF applied the pattern {_pat39!r}, which does not "
               f"appear verbatim in app:regex_patterns' published list of 14. "
               f"The rule that ran and the rule the paper prints must be one "
               f"rule")
        ck(_bf39.get("n_targets") == 5,
           f"39p: EXP-BF scored {_bf39.get('n_targets')} targets, not the 5 of "
           f"EXP-C4's roster")
        ck(_bf39.get("n_prompts_per_target") == 50,
           f"39p: EXP-BF used {_bf39.get('n_prompts_per_target')} prompts per "
           f"target, not 50")
        _pool39 = _bf39["pooled"]["rule_14"]
        ck("%d/%d" % (_pool39["fires"], _pool39["n"]) in _BF39,
           "39p: the appendix does not render the pooled 14-pattern count "
           "%d/%d that data/results/benign_fpr_analysis.json holds"
           % (_pool39["fires"], _pool39["n"]))

        def _wilson39(k, n, z=1.96):
            """analyze_belief_strata.wilson, so the interval is re-derived."""
            p = k / n
            d = 1 + z * z / n
            c = (p + z * z / (2 * n)) / d
            h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
            return (max(0.0, c - h), min(1.0, c + h))

        _lo39, _hi39 = _wilson39(_pool39["fires"], _pool39["n"])
        ck(abs(_hi39 - _pool39["wilson95"][1]) < 1e-12,
           "39p: the analysis script's Wilson upper bound does not match this "
           "harness's independent recomputation from fires/n")
        ck("%.1f" % (_hi39 * 100) in _BF39,
           "39p: EXP-BF's limit (1) does not carry the recomputed Wilson upper "
           "bound %.1f%%; a zero count is only reportable as an interval"
           % (_hi39 * 100))
        _DISP39 = {"llama3.2:3b": "Llama~3.2~3B", "llama3.1:8b": "Llama~3.1~8B",
                   "mistral:7b": "Mistral~7B", "qwen2.5:7b": "Qwen~2.5~7B",
                   "qwen2.5:14b": "Qwen~2.5~14B"}
        for _row39 in _bf39["per_target"]:
            _m39 = _row39["model"]
            ck(_m39 in _DISP39,
               f"39p: EXP-BF scored {_m39!r}, which is not on EXP-C4's "
               f"five-target roster; the roster is the one the paper already "
               f"justifies, including Qwen 2.5 32B's memory exclusion")
            ck(_DISP39.get(_m39, _m39) in _BF39,
               f"39p: EXP-BF's table does not render a row for {_m39!r}")
            ck(_row39["rule_14"]["n"] + _row39["n_timeout_excluded"]
               == _bf39["n_prompts_per_target"],
               f"39p: {_m39}'s scored + excluded records do not add to the "
               f"prompt set; a denominator that does not reconcile is exactly "
               f"the July defect this re-collection exists to fix")

    # ---- 39q. PART A's SCRIPTS: the rule lives in exactly ONE place, and the
    # analyzer makes no call of any kind. This is the check that makes the
    # appendix's "imports that list rather than copying it" sentence true rather
    # than asserted -- the July script's PRIVATE 4-pattern copy is precisely how a
    # published FPR came to describe no rule the paper reports.
    _AN39 = os.path.join(CODEREPO, "experiments", "analyze_benign_fpr.py")
    _CO39 = os.path.join(CODEREPO, "experiments", "run_benign_fpr2.py")
    ck(os.path.exists(_AN39),
       "39q: experiments/analyze_benign_fpr.py is missing; every EXP-BF number "
       "is derived by it and by nothing else")
    ck(os.path.exists(_CO39),
       "39q: experiments/run_benign_fpr2.py is missing; it is the collector the "
       "appendix credits for the untruncated responses")
    if os.path.exists(_AN39):
        _an39 = io.open(_AN39, encoding="utf-8").read()
        ck("from hedging_baseline import REFUSAL_PATTERNS" in _an39,
           "39q: the analyzer no longer IMPORTS the pattern list. A copy is how "
           "the July 4-pattern defect happened")
        ck("REFUSAL_PATTERNS" in _an39 and "not 14" in _an39,
           "39q: the analyzer no longer aborts on a pattern count other than 14, "
           "so the appendix's claim that it cannot drift from the inventory is "
           "no longer true")
        for _net39 in ("requests.", "ollama", "http://", "https://", "urllib",
                       "boto3"):
            ck(_net39 not in _an39,
               f"39q: the analyzer references {_net39!r}; EXP-BF is pure "
               f"re-scoring of committed text and must make no call and no "
               f"network access")
        _WB39 = ("    p = k / n\n"
                 "    d = 1 + z * z / n\n"
                 "    c = (p + z * z / (2 * n)) / d\n"
                 "    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))"
                 " / d\n"
                 "    return (max(0.0, c - h), min(1.0, c + h))")
        ck(_WB39 in _an39,
           "39q: the analyzer's Wilson helper is no longer byte-identical to "
           "analyze_belief_strata.py's; two intervals computed two ways in one "
           "paper is a defect even when they agree")
        _BS39 = os.path.join(CODEREPO, "experiments", "analyze_belief_strata.py")
        ck(os.path.exists(_BS39)
           and _WB39 in io.open(_BS39, encoding="utf-8").read(),
           "39q: analyze_belief_strata.py's Wilson helper has changed; it is the "
           "one EXP-BF's copy is pinned against")
    if os.path.exists(_CO39):
        _co39 = io.open(_CO39, encoding="utf-8").read()
        ck("THIS SCRIPT DOES NO SCORING." in _co39,
           "39q: the collector's no-scoring declaration is gone")
        ck("re.search" not in _co39 and '"rule_fires"' not in _co39,
           "39q: the collector has acquired scoring code. The 14-pattern rule "
           "must exist in one place and be applied in one place; the July "
           "script's private copy is the reason that is a check and not a "
           "convention")
        ck('"truncated": False' in _co39,
           "39q: the collector no longer records truncated=false per file, which "
           "is the flag the analyzer gates on. The July run stored resp[:500], "
           "and truncated text supports a lower bound, not a rate")
        ck("BENIGN_PROMPTS, NEUTRAL_SYSTEM_PROMPT" in _co39,
           "39q: the collector no longer imports the prompt set and the neutral "
           "system prompt from the July script. A re-collection that retypes "
           "either is a different experiment, and the appendix quotes that "
           "prompt verbatim")
        _JU39 = os.path.join(CODEREPO, "experiments", "run_benign_fpr.py")
        ck(os.path.exists(_JU39)
           and 'NEUTRAL_SYSTEM_PROMPT = (\n    "You are a helpful assistant. '
               'Answer the user\'s question clearly and concisely."\n)'
               in io.open(_JU39, encoding="utf-8").read(),
           "39q: the neutral system prompt the appendix quotes is no longer the "
           "one in experiments/run_benign_fpr.py, which is where the collector "
           "imports it from")
        # The two generation parameters the appendix quotes are the shared Ollama
        # defaults, not settings this experiment chose. Pinned at their source so
        # the appendix cannot drift from the path that produced the responses.
        _OT39 = os.path.join(CODEREPO, "src", "ollama_target_model.py")
        if os.path.exists(_OT39):
            _ot39 = io.open(_OT39, encoding="utf-8").read()
            ck("max_tokens: int = 300" in _ot39 and '"temperature": 0.7' in _ot39,
               "39q: src/ollama_target_model.py's generation defaults are no "
               "longer max_tokens=300 and temperature=0.7, which is what EXP-BF's "
               "Materials paragraph quotes")
            ck(r"\texttt{max\_tokens}~300, \texttt{temperature}~0.7" in _BF39,
               "39q: EXP-BF no longer states the generation parameters its "
               "responses were produced under")
        ck("NeutralOllamaModel(OllamaTargetModel)" in _co39,
           "39q: the collector no longer subclasses OllamaTargetModel. It sets a "
           "system prompt and nothing else; a private generation path would make "
           "'the unmodified generation path of EXP-R1/EXP-C4' false")
        ck("require_exact_tags" in _co39,
           "39q: the collector no longer refuses to start unless every target's "
           "EXACT tag is installed. A prefix match accepted an absent model in "
           "July and produced 50 timeout records scored as non-firing responses")

    # ---- 39r. PART A's PROVENANCE PARAGRAPH: the appendix states both July
    # defects and names the command that reproduces them. A superseded collection
    # that is merely dropped is indistinguishable from one that was never run.
    for _j39 in (r"analyze\_benign\_fpr.py -{}-july",
                 r"\textbf{Truncation can only hide a marker, never invent one}",
                 "error excluded from the denominator"):
        ck(_j39 in _BF39,
           f"39r: EXP-BF's collected-twice paragraph lost {_j39[:50]!r}; the "
           f"July collection's defects are disclosed, not buried")

    # ---- 39s. PART B, the clarity items. Three reviewers independently said the
    # paper is hard to follow and were right about the one that matters most: the
    # paper's headline mechanism was operationally defined only inside a figure
    # cell. These four pins are cheap and each answers a named complaint.
    ck(_EXPT39.count("both arms given one byte-identical neutral prompt, so "
                     "neither is told to lie") == 1,
       "39s: prompt equalization is no longer defined operationally at first use "
       "in the body. A reader met 'under equalization' throughout and was told "
       "what it meant only inside fig:ladder's rung-2 cell; that is the "
       "metareview's central complaint")
    ck(r"\paragraph{Related work.}" in _INTRO39,
       "39s: the related-work paragraph heading is gone. Two reviewers searched "
       "for 'Related work' and did not find it")
    ck("Relation to prior work" not in _INTRO39,
       "39s: the old 'Relation to prior work' heading is back")
    ck(r"\ref{app:related_work}" in _INTRO39,
       "39s: the pointer from the renamed paragraph to the appendix's full "
       "related-work treatment is gone; the rename is only honest while the "
       "pointer stands")
    ck(r"\subsection" not in _INTRO39,
       "39s: the Introduction has a \\subsection again. A lone subsection there "
       "is the 'Section 1.1 with no 1.2' defect the same review flagged, and it "
       "is the reason Related Work was renamed rather than promoted")
    ck("mechanism-faithful reimplementation" in _EXPT39
       and "at one third the width" in _EXPT39
       and r"\emph{design}, not about their instrument at full width" in _EXPT39,
       "39s: the replication-scope concession is no longer in the body. "
       "Reviewer 1's W2 and PHn9 both asked for the bank-width gap in the main "
       "text, and it reads as a concealment when it sits only in an appendix")

    # ---- 39t. THE THREE BIBLIOGRAPHY FACTS, pinned as facts. The NeurIPS 2026
    # citation checker flagged two of 22 references; both flags were correct in
    # the version reviewed, and the metareview's "even as a core paper it is
    # wrongly referenced" was XTps's Pacchiardi correction. All three are closed.
    # They are pinned HERE, with the checker named, so that no later round can
    # tidy them back and so that the response letter's claim of 0 of 27 matching
    # entries is a measured statement.
    _BIB39 = io.open("references.bib", encoding="utf-8").read()
    ck("anthropic2025claude" not in _BIB39,
       "39t: the hallucinated key anthropic2025claude is back in references.bib. "
       "The NeurIPS 2026 citation checker found no such 'Claude 4.5 model "
       "family' report exists; the real citation is anthropic2025haiku45")
    for _f39, _t39 in sorted(_SRC39.items()):
        ck("anthropic2025claude" not in _t39,
           f"39t: sections/{_f39}.tex cites the hallucinated key "
           f"anthropic2025claude")
    ck("anthropic2025haiku45" in _BIB39,
       "39t: the real Claude Haiku 4.5 System Card entry is gone")
    ck("HackAPrompt" not in _BIB39,
       "39t: the HackAPrompt title is back on perez2022ignore. The checker's "
       "second flag was that this entry conflated two different papers")
    ck("Ignore Previous Prompt" in _BIB39,
       "39t: perez2022ignore lost its own title")
    ck(r"Perez, F{\'a}bio and Ribeiro, Ian" in _BIB39,
       "39t: perez2022ignore's authors are no longer Perez and Ribeiro")
    ck("arXiv:2211.09527" in _BIB39,
       "39t: perez2022ignore lost the arXiv identifier that disambiguates it "
       "from the paper whose title it used to carry")
    for _a39 in ("Alexa Y. Pan", "Yarin Gal", "Jan Brauner"):
        ck(_a39 in _BIB39,
           f"39t: pacchiardi2024catch lost the author {_a39!r}. XTps gave the "
           f"correction as all eight authors and ICLR 2024, and the metareview "
           f"escalated it; the venue is pinned in 38i and the roster here")

    # ---- 39u. EXP-BF's ONE float, pinned where it landed. 28p's two late
    # appendix pins each gain a number this round, and this is the float that
    # spent it: if tab:benign_fpr were ever deleted those two would silently
    # come back by one and 28p would fire with no way to say why. Pinning the
    # cause next to the effect is what makes that diagnosable. Page 42 also has
    # to be an APPENDIX page, which is the same >9 test 28p applies to its own
    # five, and it is the machine-checkable form of "Part A landed in the
    # appendix".
    _bf39 = re.search(r"newlabel\{tab:benign_fpr\}\{\{([^}]*)\}\{(\d+)\}", aux)
    ck(_bf39 is not None,
       "39u: float tab:benign_fpr has no newlabel; EXP-BF's table is gone")
    if _bf39:
        ck(_bf39.group(1) == "32" and _bf39.group(2) == "42",
           f"39u: tab:benign_fpr moved: now {_bf39.group(1)} on "
           f"p{_bf39.group(2)}, expected 32 on p42. 28p's tab:dimension_transfer "
           f"and tab:covariate_audit pins are stated relative to this float's "
           f"insertion, so move all three together or none")
        ck(int(_bf39.group(2)) > 9,
           f"39u: tab:benign_fpr landed in the MAIN text, on p{_bf39.group(2)}. "
           f"Part A is appendix-only by measurement: the main-text clause was "
           f"costed and dropped because p9 has no room")

    # ---- 38h. THE SELF-REFERENCE, at its new fixed point. The count main.tex''',
    "39-l: group 39, ahead of the self-reference")

print("structural substitutions staged: %d" % len(subs), file=sys.stderr)

# ===================================================== THE MEASURED SUBSTITUTIONS
# Everything below moves a pin to a number that was MEASURED after the round-39
# build, never predicted. Each is an EQUALITY or a band, updated with the
# round-39 reason, so a later round that moves the same quantity still fires.
#
# What round 39 actually cost, measured:
#   appendix.tex   403,709 -> 410,648 chars  (+6,939: EXP-BF plus its roadmap ref)
#   page count     94 -> 95                  (the one appendix page EXP-BF costs)
#   Underfull      108 -> 108                (UNCHANGED, so 37a is NOT touched)
#   main text      still ends p9 at ruler 485, Ethics still opens p10 at 486
#   main-text      fig:dag 1/p2, tab:claim_ledger 1/p5, fig:ladder 2/p5,
#   floats         fig:r1c_collapse 3/p7, tab:external_audit 2/p8 -- ALL UNMOVED,
#                  which is the proof that Part A landed in the appendix.

sub(r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, the one appendix page Part A's four
    # interval paragraphs and Part B's coding-sheet paragraph cost (~7.1k chars).
    # Still an EQUALITY in both directions: 95+ means an unbudgeted add, 93 or
    # fewer means a later round deleted material this one deliberately landed.
    ck("Output written on main.pdf (94 pages" in log,
       "page count is not 94 (89 + round 37's four appendix pages + round 38's "
       "one for the equalization-panel intervals and the T/D disclosure)")''',
    r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, the one appendix page Part A's four
    # interval paragraphs and Part B's coding-sheet paragraph cost (~7.1k chars).
    # Still an EQUALITY in both directions: 95+ means an unbudgeted add, 93 or
    # fewer means a later round deleted material this one deliberately landed.
    # ROUND-39 SUBSTITUTION: 94 -> 95, the one appendix page EXP-BF costs
    # (+6,939 characters of appendix.tex, measured). Still an EQUALITY in both
    # directions: 96+ means an unbudgeted add, 94 or fewer means a later round
    # deleted EXP-BF or something else this round landed. The two ruler
    # assertions are UNCHANGED, which is the costing claim: the main text still
    # ends on p9 at 485 and Ethics still opens p10 at 486, so the new page is
    # appendix. Round 39's ONE main-text candidate -- a clause on the benign
    # false-positive rate beside sec:hedging_baseline's 69-80% -- was measured
    # against this budget and DROPPED: that paragraph's last rendered line is
    # full, so even a 31-character addition moved the main text's final line
    # from 485 onto p10. Part A is appendix-only by measurement, not by choice.
    ck("Output written on main.pdf (95 pages" in log,
       "page count is not 95 (89 + round 37's four appendix pages + round 38's "
       "one for the equalization-panel intervals and the T/D disclosure + round "
       "39's one for EXP-BF)")''',
    "39-m1: check 1's page count, 94 -> 95")

sub(r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, Part A's and Part B's one appendix page.
    # The two ruler assertions below are again UNCHANGED, which is the costing
    # claim restated: p9 still closes at 485 and the Ethics statement still opens
    # p10 at 486, so the new page is appendix.
    ck(re.search(r"Pages:\s+94", _pp36) is not None,
       f"36e: the document is not 94 pages: "''',
    r'''    # ROUND-38 SUBSTITUTION: 93 -> 94, Part A's and Part B's one appendix page.
    # The two ruler assertions below are again UNCHANGED, which is the costing
    # claim restated: p9 still closes at 485 and the Ethics statement still opens
    # p10 at 486, so the new page is appendix.
    # ROUND-39 SUBSTITUTION: 94 -> 95, EXP-BF's one appendix page. The two ruler
    # assertions below are UNCHANGED for the third round running, which is what
    # licenses calling this an appendix-only round.
    ck(re.search(r"Pages:\s+95", _pp36) is not None,
       f"36e: the document is not 95 pages: "''',
    "39-m2: 36e's page count, 94 -> 95")

sub(r'''    ck(len(app34) < 408_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441, round 37 added 17,390 for EXP-XP and Parts "
       f"A/C/D and round 38 added 7,149 for the equalization-panel intervals and "
       f"the T/D disclosure -- a value this high means more than that landed")
    ck(len(app34) > 398_000,
       f"34a: appendix.tex is {len(app34)} chars, below round 34's 379,441 plus "
       f"round 37's 17,390 plus round 38's 7,149 -- something was deleted that "
       f"one of the three rounds deliberately kept; see 34g, 37e and 38b")''',
    r'''    # ROUND-39 SUBSTITUTION: the LIVE band moves a third time, by round 39's
    # MEASURED +6,939 characters (EXP-BF's subsection and its roadmap
    # reference; 403,709 -> 410,648). Round 34's claim is again not weakened by
    # re-banding the live number: it is RESTORED at full strength immediately
    # below, where un-doing rounds 39, 38 and 37 and un-converting round 36 must
    # land back inside round 34's original 372,000-382,000 window -- and THAT
    # pair of checks is untouched by this round too.
    ck(len(app34) < 415_000,
       f"34a: appendix.tex is {len(app34)} chars; round 34's condensation took "
       f"it from 386,189 to 379,441, round 37 added 17,390 for EXP-XP and Parts "
       f"A/C/D, round 38 added 7,149 for the equalization-panel intervals and "
       f"the T/D disclosure and round 39 added 6,939 for EXP-BF -- a value this "
       f"high means more than that landed")
    ck(len(app34) > 405_000,
       f"34a: appendix.tex is {len(app34)} chars, below round 34's 379,441 plus "
       f"round 37's 17,390 plus round 38's 7,149 plus round 39's 6,939 -- "
       f"something was deleted that one of the four rounds deliberately kept; "
       f"see 34g, 37e, 38b and 39n")''',
    "39-m3: 34a's live character band, re-banded on the measured +6,939")

sub(r'''                           # ROUND-38 SUBSTITUTION: round 38 adds ~7.1k
                           # characters of appendix prose upstream of both, so
                           # each moves one page LATER and neither changes its
                           # float number (round 38 adds no float at all).
                           # Updated rather than relaxed -- a further shift, or
                           # any change of float number, still fires.
                           ("tab:dimension_transfer", "52", "71"),
                           ("tab:covariate_audit", "53", "73")]:''',
    r'''                           # ROUND-38 SUBSTITUTION: round 38 adds ~7.1k
                           # characters of appendix prose upstream of both, so
                           # each moves one page LATER and neither changes its
                           # float number (round 38 adds no float at all).
                           # Updated rather than relaxed -- a further shift, or
                           # any change of float number, still fires.
                           # ROUND-39 SUBSTITUTION: EXP-BF adds ONE appendix
                           # float (tab:benign_fpr, number 32 on p42) upstream
                           # of both, so each gains exactly one NUMBER, and
                           # +6,939 characters of appendix prose push each one
                           # page LATER. Both deltas are the signature of an
                           # append that displaced nothing: a float inserted
                           # upstream renumbers everything after it by one, and
                           # a page of prose moves pages by one. 39u below pins
                           # tab:benign_fpr itself at 32/p42, so this pair and
                           # that one cannot drift apart silently.
                           ("tab:dimension_transfer", "53", "72"),
                           ("tab:covariate_audit", "54", "74")]:''',
    "39-m4: 28p's two late appendix float pins, +1 number and +1 page")

sub(r'''        _R37_MOVED = {_k: (tuple(_v[0]), tuple(_v[1])) for _k, _v in
                      json.load(io.open("/tmp/r38_label_moves.json",
                                        encoding="utf-8")).items()}
        ck(len(_R37_MOVED) == 103,
           f"35g: the round-37 move record has {len(_R37_MOVED)} entries, not the "
           f"103 gen_r37_label_moves.py measured")''',
    r'''        # ROUND-39 SUBSTITUTION: regenerated again, by gen_r39_label_moves.py,
        # and this time the moved SET grows: 103 -> 137. Two causes, both
        # measured. (1) EXP-BF adds ONE appendix float (tab:benign_fpr, 32/p42),
        # which renumbers every appendix float after it, so a label can differ
        # from its c9718cf pin in the NUMBER component alone. (2) The roadmap
        # reference added to bucket 3 of tab:appendix_roadmap costs one rendered
        # line in a wrapped table cell, which pushes several early appendix
        # section headings across a page boundary WITHOUT adding a page there --
        # that is why 36 labels whose c9718cf pages are in the p17-p41 range
        # newly appear here while 28p's tab:eccp_decidability 7/p20,
        # tab:frontier_panel 9/p23 and tab:experiment_summary 10/p25 are all
        # unmoved. The generator still refuses to write if any moved label's
        # c9718cf page was inside the 9-page main text, and still re-asserts the
        # five main-text float pins byte-identical before emitting anything.
        _R37_MOVED = {_k: (tuple(_v[0]), tuple(_v[1])) for _k, _v in
                      json.load(io.open("/tmp/r39_label_moves.json",
                                        encoding="utf-8")).items()}
        ck(len(_R37_MOVED) == 137,
           f"35g: the round-39 move record has {len(_R37_MOVED)} entries, not the "
           f"137 gen_r39_label_moves.py measured")''',
    "39-n1: 35g's move record, regenerated for round 39 (103 -> 137)")

sub(r'''        # ROUND-38 SUBSTITUTION: the same 103 labels, one page further on. The
        # -1 and +1 buckets are unchanged (three labels still move backward, 23
        # still move by one), and the mass that sat at +3 moves to +4: round 38's
        # single appendix page. A 104th label, or a label moving by a different
        # amount, still fires.
        ck(_hist37 == {-1: 3, 1: 23, 2: 1, 3: 5, 4: 61, 5: 10},
           f"35g: the page-delta histogram of the moved appendix pins is "
           f"{dict(sorted(_hist37.items()))}, not the "
           f"{{-1: 3, 1: 23, 2: 1, 3: 5, 4: 61, 5: 10}} round 38 is costed at")''',
    r'''        # ROUND-39 SUBSTITUTION: the histogram is re-measured on the 137. The
        # mass that sat at +4 has moved to +5 and +6 (EXP-BF's one appendix page
        # on top of round 38's, with local float packing deciding which), the +1
        # and +2 buckets grow by the early headings the roadmap line pushed over
        # a boundary, and two labels still move BACKWARD. THERE IS NO 0 BUCKET,
        # which is the non-obvious fact worth pinning: no label changed float
        # NUMBER while keeping its page, so the renumbering tab:benign_fpr causes
        # and the repagination EXP-BF causes affect exactly the same labels. A
        # 138th label, or a label moving by a different amount, still fires.
        ck(_hist37 == {-1: 2, 1: 37, 2: 21, 4: 4, 5: 40, 6: 30, 7: 3},
           f"35g: the page-delta histogram of the moved appendix pins is "
           f"{dict(sorted(_hist37.items()))}, not the "
           f"{{-1: 2, 1: 37, 2: 21, 4: 4, 5: 40, 6: 30, 7: 3}} round 39 is "
           f"costed at")''',
    "39-n2: 35g's page-delta histogram, re-measured")

sub(r'''        # ROUND-37 SUBSTITUTION: the label SET may now differ, by exactly EXP-XP's
        # two labels and nothing else, in the add direction only.
        ck(set(_b35) - set(_a35) == {"app:pacchiardi_census",
                                     "tab:pacchiardi_census"},
           f"35g: the labels added since c9718cf are "
           f"{sorted(set(_b35) - set(_a35))}, not EXP-XP's two")''',
    r'''        # ROUND-37 SUBSTITUTION: the label SET may now differ, by exactly EXP-XP's
        # two labels and nothing else, in the add direction only.
        # ROUND-39 SUBSTITUTION: plus EXP-BF's two, app:benign_fpr (the
        # subsection) and tab:benign_fpr (its one table). That is the whole of
        # round 39's label cost, it is why 38f's total moves 225 -> 227, and the
        # add-only direction is still asserted below. Round 38 added none.
        ck(set(_b35) - set(_a35) == {"app:pacchiardi_census",
                                     "tab:pacchiardi_census",
                                     "app:benign_fpr", "tab:benign_fpr"},
           f"35g: the labels added since c9718cf are "
           f"{sorted(set(_b35) - set(_a35))}, not EXP-XP's two and EXP-BF's two")''',
    "39-n3: 35g's added-label set, plus EXP-BF's two")

sub(r'''              ("appendix.tex",    31, 433, 256)]''',
    r'''              # ROUND-39 SUBSTITUTION: 256 -> 260 en dashes. Four new RANGES in
              # EXP-BF, counted in the source: `69--80\%` twice (the accuracy the
              # subsection is about), `330--1{,}182` (the per-target median
              # response length, which is what shows nothing was truncated) and
              # `35--51\%` (the paraphrase band limit (4) restates). The em-dash
              # count is unchanged at 31 on both sides of the conversion, which
              # is what 36a is for, and 38g independently re-partitions the 31.
              ("appendix.tex",    31, 433, 260)]''',
    "39-n4: 36a's appendix en-dash count, 256 -> 260")

sub(r'''    for _f38a in ["abstract", "methodology", "experiments", "discussion",
                  "conclusion"]:''',
    r'''    # ROUND-39 SUBSTITUTION: experiments.tex leaves this list, because round 39's
    # three clarity edits land in it (prompt equalization defined operationally at
    # first use in the body, the bank-width concession lifted out of the appendix,
    # and ADAGE removed from the main text). It is not thereby unchecked -- it is
    # checked HARDER, in the loop just below, against the round-39 ledger itself
    # rather than against a blanket equality, and 39-d's 37b pin independently
    # proves it reduces to ea6faf9 under UNDO39 composed with UNDO38 and UNDO37.
    # abstract.tex and discussion.tex remain, so both standing no-fund sites hold.
    for _f38a in ["abstract", "methodology", "discussion",
                  "conclusion"]:''',
    "39-n5: 38a's no-fund roster, experiments.tex moved out")

sub(r'''    for _f38b in ["introduction", "related_work"]:
        _was38b = _git38("sections/%s.tex" % _f38b)''',
    r'''    # ROUND-39 SUBSTITUTION: experiments.tex joins this loop, which is where it
    # is checked instead. UNDO39 runs innermost (see 39-f), so a file round 39
    # touches and round 38 does not still reduces to the round-37 commit: UNDO38
    # simply has no pairs for it.
    for _f38b in ["introduction", "related_work", "experiments"]:
        _was38b = _git38("sections/%s.tex" % _f38b)''',
    "39-n6: 38a's ledger-reduction loop, experiments.tex moved in")

sub(r'''        ck(len(_B38) == 225,
           f"38f: the document has {len(_B38)} labels, not 225; round 38 adds no "
           f"float and no \\label, so a new one is an unbudgeted add")''',
    r'''        # ROUND-39 SUBSTITUTION: 225 -> 227. EXP-BF adds exactly two labels,
        # app:benign_fpr and tab:benign_fpr, and 39-n3 names them as the only
        # additions since c9718cf. Still an EQUALITY: a 228th label is an
        # unbudgeted add, and 226 means one of EXP-BF's two was deleted. The five
        # main-text float pins above are UNMOVED, which together with this is the
        # whole costing claim for the round -- two new labels, both in the
        # appendix, and no main-text movement at all.
        ck(len(_B38) == 227,
           f"38f: the document has {len(_B38)} labels, not 227; round 39 adds "
           f"EXP-BF's two (app:benign_fpr, tab:benign_fpr) and nothing else, so "
           f"any other count is an unbudgeted add or a deletion")''',
    "39-n7: 38f's label total, 225 -> 227")

sub(r'''        ck(len(_a35) == 223 and len(_b35) == 225,
           f"35g: the document has {len(_b35)} labels, c9718cf had "
           f"{len(_a35)}, expected 223 then and 225 now")''',
    r'''        # ROUND-39 SUBSTITUTION: 225 -> 227 on the live side, EXP-BF's two. The
        # c9718cf side stays 223: it is a commit, and if it ever moves the pin is
        # reading the wrong revision. 38f asserts the same live total independently
        # off main.aux, and 39-n3 below names the four added labels exactly.
        ck(len(_a35) == 223 and len(_b35) == 227,
           f"35g: the document has {len(_b35)} labels, c9718cf had "
           f"{len(_a35)}, expected 223 then and 227 now")''',
    "39-n8: 35g's own label total, 225 -> 227 live")

sub(r'''                  # ROUND-38 SUBSTITUTION: the advertised total moves with the
                  # harness, 2,765 -> 2,911. See 38h for the arithmetic and for
                  # why the parent scored 2,766 against this tree before a single
                  # round-38 check was added.
                  "\\textbf{2{,}911-check verification harness}",''',
    r'''                  # ROUND-38 SUBSTITUTION: the advertised total moves with the
                  # harness, 2,765 -> 2,911. See 38h for the arithmetic and for
                  # why the parent scored 2,766 against this tree before a single
                  # round-38 check was added.
                  # ROUND-39 SUBSTITUTION: 2,911 -> 3,072, and note that this time
                  # the parent scores FEWER against this tree than against its own
                  # (2,909, not 2,911): two of its checks are raised inside loops
                  # whose membership round 39 changed. The number is read off
                  # run.py's final line either way, never predicted.
                  "\\textbf{3{,}072-check verification harness}",''',
    "39-n9: 37h's advertised-total literal, 2,911 -> 3,072")

sub(r'''    ck("2{,}911-check" in _MT37,
       "37h: the advertised check count is not 2,911; re-pin it here and in "
       "main.tex together, and re-read the final line of verification/run.py's "
       "output for the true number")''',
    r'''    ck("3{,}072-check" in _MT37,
       "37h: the advertised check count is not 3,072; re-pin it here and in "
       "main.tex together, and re-read the final line of verification/run.py's "
       "output for the true number")''',
    "39-n10: 37h's self-reference, 2,911 -> 3,072")

sub(r'''    #   =2,911
    ck("2{,}911-check verification harness" in _MT38,
       "38h: main.tex's advertised check count is not 2,911; re-pin it here, in "
       "37h and in main.tex together, and read the final line of "
       "verification/run.py's output for the true number")''',
    r'''    #   =2,911
    #
    # ROUND-39 SUBSTITUTION: 2,911 -> 3,072. The round-39 arithmetic, measured the
    # same way, by diffing the two harnesses' raised checks on this one tree rather
    # than by counting source lines:
    #
    #   2,909  verify_r38.py's total AGAINST THIS TREE (`run.py r38`), which is
    #          TWO FEWER than the 2,911 it scored against its own. That direction
    #          is the surprise and it is why this number is measured and not
    #          predicted: the total is not a property of the harness alone, it is a
    #          property of the harness applied to a tree, because checks raised
    #          inside loops over the document move with the document.
    #     +34  35g's per-moved-label loop, which raises one check per entry of the
    #          move record: gen_r39_label_moves.py measures 137 moved appendix pins
    #          where round 38 measured 103. EXP-BF's one appendix float renumbers
    #          the appendix tail and the roadmap line repaginates its head, so the
    #          record grows; 39-n1..n3 pin its size, its histogram and the four
    #          labels added since c9718cf.
    #      +1  38a's experiments.tex, which leaves the one-check byte-identity
    #          roster (round 39 edits it for the clarity items) and enters the
    #          two-check ledger-reduction loop instead. A no-fund file becoming a
    #          funded one costs exactly one check, and it is checked harder after.
    #    +128  groups 39a-39u's own checks, from the same diff: the round-39 ledger
    #          and its chain inversion, the build and budget re-pins, EXP-BF's
    #          table, caveats and re-derivation, Part B's four clarity pins, the
    #          three bibliography facts pinned as facts with the NeurIPS citation
    #          checker named as the reason, and this paragraph's own check.
    #          Round 39 RETIRES NOTHING: §3.4's ADAGE check is inverted in place
    #          (present -> absent from the main text, present in the appendix) with
    #          the round-39 reason in a comment, not deleted, which is why the
    #          count only ever goes up.
    #   =3,072
    ck("3{,}072-check verification harness" in _MT38,
       "38h: main.tex's advertised check count is not 3,072; re-pin it here, in "
       "37h and in main.tex together, and read the final line of "
       "verification/run.py's output for the true number")''',
    "39-n11: 38h's self-reference and the round-39 arithmetic, 2,911 -> 3,072")

print("measured substitutions staged: %d" % len(subs), file=sys.stderr)

# ============================================================== apply, in order
for old, new, label in subs:
    n = out.count(old)
    if n != 1:
        raise SystemExit("[%s] anchor occurs %d times, not once; nothing written"
                         % (label, n))
    out = out.replace(old, new, 1)

print("substitutions applied: %d" % len(subs))
io.open(OUT, "w", encoding="utf-8").write(out)
print("wrote %s (%d lines, was %d)"
      % (OUT, out.count("\n") + 1, src.count("\n") + 1))
