#!/usr/bin/env python3
"""Build /tmp/verify_r35.py from /tmp/verify_r34.py.

Retains all 2082 round-34 checks. The ones round 35 deliberately changes are
UPDATED IN PLACE with the round-35 reason in a comment, never deleted, per the
standing rule. Then appends GROUP 35.

Round 35 answers a 7/10 Weak Accept (confidence 4/5) whose per-dimension scores
average ~8.4 (Novelty 8, Correctness 8.5, Rigor 8.5, Empirical support 8,
Significance 8.5, Clarity 8, Reproducibility 9). The 7 is a DISCOUNT the report
explains twice -- "Claims 1-4: very strong. Claim 5: quite weak" and "this
creates a strange asymmetry" -- and their §18 names the remedy: make the
epistemic hierarchy "the dominant thing a reviewer sees". They also say "I don't
think you need another giant experiment".

So the round is four edits, none of them an experiment and none of them a
number:
  A  fig:ladder's five rung labels now carry THEIR epistemic verbs
     (Identified / Demonstrated / Diagnosed / Possible / Not identified) --
     folded into the hierarchy that already exists rather than added as a
     fourth rendering of it, because a fourth would worsen the label overload
     their own §15 complains about. Free: the tikz bands are fixed-height.
  B  the independence claim their §8 asks for almost verbatim, absent until now
     ("does not depend" = 0 occurrences in the main text at c9718cf).
  C  the ECCP status disclaimer moves to the front of its paragraph (their §14).
     A pure move: 1330 chars in, 1330 chars out.
  D  a build-identity stamp, because this is the THIRD consecutive review of the
     round-31 tree. Lands on p11, outside the 9-page budget, so it is free.

Measured cost of all four: ZERO. All 223 \newlabel page pins are unchanged from
c9718cf, p9 still ends at ruler 485, and the page count is still 89.
"""
import io

SRC = "/tmp/verify_r34.py"
DST = "/tmp/verify_r35.py"
s = io.open(SRC, encoding="utf-8").read()
n = 0


def sub(old, new, label):
    global s, n
    assert s.count(old) == 1, (label, s.count(old))
    s = s.replace(old, new, 1)
    n += 1
    print(f"  patched: {label}")


# ---- P1. the round-35 edit ledger --------------------------------------------
sub('''R34_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r34_edits.json",
                                                 encoding="utf-8"))]
''',
    '''R34_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r34_edits.json",
                                                 encoding="utf-8"))]
# ROUND-35 EXTENSION: the 4 paragraph-level blocks round 35 applied on top of the
# round-34 commit (c9718cf). This was the EPISTEMIC-HIERARCHY round, answering a
# 7/10 whose dimension scores average ~8.4 and whose 7 is an explicit discount
# for the claims-1-4-vs-claim-5 asymmetry. Every block is in a BOLDED file, which
# is why the replay below needs no appendix side-bag: methodology-1 is Part C's
# pure reorder (1330 chars in, 1330 out), methodology-2/-3 are Part A's five rung
# relabels, and conclusion-1 is Part B's independence claim (+15). appendix.tex is
# byte-identical to c9718cf this round, asserted at 35f.
# Generated by /tmp/gen_r35_edits.py, the same coalescing opcode walk that
# produced r29..r34_edits.json.
R35_EDITS = [tuple(x) for x in json.load(io.open("/tmp/r35_edits.json",
                                                 encoding="utf-8"))]
''', "P1 R35_EDITS load")

# ---- P2. replay the round-35 blocks before the word-multiset comparison ------
sub('''    predicted = words(rebuilt)
    actual = words(cur_cat)''',
    '''    # ROUND-35 EXTENSION: replay the round-35 blocks on top of the rebuilt
    # round-34 baseline. All four are in BOLDED files, so this is round 33's
    # simple form rather than round 34's side-bag -- and the ck() below is what
    # makes that claim falsifiable rather than asserted: a round-35 entry naming
    # a non-main file would fire here instead of being silently skipped.
    for name, tag, old, new in R35_EDITS:
        ck(name in BOLDED,
           f"round-35 ledger entry {tag} names a non-main file ({name}); "
           f"round 35 edited only methodology.tex, conclusion.tex and main.tex")
        if name not in BOLDED:
            continue
        ck(rebuilt.count(old) == 1,
           f"enumerated round-35 edit does not apply once to the rebuilt "
           f"round-34 baseline ({name}/{tag}): {old[:80]!r}")
        rebuilt = rebuilt.replace(old, new, 1)
    predicted = words(rebuilt)
    actual = words(cur_cat)''', "P2 R35 replay stage")

sub('round-23..34 edit accounts for: "', 'round-23..35 edit accounts for: "',
    "P2b ledger message range (lost)")
sub('round-23..34 edit accounts "', 'round-23..35 edit accounts "',
    "P2c ledger message range (gained)")

# ---- P3/P4. the prose-bold ledger gains Part B's label ----------------------
sub('''PROSE_BOLD = {"abstract": (18, 17), "introduction": (24, 52),
              "methodology": (29, 58), "experiments": (39, 51),
              "discussion": (6, 5), "conclusion": (10, 15)}''',
    '''# ROUND-35 SUBSTITUTION: conclusion 15 -> 16, the single span Part B adds --
# "(1)--(3) do not depend on (4)", which is their §8 ask verbatim in substance
# and was measurably absent ("does not depend" occurred 0 times in the main text
# at c9718cf). methodology is UNCHANGED at 58 on a round that rewrote five rung
# labels and reordered a paragraph: Part A's edits are all inside a float, and
# this ledger is computed on de_float()'d text, while Part C is a pure move and
# Part A's relabels are span-for-span (one \\textbf per column-1 cell before and
# after). Every other file unchanged, which is the point -- nothing was funded
# out of discussion.tex or the abstract.
PROSE_BOLD = {"abstract": (18, 17), "introduction": (24, 52),
              "methodology": (29, 58), "experiments": (39, 51),
              "discussion": (6, 5), "conclusion": (10, 16)}''',
    "P3 PROSE_BOLD conclusion 15 -> 16")

sub('''    ck(tot_was == 126 and tot_now == 198,
       f"the prose-bold ledger changed: {tot_was} -> {tot_now}, expected 126 -> 198")''',
    '''    # ROUND-35 SUBSTITUTION: 198 -> 199, the one span Part B adds (see
    # PROSE_BOLD). Net +1 on a round that cost zero rulers and moved none of the
    # document's 223 float/section page pins.
    ck(tot_was == 126 and tot_now == 199,
       f"the prose-bold ledger changed: {tot_was} -> {tot_now}, expected 126 -> 199")''',
    "P4 tot_now 198 -> 199")

# ---- P5. round 24's R5 pin follows rung 2's label ---------------------------
sub('''    ck(r"\\textbf{2. Asymmetry-independent} signal" in meth,
       "R5: fig:ladder rung 2 was not corrected")''',
    '''    # ROUND-35 SUBSTITUTION (Part A): rung 2's column-1 label becomes
    # "\\textbf{2. Demonstrated}: survives equalization". R5's SUBSTANCE is
    # unchanged and still double-pinned: what equalization removes is the
    # asymmetry between two prompts, so the rung may not be called
    # "instruction-independent" -- and "survives equalization" cannot be misread
    # that way at all, while 24b below still asserts the wrong wording is absent
    # from every main section. Measured, not guessed: "asymmetry-independent" as
    # a column-1 payload renders 156.30pt into a 159.34pt box (1.05mm of gap,
    # visually flush against column 2), which is why the word itself could not
    # survive the relabel; the shipped string renders 145.20pt. See 35b.
    ck(r"\\textbf{2. Demonstrated}: survives equalization" in meth,
       "R5: fig:ladder rung 2 lost its equalization label")''',
    "P5 R5 rung-2 pin")

# ---- P6. 31g's rung-label list, relabelled ----------------------------------
sub('''    for _rung in ["\\\\textbf{5. Causal deception signal ($D\\\\!\\\\to\\\\!S$, $\\\\tau_D$)}",
                  "\\\\textbf{4. Deception-\\\\emph{associated} signal}, fixed $E$",
                  "\\\\textbf{1. Instructed-condition discrimination}"]:
        ck(_rung in _lad31, f"31g: the ladder lost rung label {_rung!r}")''',
    '''    # ROUND-35 SUBSTITUTION (Part A, their §18): the three dominant rungs keep
    # their MEANING and gain the reviewer's own epistemic verbs, which is what
    # their §18 asked to be "the dominant thing a reviewer sees". 31g's property
    # -- that rungs 1/4/5 are visually dominant over the two grey diagnostics --
    # is unchanged and still pinned by the dim] count below.
    for _rung in ["\\\\textbf{5. Not identified}: causal $D\\\\!\\\\to\\\\!S$ ($\\\\tau_D$)",
                  "\\\\textbf{4. Possible}: deception-\\\\emph{associated}",
                  "\\\\textbf{1. Identified}: instructed contrast"]:
        ck(_rung in _lad31, f"31g: the ladder lost rung label {_rung!r}")''',
    "P6 31g rung labels")

# ---- P7. GROUP 35 -----------------------------------------------------------
GROUP35 = r'''
    # ==== GROUP 35 -- the EPISTEMIC-HIERARCHY round: their vocabulary, no new
    # label system, and zero budget spent ====================================
    # Round 35 answers a 7/10 Weak Accept (confidence 4/5) whose per-dimension
    # scores average ~8.4. The report explains the gap twice -- "Claims 1-4: very
    # strong. Claim 5: quite weak" (§2) and "this creates a strange asymmetry"
    # (§8) -- and their §18 names the remedy: make the epistemic hierarchy "the
    # dominant thing a reviewer sees". Their §17 lists three 7->8 items, of which
    # 2.5 were ALREADY in the tree and invisible to them because they reviewed a
    # build three rounds old (35e).
    # The round runs no experiment, changes no number, and costs nothing: 35g
    # asserts that all 223 \newlabel page pins are byte-identical to c9718cf.
    intro35, meth35, expt35, concl35, app35 = intro, meth, expt, concl, app
    _REPO35 = "/Users/mediratta/code/paper_writing/AI-Researcher-align"
    _PDIR35 = "output/adaptive_lie_detector_paper/"

    def _git35(path):
        _r = subprocess.run(["git", "show", "c9718cf:" + _PDIR35 + path],
                            cwd=_REPO35, capture_output=True, text=True)
        return _r.stdout if _r.returncode == 0 else None

    # ---- 35a. PART C (their §14): "why does this need a new named principle?
    # ... I might even move that sentence earlier." The status disclaimer was the
    # ECCP paragraph's THIRD sentence; it is now its second, immediately after
    # the italic statement. Asserted as an ORDER, not a presence -- presence was
    # already pinned by round 32, and presence is exactly what a future round
    # could satisfy while undoing this one.
    _eccp35 = ("\\textbf{The ECCP names a benchmark-design instance of standard "
               "pathway non-identifiability, not a new theoretical result}")
    _prop35 = ("The Proposition below is that statement for $k$ unobserved "
               "mechanisms; \\textbf{behavioral deception detection is the "
               "instantiation $(M_1,M_2)=(D,C)$}.")
    ck(_eccp35 in meth35,
       "35a: the ECCP status disclaimer is gone; it is the whole of their §14 "
       "answer and round 32 put it there")
    ck(_prop35 in meth35,
       "35a: the Proposition-instantiation sentence was edited, not moved -- "
       "Part C was a pure reorder and nothing in it may be rewritten")
    if _eccp35 in meth35 and _prop35 in meth35:
        ck(meth35.index(_eccp35) < meth35.index(_prop35),
           f"35a: the ECCP disclaimer is at offset {meth35.index(_eccp35)}, "
           f"AFTER the Proposition-instantiation sentence at "
           f"{meth35.index(_prop35)} -- their §14 asked for it earlier, and "
           f"this round moved it to the paragraph's second sentence")
    # and the move was free, which is the claim the letter makes: 1330 characters
    # of paragraph in, 1330 out. methodology.tex's net delta over the whole round
    # is -9 chars (15,696 -> 15,687), all of it Part A's five rung labels.
    ck(len(meth35) == 15_687,
       f"35a: methodology.tex is {len(meth35)} chars, expected 15,687 "
       f"(c9718cf's 15,696 less Part A's 9) -- Part C is a pure move and Part A "
       f"is confined to five \\rungrow column-1 arguments, so any other value "
       f"means an unledgered edit entered §2")

    # ---- 35b. PART A (their §18): the five rung labels now carry the
    # reviewer's own epistemic vocabulary. Pinned BOTH ways -- new present, old
    # absent -- because the failure mode of a relabel is a half-applied one.
    _lad35 = meth35[meth35.index("\\newcommand{\\rungrow}"):]
    _lad35 = _lad35[:_lad35.index("\\end{tikzpicture}")]
    _C1_35 = ["\\textbf{5. Not identified}: causal $D\\!\\to\\!S$ ($\\tau_D$)",
              "\\textbf{4. Possible}: deception-\\emph{associated}",
              "\\textbf{3. Diagnosed}: not surface form",
              "\\textbf{2. Demonstrated}: survives equalization",
              "\\textbf{1. Identified}: instructed contrast"]
    for _c35 in _C1_35:
        ck(_lad35.count("{" + _c35 + "}") == 1,
           f"35b: fig:ladder's column 1 does not carry {_c35!r} exactly once")
    for _old35 in ["\\textbf{5. Causal deception signal",
                   "\\textbf{4. Deception-\\emph{associated} signal}",
                   "\\textbf{3. Behavioural}, not surface form",
                   "\\textbf{2. Asymmetry-independent} signal",
                   "\\textbf{1. Instructed-condition discrimination}"]:
        ck(_old35 not in meth35,
           f"35b: fig:ladder still carries the pre-round-35 rung label "
           f"{_old35!r}, so the relabel is half-applied")
    # the five epistemic verbs map 1:1 onto their §18's five lines, and the
    # mapping is the deliverable: rung 5 is the one the paper does NOT reach, so
    # "Not identified" must be the TOP row's label and nothing else.
    ck(_lad35.index("Not identified") < _lad35.index("Possible")
       < _lad35.index("Diagnosed") < _lad35.index("Demonstrated")
       < _lad35.index("Identified}: instructed"),
       "35b: the epistemic labels are not in descending rung order 5->1, so the "
       "figure no longer reads top-down as their §18's hierarchy")
    # columns 2 and 3 are BYTE-UNCHANGED. Part A touched only the first \rungrow
    # argument of each row; if a relabel had spilled into the operational test or
    # the site column, the figure's three-column claim would stop being true.
    for _op35 in ["{\\textbf{5.} $\\mathrm{do}(D)$: $D$ set or randomised}",
                  "{\\textbf{4. criterion 4}: fix $E$, grade $D$ off-label}",
                  "{\\textbf{3. criteria 2--3}: re-extract cross-family}",
                  "{\\textbf{2. criterion 1}: one neutral prompt}",
                  "{\\textbf{1.} the benchmark as published}"]:
        ck(_lad35.count(_op35) == 1,
           f"35b: Part A disturbed the ladder's operational column: {_op35!r}")
    for _site35 in ["{\\emph{no design audited here}}",
                    "{\\textbf{materials we built}}",
                    "{the parameter-free lexical rule}",
                    "{equalization: it collapses}",
                    "{97.0\\% pooled}"]:
        ck(_lad35.count(_site35) == 1,
           f"35b: Part A disturbed the ladder's third column: {_site35!r}")
    ck("{What a design establishes}" in _lad35
       and "{Reached by: the operational test}" in _lad35
       and "{Where the audited work sits}" in _lad35,
       "35b: one of the ladder's three column headers changed; the first one is "
       "what makes the new epistemic labels read as claims about DESIGNS")
    ck("$\\uparrow$ \\textbf{this paper reaches rung 4, not rung 5}" in _lad35,
       "35b: the relabel took the break arrow with it")
    ck("\\textbf{This paper reaches rung~4, not rung~5}: the criterion-4 "
       "contrast we built (EXP-C4) exhibits a deception-\\emph{associated} "
       "signal at byte-identical elicitation---necessary for, but not equal to, "
       "$\\tau_D$." in meth35,
       "35b: fig:ladder's caption changed; Part A was a column-1 relabel and the "
       "caption is the site that says what rung 4 is worth")
    # ---- the OVERFLOW LAW, measured rather than eyeballed. \makebox[56mm][l]
    # pads with \hss, which shrinks infinitely, so an over-wide column-1 payload
    # produces NO Overfull warning -- it silently collides with column 2. The
    # budget is 56mm = 159.34pt. Measured with \settowidth under the paper's own
    # class and fonts (/tmp/measure_ladder.tex, round 35):
    #     rung 5  136.18pt    rung 4  121.89pt    rung 3  114.23pt
    #     rung 2  145.20pt    rung 1  118.08pt
    # and the two variants this round REJECTED for flushness:
    #     "2. Demonstrated: asymmetry-independent"  156.30pt  (1.05mm of gap)
    #     "2. Demonstrated: not the prompt asymmetry"  164.56pt  (overflows)
    # A visible-character bound is the cheap proxy that travels with the source:
    # every shipped payload is <= 38 visible chars and the rejected ones are 39
    # and 41.
    def _vis35(_t):
        _t = _t.replace("\\!", "").replace("\\to", "\u2192")
        _t = _t.replace("\\tau_D", "\u03c4D").replace("\\mathrm", "")
        _t = re.sub(r"\\(?:textbf|emph|small|scriptsize)\b", "", _t)
        return re.sub(r"[{}$]", "", _t)
    for _c35 in _C1_35:
        ck(len(_vis35(_c35)) <= 38,
           f"35b: fig:ladder column-1 payload {_vis35(_c35)!r} is "
           f"{len(_vis35(_c35))} visible chars; 56mm holds ~38 at \\small and "
           f"\\makebox overflows SILENTLY into column 2 -- re-measure with "
           f"\\settowidth before raising this bound")
    ck(_lad35.count("dim]") == 2,
       f"35b: {_lad35.count('dim]')} rungs are greyed, expected 2 -- the "
       f"relabel must not change which rungs are dominant")
    ck(_lad35.count("EXP-") == 0,
       "35b: a bare EXP code entered the ladder, which their §15 asked against")

    # ---- 35c. PART B (their §8, and the second half of their §17.2): "The
    # paper's principal result does not depend on criterion 4 being positive."
    # Measured absent at c9718cf: "does not depend" occurred 0 times in the main
    # text. This is the logical basis of the 7 -- their score is a discount for
    # the claims-1-4-vs-claim-5 asymmetry -- so it is pinned as a (fact, site)
    # triple: the conclusion states the independence, the conclusion's opening
    # down-weights (4)-(5), and §3.5 says the standing count is the finding.
    _indep35 = ("\\textbf{(1)--(3) do not depend on (4)}: it tests the reading "
                "that deception is undetectable, and the evidence runs against "
                "it.")
    ck(concl35.count(_indep35) == 1,
       "35c: the conclusion does not carry the independence claim exactly once; "
       "it is their §8 ask and the direct answer to the score discount")
    ck("The alternative reading---that deception is undetectable---is what (4) "
       "tests" not in concl35,
       "35c: the pre-round-35 sentence is still there, so Part B was added "
       "rather than substituted -- and an ADD at that site spills p9")
    ck("(4)--(5) as a weaker, target-dependent secondary finding" in concl35,
       "35c: round 31's down-weighting is gone; Part B's independence claim and "
       "that clause are one answer to their §17.2 and must stand together")
    ck("The standing 1-of-5 is itself a positive finding rather than a "
       "disappointment: once the elicitation confound is removed, detection is "
       "markedly less stable across targets than the instructed benchmark's "
       "near-ceiling accuracy suggests." in expt35,
       "35c: §3.5's secondary-finding sentence is gone -- it is the third leg "
       "of the §17.2 answer and the one the letter quotes back at them")
    # the numbering the independence claim uses is the CONCLUSION's own (1)-(5),
    # established one paragraph earlier, not tab:claim_ledger's. Both must be
    # present for the sentence to be readable at all.
    ck("\\textbf{We establish---(1)--(3) structurally or by replication, "
       "(4)--(5) as a weaker, target-dependent secondary finding:}" in concl35,
       "35c: the conclusion lost the sentence that DEFINES (1)-(5), which is "
       "what makes Part B's '(1)--(3) do not depend on (4)' resolvable")
    # and it renders on p9, inside the budget, not pushed to p10
    ck("do not depend on (4)" in _flat9,
       "35c: the independence claim is not on p9; the main text must end there")

    # ---- 35d. PART D: the build-identity stamp. Three consecutive reviews have
    # scored the round-31 tree -- their PDF filename, main(20260919-020957).pdf,
    # is 02:09:57 UTC = 07:39:57 IST, eleven seconds BEFORE round 31's commit
    # 3d2805e at 07:40:08 -- so rounds 32, 33 and 34 were invisible to them. The
    # stamp puts the provenance in the artifact instead of in the letter.
    _mtex35 = io.open("main.tex", encoding="utf-8").read()
    _stamp35 = ("\\textbf{Build identity.} Source revision~35, built "
                "19~September~2026 from parent\ncommit \\texttt{c9718cf}.")
    ck(_stamp35 in _mtex35,
       "35d: the build-identity stamp is missing from main.tex")
    ck(_mtex35.index("\\subsection*{Reproducibility statement}")
       < _mtex35.index("\\textbf{Build identity.}")
       < _mtex35.index("\\bibliographystyle"),
       "35d: the stamp is not inside the Reproducibility statement, which is "
       "where a reader looks for provenance")
    ck("The revision number increments once per review round" in _mtex35,
       "35d: the stamp no longer says what the revision number means, which is "
       "the only thing that makes it checkable by a reviewer")
    # it is FREE: it sits past the 9-page main text. Asserted from the render,
    # not from the source -- the whole point is where it lands.
    for _pg35 in range(1, 10):
        _f35 = " ".join(subprocess.run(
            ["pdftotext", "-f", str(_pg35), "-l", str(_pg35), "main.pdf", "-"],
            capture_output=True, text=True).stdout.split())
        ck("Source revision 35" not in _f35,
           f"35d: the build stamp rendered on p{_pg35}, inside the 9-page main "
           f"text -- it was costed as free because it lands after it")
    ck("Source revision 35" in " ".join(subprocess.run(
        ["pdftotext", "-f", "11", "-l", "11", "main.pdf", "-"],
        capture_output=True, text=True).stdout.split()),
       "35d: the build stamp is not on p11, where the Reproducibility statement "
       "ends -- if it moved, re-check that it is still outside the budget")
    # anonymity: the submission is double-blind, so the stamp may carry a date
    # and a hash and nothing else.
    # comment-stripped, because main.tex NAMES \iclrfinalcopy twice in prose
    # comments explaining when to uncomment it -- the property is that no
    # EXECUTABLE line carries it.
    ck(not [_ln for _ln in _mtex35.split("\n")
            if "\\iclrfinalcopy" in _ln.split("%")[0]],
       "35d: \\iclrfinalcopy is uncommented; the submission is double-blind")
    for _id35 in ["Mediratta", "Anupam", "github.com/"]:
        ck(_id35 not in _stamp35,
           f"35d: the build stamp carries author-identifying content: {_id35!r}")

    # ---- 35e. the §17 items that were ALREADY in the tree. These are not this
    # round's work; they are pinned because the letter's central claim is that
    # 2.5 of their three 7->8 items landed in rounds 31-34 and they could not see
    # them. If one of these regresses, the letter becomes false.
    ck("\\textbf{What is new.}" in intro35,
       "35e: round 34's novelty label is gone -- it is their §17.1 and the "
       "letter cites it as already-landed")
    ck("This is an identification problem, not a generalization one:" in absr,
       "35e: the abstract lost the sentence their own report quotes as its "
       "strongest")
    # round 33 folded this into fig:dag's CAPTION, which lives in
    # introduction.tex, and §3.2 carries the second instance. Checked at both
    # sites rather than in §2, where it has never been.
    ck("identification, not classification" in intro35
       and "identification, not classification" in expt35,
       "35e: the identification-not-classification anchor left fig:dag's "
       "caption or §3.2")
    ck(len([h for h in re.findall(r"\\subsection\{([^}]*)\}", expt35)
            if "Rung" in h]) == 4,
       "35e: round 33's four rung tags are gone; their §15 asked for fewer "
       "labels and round 33's reviewer asked for these, and the letter presents "
       "that as a conflict SHOWN, not silently resolved")
    # §15's decline, asserted as numbers so a later round cannot quietly drop the
    # two tags that exist only inside those titles.
    # NB: MAIN (and therefore main_txt) includes sections/related_work.tex,
    # which main.tex does NOT \input -- it is dead source whose content was
    # folded into the introduction and discussion rounds ago. It contributes
    # nothing to the PDF, so the two RENDERED inventories below are computed over
    # the six compiled files only. Using main_txt here would report 22 tags in 54
    # occurrences and 6 floats, none of which a reader can see.
    _compiled35 = "".join(read(_f + ".tex") for _f in BOLDED)
    _tags35 = re.findall(r"EXP-[A-Za-z0-9]+", _compiled35)
    ck(len(set(_tags35)) == 19 and len(_tags35) == 48,
       f"35e: the main text carries {len(set(_tags35))} distinct EXP tags in "
       f"{len(_tags35)} occurrences, expected 19/48 -- the §15 decline was "
       f"argued on those numbers")
    ck("EXP-R1b" in _compiled35 and "/XJ" in _compiled35,
       "35e: EXP-R1b or EXP-XJ left the main text; both appear ONLY inside "
       "§3 subsection titles (the body uses the compressed EXP-R1/R1c and "
       "EXP-XA/XJ idioms), so cutting the title tags deletes two experiments' "
       "traceability -- which is why §15 was declined with receipts")
    # their §5: the paper is STRONGER than the ask -- both figures, and which one
    # it relies on.
    ck("\\textbf{69.1\\%} with the most load-bearing pattern dropped is the "
       "figure we rely on; 79.8\\% on the full inventory a sensitivity result"
       in expt35,
       "35e: §3.3 no longer reports the drop-one 69.1% and the full-inventory "
       "79.8% with the reliance named; their §5 asked for less than this")

    # ---- 35f. WHAT THIS ROUND DID NOT TOUCH, asserted against c9718cf itself
    # rather than described. Round 35 edited exactly three files: main.tex,
    # sections/methodology.tex and sections/conclusion.tex.
    for _f35 in ["abstract", "introduction", "experiments", "discussion",
                 "appendix"]:
        _was35 = _git35("sections/%s.tex" % _f35)
        ck(_was35 is not None,
           f"35f: cannot read c9718cf:{_f35}.tex, so the unchanged-files claim "
           f"is unverifiable")
        if _was35 is None:
            continue
        ck(read(_f35 + ".tex") == _was35,
           f"35f: {_f35}.tex changed this round. Round 35 is a four-edit round "
           f"in methodology.tex, conclusion.tex and main.tex; an edit here was "
           f"not authorized -- and discussion.tex and the abstract are standing "
           f"no-fund sites")
    ck(main_txt.count("\\fbox{\\parbox") == 3,
       "35f: the three structured caution boxes must survive; every reviewer "
       "who has commented on them named them a strength")
    ck(len(re.findall(r"\\begin\{(?:figure|table)\}", _compiled35)) == 5,
       "35f: the main text no longer has exactly 5 floats -- their §13 asks for "
       "this architecture and the letter says it is already what they want")

    # ---- 35g. THE PRICE, measured: zero. Every \newlabel in the document --
    # all 223 of them, floats, sections and appendix alike -- sits on the same
    # page as at c9718cf. This is the strongest available statement that a
    # four-edit round at slack 0 cost nothing, and it is stricter than the
    # five-pin check above because it also catches an appendix float sliding.
    _auxw35 = _git35("main.aux")
    ck(_auxw35 is not None, "35g: cannot read c9718cf:main.aux")
    if _auxw35 is not None:
        def _pins35(_aux):
            return {_m.group(1): (_m.group(2), _m.group(3)) for _m in
                    re.finditer(r"newlabel\{([^}]*)\}\{\{([^}]*)\}\{(\d+)\}",
                                _aux)}
        _a35 = _pins35(_auxw35)
        _b35 = _pins35(io.open("main.aux", encoding="utf-8").read())
        ck(len(_a35) == 223 and len(_b35) == 223,
           f"35g: the document has {len(_b35)} labels, c9718cf had "
           f"{len(_a35)}, expected 223 in both")
        _moved35 = sorted(k for k in set(_a35) & set(_b35)
                          if _a35[k] != _b35[k])
        ck(not _moved35,
           f"35g: round 35 moved {len(_moved35)} label(s) off their c9718cf "
           f"page: {[(k, _a35[k], _b35[k]) for k in _moved35[:6]]} -- the round "
           f"was costed at zero rulers and this is the check that proves it")
        ck(not (set(_a35) ^ set(_b35)),
           f"35g: the label set changed: "
           f"{sorted(set(_a35) ^ set(_b35))[:8]}")
'''

sub("""
    # ---- report -----------------------------------------------------------
    if fails:""", GROUP35 + """
    # ---- report -----------------------------------------------------------
    if fails:""", "P7 GROUP 35")

io.open(DST, "w", encoding="utf-8").write(s)
print(f"wrote {DST} ({n} patches, {len(s)} chars)")
